### ISSUE TITLE
Not loading saves after purchasing BA

### ISSUE THREAD

**Issue by krazzyharry** [MegaMek/mekhq#1050]
Getting this error when trying to load saved game after purchasing BA.  CPNX and custom units available if needed.

This is what keeps popping up in the log...

  exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
   at java.util.TreeMap.getEntry(Unknown Source)
   at java.util.TreeMap.get(Unknown Source)
   at mekhq.campaign.Campaign.getPart(Campaign.java:1635)
   at mekhq.campaign.parts.BattleArmorSuit.getStickerPrice(BattleArmorSuit.java:272)
   at mekhq.campaign.parts.BattleArmorSuit.getStickerPrice(BattleArmorSuit.java:279)
   at mekhq.campaign.parts.BattleArmorSuit.g
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2794349/mekhqlog.txt)
etStickerPrice(BattleArmorSuit.java:279)
   at mekhq.campaign.parts.BattleArmorSuit.getStickerPrice(BattleArmorSuit.java:279)

**Comment by krazzyharry** [comment]
Corrected for next release per Hammer on BT forum  (New Development Snapshot 0.45.2 for Megamek, MegaMekLab)
