### ISSUE TITLE
Cannot create new Contract from Add Mission in Briefing Room

### ISSUE THREAD

**Issue by MattDroz** [MegaMek/mekhq#1082]
When trying to add a New Contract from the Briefing Room (Release 0.45.3), the dialog box does not open and nothing happens. I find the following in the mekhq logs:

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.dialog.NewAtBContractDialog.initComponents(NewAtBContractDialog.java:109)
	at mekhq.gui.dialog.NewContractDialog.<init>(NewContractDialog.java:86)
	at mekhq.gui.dialog.NewAtBContractDialog.<init>(NewAtBContractDialog.java:84)
	at mekhq.gui.BriefingTab.addMission(BriefingTab.java:346)
	at mekhq.gui.BriefingTab.lambda$initTab$1(BriefingTab.java:195)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

I'm able to create a new contract for the default campaign files, but not for my own. Attached is a zip of my current campaign file.
[Team Banzai30450401.zip](https://github.com/MegaMek/mekhq/files/2865290/Team.Banzai30450401.zip)

**Comment by NickAragua** [comment]
It looks like the campaign uses a lot of custom unit designs, so if you could zip those up and attach them to the issue, that'll enable us to load it up for troubleshooting.

**Comment by MattDroz** [comment]
[Team Banzai.zip](https://github.com/MegaMek/mekhq/files/2867891/Team.Banzai.zip)
Here's the Custom Mechfiles
