### ISSUE TITLE
Error in Campigan load file, will not load.

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1096]
### Environment
What version of MekHQ does your issue apply to?  45.3
What operating system are you using?  Windows, Mac, or Linux?  Windows 10
What java version are you using?   Version 8 update 201

### Description
Campigan file will not load: Specific error is:
java.lang.NullPointerException
	at mekhq.campaign.unit.Unit.resetPilotAndEntity(Unit.java:3080)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:589)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:194)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:118)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

### Files
All provided (CPNX file is in Onishi's Heavy Calvary4.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2883496/mekhqlog.txt)
[Custom.zip](https://github.com/MegaMek/mekhq/files/2883497/Custom.zip)

[Onishi's heavy calvary4.zip](https://github.com/MegaMek/mekhq/files/2883527/Onishi.s.heavy.calvary4.zip)

**Comment by sixlettervariables** [comment]
#1068 fixed that exact issue.
