### ISSUE TITLE
NPE when salvaging mech with Command Console

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#1101]
AtB generated a mission containing an enemy Cyclops CP-11-A-DC. After completing the mission, attempting to salvage the Cyclops results in an NPE and the mission cannot be resolved.

To reproduce, load the attached campaign, manually resolve using the attached mul, then try salvaging the Cyclops. (Note that salvaging any other unit from this mul works fine.)

[mekhq_npe_command_console.zip](https://github.com/MegaMek/mekhq/files/2892072/mekhq_npe_command_console.zip)

Also, not sure if this is related, but I noticed during the mission that the Cyclops had two crew members: a pilot and a commander. However, they were clones of the same character (i.e. same name and stats), but rolled for and sustained damage separately. (The commander clone actually died in-mission, but the pilot clone survived.)

```
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at mekhq.campaign.unit.Unit.resetPilotAndEntity(Unit.java:3080)
	at mekhq.campaign.Campaign.addTestUnit(Campaign.java:1085)
	at mekhq.campaign.ResolveScenarioTracker.resolveScenario(ResolveScenarioTracker.java:1244)
	at mekhq.gui.dialog.ResolveScenarioWizardDialog.finish(ResolveScenarioWizardDialog.java:1302)
	at mekhq.gui.dialog.ResolveScenarioWizardDialog.access$700(ResolveScenarioWizardDialog.java:80)
	at mekhq.gui.dialog.ResolveScenarioWizardDialog$6.actionPerformed(ResolveScenarioWizardDialog.java:1073)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at mekhq.gui.BriefingTab.resolveScenario(BriefingTab.java:528)
	at mekhq.gui.BriefingTab.lambda$initTab$13(BriefingTab.java:299)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

MekHQ v0.45.3
Ubuntu 18.04.2
OpenJDK v1.8.0_191

**Comment by NickAragua** [comment]
Unfortunately, I'm unable to reproduce this with provided campaign and mul. It must be one of those situations where closing and reopening mekhq makes the problem go away.

**Comment by RexPearce** [comment]
@NickAragua, thanks for checking. I'll double check on my end and see if I can reproduce.

**Comment by RexPearce** [comment]
@NickAragua, I'm still getting the same NPE on my end. I'll describe what I'm doing in more detail to make sure we're doing the same thing.

To reproduce:

- load the attached campaign
- go to the 'briefing screen'
- select pending mission 'Hide and Seek (Attacker)' (3/11/3046)
- click 'Resolve Manually'
- click 'Yes' to 'Did your side control battlefield..'
- select the attached mul
- click next until you reach the 'Claim Salvage' screen
- select the 'Cyclops CP-11-A-DC' for salvage
- click next until you reach the 'Preview' screen
- Click the Finish button. *** This is when the NPE is generated, and the resolve window doesn't disappear as it should.  You can click 'Finish' many times here, each time 'recovering' more units in the hanger.

Could you try the above and see if you get the same results?

**Comment by NickAragua** [comment]
Ok, it looks like I can reproduce this in 45.3, but not in the dev environment (e.g. building directly from the current state of the source). My conclusion is that a code change since fixed this behavior between the dev release and the current code state.

**Comment by RexPearce** [comment]
I just tested and it's fixed for me too in the latest master.
