### ISSUE TITLE
45.3 Repair not progressing

### ISSUE THREAD

**Issue by Arakash0** [MegaMek/mekhq#1113]
### Environment
MeqHQ 0.45.3
Java version 1.8.0_181
Windows 7

### Description
Playing an ATB campaign in MekHQ
In the repair bay, ive pressed do task on an item(scheduled would be the correct term i guess) but the repair doesn't get done no matter how many days i waited. In the Daily log there is no mention of the task being worked on or finished. I have to go to GM mode to manually complete it.

In the case of the save i provided the mech the bug was happening on was Warhammer-7A no17 repairing the small pulse laser

Ive run into this bug at least 4-5 times in the last few days of playing MekHQ.
Reloading apparently fixes the issue so im not exactly sure how what i can give you to let you reproduce it yourselves.
Looking through recently opened/closed issues i thought it might be this bug : https://github.com/MegaMek/mekhq/issues/1085 but it seems different enough that im not sure.

### Files
Ive provided the campaign file, log and custom mechs, but as I mentioned, when I save and reload the issue disappears.

[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2902176/mechfiles.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/2902177/mekhqlog.zip)
[Campaign save.zip](https://github.com/MegaMek/mekhq/files/2902178/Campaign.save.zip)

**Comment by Arakash0** [comment]
Noticed this bug again today.
I have a log file here from when I advanced a day, with the un-repaired item not being finished.  
[campaign file.zip](https://github.com/MegaMek/mekhq/files/2911372/campaign.file.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2911374/mechfiles.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/2911375/mekhqlog.zip)

Unlike the last log i posted, this one has an exception.

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 25, Size: 25
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at mekhq.gui.model.ScenarioTableModel.getScenario(ScenarioTableModel.java:106)
	at mekhq.gui.BriefingTab.refreshScenarioView(BriefingTab.java:849)
	at mekhq.gui.ActionScheduler.lambda$new$0(ActionScheduler.java:46)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Arakash0** [comment]
Here is another log, which shows a different set of Exceptions(10+ of them), but has the same effect (repair/replace not progressing). Again the problem disappears when i save and load.

[campaign save.zip](https://github.com/MegaMek/mekhq/files/2911649/campaign.save.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2911650/mechfiles.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/2911651/mekhqlog.zip)

**Comment by Arakash0** [comment]
Two mechs repairs not happening

War Dog - Replace Mech Left Torso Task (Scheduled)

Marauder - Replace Mech Head (Scheduled)

[campaign save.zip](https://github.com/MegaMek/mekhq/files/2922663/campaign.save.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2922664/mechfiles.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/2922665/mekhqlog.zip)

Exception visible in log:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.boardview.BoardView1.addAttack(BoardView1.java:4373)
	at megamek.client.ui.swing.boardview.BoardView1$14.gameNewAction(BoardView1.java:5192)
	at megamek.common.event.GameNewActionEvent.fireEvent(GameNewActionEvent.java:52)
	at megamek.common.Game.processGameEvent(Game.java:3136)
	at megamek.common.Game.addAction(Game.java:2350)
	at megamek.client.Client.receiveAttack(Client.java:1113)
	at megamek.client.Client.handlePacket(Client.java:1361)
	at megamek.client.Client$1$2.run(Client.java:217)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by sixlettervariables** [comment]
@Arakash0 which techs did you choose? I'm not able to replicate that on the latest code base.

**Comment by Arakash0** [comment]
@sixlettervariables I haven't recorded the tech that was being used at the time the bug happened in any of my reports, but if its helpful I will do so from now on.

That being said, considering as I mentioned in earlier posts the issue completely disappears whenever I reload the save, I have doubts that it would allow you to replicate it on your end reliably.

**Comment by sixlettervariables** [comment]
@Arakash0 I believe it is Tech related (running out of minutes even though it appears like they should have time).

**Comment by Arakash0** [comment]
Using the save, you can replicate the bug, no errors visible in log. 
[Campaign Save.zip](https://github.com/MegaMek/mekhq/files/2935206/Campaign.Save.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2935207/mechfiles.zip)

1. Go into hanger, select Warhammer-7A #16 'Repair' which is mothballed
	(Note: If you save->reload at any time after the mothball, this bug wont appear)
	(Note: Ive seen this bug appear when no mothballing/activating has happened)
2. Activate it using Ed Stranick (or any other tech with 480mins) This should do it immediately
3. In the hanger Set Warhammer #16 to Site- Factory
3. Go into repair bay, order all the parts you need
	(Note: If you use GM-Aquire Part Instantly, the bug wont appear.)
4. Go into warehouse then select Part status: In Transit
5. Turn on GM Tools, then select Deliver now on all parts in that view. 
6. Complete the 3 salvage tasks on the Warhammer using Mech Tech Sajid Lumo(any tech other than Peggy Malipeddi who has time to do the tasks in a day works fine here)
5. Select the replace Mech Right Arm Task, make Peggy Malipeddi do it.
6. Notice the task appear in the daily log on the right, then Advance a day

In the daily log there is no notification but the task still appears scheduled. Advancing days doesnt progress the task.
If you scroll down techs to Peggy Malipeddi, you will notice you can still select 'Do Task' With

**Comment by sixlettervariables** [comment]
Okay, so this has taken me a while to get back to, but it appears to work (at least on 0.45.4 and 0.45.5-SNAPSHOT).

I tried a few different variations and could not get it into the state you described.
