### ISSUE TITLE
Recursion in BattleArmorSuit::getTonnage

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#1115]
Not sure if its related but the the log file has some errors around equipment. Which I suspect is hand modifications to custom unit files.

Also the last error listed in the log is thousands of lines of 

```
Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at java.util.TreeMap.getEntry(Unknown Source)
	at java.util.TreeMap.get(Unknown Source)
	at mekhq.campaign.Campaign.getPart(Campaign.java:1665)
	at mekhq.campaign.parts.BattleArmorSuit.getTonnage(BattleArmorSuit.java:225)
	at mekhq.campaign.parts.BattleArmorSuit.getTonnage(BattleArmorSuit.java:227)
```

_Originally posted by @HammerGS in https://github.com/MegaMek/megamek/issues/1271#issuecomment-467161996_

**Comment by sixlettervariables** [comment]
Apparently I missed this in https://github.com/MegaMek/mekhq/pull/1011
