### ISSUE TITLE
MekHQ not randomly picking portraits .44

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1160]
From this forum post.
https://bg.battletech.com/forums/index.php?topic=64837.0

> New computer, new upload of MMHQ. Had just gotten fun in my last campaign, but no longer have that computer. Setting up, I downloaded the ink effects pic packs and unzipped them into "Male" and "Female" folders in the /images/portraits subfolder. Then, I opened MMHQ and hired some new people. Only MMHQ wouldn't generate pics for any of them. I've tried several ways (Males instead of male, etc.) but I'm stumped...
> 
> (Oh, and does the "Randomize Portrait(s)" EVER work?)
> 
> I'm sure it's something obvious I'm missing, but can't figure out what it is.

### Environment
What version of MekHQ does your issue apply to? 0.44.0

NPE from the Log.
```
java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(Unknown Source)
	at mekhq.gui.view.PersonViewPanel.setPortrait(PersonViewPanel.java:266)
	at mekhq.gui.view.PersonViewPanel.initComponents(PersonViewPanel.java:124)
	at mekhq.gui.view.PersonViewPanel.<init>(PersonViewPanel.java:105)
	at mekhq.gui.dialog.NewRecruitDialog.refreshView(NewRecruitDialog.java:57)
	at mekhq.gui.dialog.NewRecruitDialog.initComponents(NewRecruitDialog.java:86)
	at mekhq.gui.dialog.NewRecruitDialog.<init>(NewRecruitDialog.java:52)
	at mekhq.gui.CampaignGUI.hirePerson(CampaignGUI.java:1509)
	at mekhq.gui.CampaignGUI.access$1500(CampaignGUI.java:163)
	at mekhq.gui.CampaignGUI$21.actionPerformed(CampaignGUI.java:827)
```
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3000894/mekhqlog.txt)

**Comment by VicenteCartas** [comment]
Could you try in a newer version than 0.44 to see if this issue still happens?

**Comment by sixlettervariables** [comment]
Closed as likely stale, the source has significantly changed since 0.44.
