### ISSUE TITLE
Unable to hire from market with mechs

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#1170]
In the latest dev snapshot on windows (0.45.4), you can't hire people from the market if they come with a mech. If they are infantry, no problem, but mech warriors with mechs throw the following error:

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.text.DecimalFormat.format(Unknown Source)
	at java.text.Format.format(Unknown Source)
	at mekhq.gui.dialog.PersonnelMarketDialog.refreshPersonView(PersonnelMarketDialog.java:495)
	at mekhq.gui.dialog.PersonnelMarketDialog.personChanged(PersonnelMarketDialog.java:479)
	at mekhq.gui.dialog.PersonnelMarketDialog.lambda$initComponents$1(PersonnelMarketDialog.java:234)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)

**Comment by VicenteCartas** [comment]
That's related to the money changes. I'll take a look at it today.
