### ISSUE TITLE
Unable to delete a finance log transaction

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#1174]
Possibly related to #1170 , if you rtry to GM-delete a transaction from the finance log you get:

`
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.text.DecimalFormat.format(Unknown Source)
	at java.text.Format.format(Unknown Source)
	at javax.swing.text.InternationalFormatter.valueToString(Unknown Source)
	at mekhq.gui.dialog.EditTransactionDialog.buildMainPanel(EditTransactionDialog.java:134)
	at mekhq.gui.dialog.EditTransactionDialog.initGUI(EditTransactionDialog.java:79)
	at mekhq.gui.dialog.EditTransactionDialog.<init>(EditTransactionDialog.java:69)
	at mekhq.gui.adapter.FinanceTableMouseAdapter.actionPerformed(FinanceTableMouseAdapter.java:50)
`

**Comment by VicenteCartas** [comment]
I'll give it a look, thanks for reporting this!
