### ISSUE TITLE
Pregnant people cause a NPE when selecting them in Personnel tab

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#1330]
Playing new 47.1 HQ 
I found that when trying to select various people in the personnel tab, they would fail to load and cause a NPE error in the log.  Upon further research it seems that the link between all the personnel who are failing to load is that they are pregnant.  
[code]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.view.PersonViewPanel.fillInfo(PersonViewPanel.java:608)
	at mekhq.gui.view.PersonViewPanel.initComponents(PersonViewPanel.java:166)
	at mekhq.gui.view.PersonViewPanel.<init>(PersonViewPanel.java:125)
	at mekhq.gui.PersonnelTab.refreshPersonnelView(PersonnelTab.java:858)
	at mekhq.gui.PersonnelTab.lambda$initTab$2(PersonnelTab.java:270)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JTable.changeSelectionModel(Unknown Source)
	at javax.swing.JTable.changeSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Actions.actionPerformed(Unknown Source)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.JTable.processKeyBinding(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[/code]  

See https://bg.battletech.com/forums/index.php?topic=67484.0 for additional information.

**Comment by sixlettervariables** [comment]
Closed by #1331

**Comment by MarcJC** [comment]
Thank you for the quick work on this.  
Just to double check the error also occurred when selecting the person on the TO&E tab
I wanted to make sure the fix also fixed that tab also.

**Comment by sixlettervariables** [comment]
I'll confirm, but I believe so.

**Comment by sixlettervariables** [comment]
Confirmed, handles everywhere we display persons in MHQ.
