### ISSUE TITLE
Simca Ambulance possibly causing campaign to not load (NPE with Simca Ambulance?)

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/mekhq#1333]
### Environment
0.47.1
Windows 10

### Description
A unit I am trying to use in my campaign is likely causing an NPE when a campaign is attempting to load, after livestreaming a session with Megamek, I was purchasing some unit to create an SAR unit, including the Simca Ambulance.  I have also noticed after putting a full compliment of crew when putting the Simca Ambulance in the TO&E, The Ambulance happens to be an unspecified vehicle.  After purchasing it for the campaign (or adding it in GM mode), any time I attempted to save the campaign, then load it back up, it brings up a Campaign can't be loaded error.  

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3829720/mekhqlog.txt)

[Stormbringing Destoryers Bugged.zip](https://github.com/MegaMek/mekhq/files/3829722/Stormbringing.Destoryers.Bugged.zip)

**Comment by HammerGS** [comment]
NPE from the log

```
java.lang.NullPointerException
	at mekhq.campaign.io.CampaignXmlParser.processPartNodes(CampaignXmlParser.java:1710)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:271)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:210)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:129)
```

**Comment by CrimsonThunderSB** [comment]
I am guessing that's an error in the coding.
