### ISSUE TITLE
Issue with BattleArmor Parts. (java.lang.ArrayIndexOutOfBoundsException:)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#137]
In 0.3.31 we have two reported bugs that seem to be related to parts.

First:
http://bg.battletech.com/forums/index.php?topic=53882.msg1244787#msg1244787

@arlith Comment regarding bug
http://bg.battletech.com/forums/index.php?topic=53882.msg1245090#msg1245090

and here:
http://bg.battletech.com/forums/index.php?topic=53882.msg1247682#msg1247682

Possible description :
http://bg.battletech.com/forums/index.php?topic=53882.msg1245237#msg1245237
Both errors have this:

`java.lang.ArrayIndexOutOfBoundsException: -2
    at mekhq.campaign.unit.Unit.initializeParts(Unit.java:1805)
    at mekhq.campaign.Campaign.createCampaignFromXMLFileInputStream(Campaign.java:4004)
    at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:184)
    at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:113)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
`

I'm post from the forums no save game provided.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/423937/mekhqlog.txt)

**Comment by HammerGS** [comment]
Campaign File renamed as text cause won't let it attached as zip.


[Welshy's Baad Brew30650320.txt](https://github.com/MegaMek/mekhq/files/424085/Welshy.s.Baad.Brew30650320.txt)

**Comment by Dylan-M** [comment]
Marked Post-Stable since BA aren't yet fully implemented.

**Comment by neoancient** [comment]
This appears to be an issue with BA refits that was fixed some time ago. The last forum post listed confirms that this occured after a refit. Closing as resolved.
