### ISSUE TITLE
Campaign won't load. Numerous errors in Logs (maybe ClassCastException)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1432]
Reported on Discord.

This is originally a campaign being moved forward from an older version. Don't know which one.  Numerous issues in the log

### Environment
What version of MekHQ does your issue apply to? 47.3 (run from Repo)
What operating system are you using?  Windows (for both testing and from original poster)

### Description
I think the issue is this:
```
java.lang.ClassCastException: class megamek.common.weapons.autocannons.ISAC5 cannot be cast to class megamek.common.AmmoType (megamek.common.weapons.autocannons.ISAC5 and megamek.common.AmmoType are in unnamed module of loader 'app')
	at mekhq.campaign.parts.equipment.LargeCraftAmmoBin.getFullShots(LargeCraftAmmoBin.java:155)
	at mekhq.campaign.parts.equipment.LargeCraftAmmoBin.updateConditionFromEntity(LargeCraftAmmoBin.java:282)
	at mekhq.campaign.unit.Unit.runDiagnostic(Unit.java:535)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:683)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:210)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:129)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

### Files
[campaigns.zip](https://github.com/MegaMek/mekhq/files/4118011/campaigns.zip)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/4118012/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4118013/mekhqlog.txt)

**Comment by Mekslayer** [comment]
I believe the cpnx is from either 44.0 or 42.0.

How does it get fixed?

**Comment by cjfarls** [comment]
I have run into this issue today also.  Everything worked yesterday, now it goes through the load screen, but nothing opens up.  Have tried both 0.46.1 and an old copy of 0.46.0, as well as both the most recent campaign save and an older version.  Also reinstalled Java.  The log and campaign file (saved as a txt rather than CPNX file) are attached.

[Rupard's Roughriders 3034-01.txt](https://github.com/MegaMek/mekhq/files/4125623/Rupard.s.Roughriders.3034-01.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4125627/mekhqlog.txt)
