### ISSUE TITLE
Campaign won't Load - NPE in mekhq.campaign.parts.AeroSensor

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1439]
I have run into this issue today also.  Everything worked yesterday, now it goes through the load screen, but nothing opens up.  Have tried both 0.46.1 and an old copy of 0.46.0, as well as both the most recent campaign save and an older version.  Also reinstalled Java.  The log and campaign file (saved as a txt rather than CPNX file) are attached.  Running windows 10

[Rupard's Roughriders 3034-01.txt](https://github.com/MegaMek/mekhq/files/4125623/Rupard.s.Roughriders.3034-01.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4125627/mekhqlog.txt)

Okay, if I go back 5 saves (~6mo game time), I can open that cpnx file.  Attached
[Rupard's Roughriders 3033-07.txt](https://github.com/MegaMek/mekhq/files/4125643/Rupard.s.Roughriders.3033-07.txt)

_Originally posted by @cjfarls in https://github.com/MegaMek/mekhq/issues/1432#issuecomment-579543173_

**Comment by sixlettervariables** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.parts.AeroSensor.getBaseTime(AeroSensor.java:92)
	at mekhq.campaign.parts.Part.getActualTime(Part.java:804)
	at mekhq.campaign.parts.Part.getTimeLeft(Part.java:810)
	at mekhq.campaign.parts.Part.getRepairDesc(Part.java:469)
	at mekhq.gui.model.PartsTableModel.getValueAt(PartsTableModel.java:107)
	at javax.swing.table.TableRowSorter$TableRowSorterModelWrapper.getValueAt(Unknown Source)
	at javax.swing.DefaultRowSorter.compare(Unknown Source)
	at javax.swing.DefaultRowSorter.access$100(Unknown Source)
	at javax.swing.DefaultRowSorter$Row.compareTo(Unknown Source)
	at javax.swing.DefaultRowSorter$Row.compareTo(Unknown Source)
	at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.ComparableTimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at javax.swing.DefaultRowSorter.sort(Unknown Source)
	at javax.swing.DefaultRowSorter.allRowsChanged(Unknown Source)
	at javax.swing.JTable.notifySorter(Unknown Source)
	at javax.swing.JTable.sortedTableChanged(Unknown Source)
	at javax.swing.JTable.tableChanged(Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableDataChanged(Unknown Source)
	at mekhq.gui.model.DataTableModel.setData(DataTableModel.java:45)
	at mekhq.gui.WarehouseTab.refreshPartsList(WarehouseTab.java:699)
	at mekhq.gui.WarehouseTab.refreshAll(WarehouseTab.java:476)
	at mekhq.gui.CampaignGUI.lambda$initComponents$0(CampaignGUI.java:359)
	at java.lang.Iterable.forEach(Unknown Source)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:359)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:215)
	at mekhq.MekHQ.showNewView(MekHQ.java:347)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:310)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
```

**Comment by RexPearce** [comment]
Loads fine in latest dev - no exceptions generated. I clicked on all Aerospace units, no errors or visible issues.

There was a single unscramble warning, but that seems unrelated to above NPE:

```
unscrambleEquipmentNumbers : Could not unscramble equipment for Griffin GRF-1RR (12cb73e8-169d-4e2c-b22f-16294cd956c9)

 - PPC equipmentNum: 2
```
