### ISSUE TITLE
Thumper artillery vehicle causes array index out of bounds exception error 

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/mekhq#1470]
Windows 10

After downloading the 0.47.4 I attempted to load a campaign, the campaign fails to load.  I checked the log after, and noticed a array index out of bounds error.  I really don't want to have to redo this entire campaign if this is repairable.

java.lang.ArrayIndexOutOfBoundsException: 5
	at mekhq.campaign.unit.Unit.initializeParts(Unit.java:2268)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:685)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:210)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:129)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

[Bugged Stormbringing Destroyers.zip](https://github.com/MegaMek/mekhq/files/4183064/Bugged.Stormbringing.Destroyers.zip)

**Comment by neoancient** [comment]
Related to Megamek/megamek#1652
The Thumper Artillery Vehicle incorrectly had a turret indicated in the unit file, which resulted in turret, armor, and stabilizer parts in MekHQ. When the unit file was fixed the turret part locations exceeded the number of actual locations. I'll put in some checks to keep similar unit fixes from breaking campaigns in the future.

Here's the fixed campaign file.
[Bugged Stormbringind Destroyers-fixed.zip](https://github.com/MegaMek/mekhq/files/4183290/Bugged.Stormbringind.Destroyers-fixed.zip)

**Comment by CrimsonThunderSB** [comment]
Thank you Ancient, very much appreciated, and if I find anything else, I will let you know.

**Comment by neoancient** [comment]
I'm going to leave this open until the preventative measures are in place.

**Comment by HammerGS** [comment]
This is the original Thumper file if anyone needs it.
[Thumper Artillery Vehicle.zip](https://github.com/MegaMek/mekhq/files/4183558/Thumper.Artillery.Vehicle.zip)
