### ISSUE TITLE
Megamek crashing on Loading Save after removing Gyro in order to replace.

### ISSUE THREAD

**Issue by Kurios** [MegaMek/mekhq#15]
This is the end result of trying to replace a gyro and a cockpit.  If I can figure out what actually went wrong code wise, I'll add more commentary.

But now with hot crash on load action.

```
Starting load of AtB configuration data from XML...
Starting load of news data for 3041 from XML...
loaded 0 days of news items for 3041
Load of campaign file complete!


Starting load of faction hint data from XML...
RAT files loaded
The unit Truck (AC Conversion) could not be found in the CivilianUnits RAT (data\rat\Against The Bot\CivilianUnits.txt)
The unit Truck (SRM Conversion) could not be found in the CivilianUnits RAT (data\rat\Against The Bot\CivilianUnits.txt)
The unit Truck (AC Conversion) could not be found in the CivilianUnits_CivVeh RAT (data\rat\Against The Bot\CivilianUnits_CivVeh.txt)
The unit Truck (SRM Conversion) could not be found in the CivilianUnits_CivVeh RAT (data\rat\Against The Bot\CivilianUnits_CivVeh.txt)
Loaded Rats in: 5000ms.
Staring MegaMekLab version: 0.1.49-git
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.parts.MissingMekGyro.getNewPart(MissingMekGyro.java:162)
	at mekhq.campaign.parts.MissingPart.getDetails(MissingPart.java:187)
	at mekhq.campaign.Campaign.getPartsInUse(Campaign.java:1129)
	at mekhq.gui.CampaignGUI.refreshOverviewPartsInUse(CampaignGUI.java:4770)
	at mekhq.gui.CampaignGUI.refreshOverview(CampaignGUI.java:4754)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:752)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:553)
	at mekhq.MekHQ.showNewView(MekHQ.java:166)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:278)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

```
[Purple Legion30411011.zip](https://github.com/MegaMek/mekhq/files/135460/Purple.Legion30411011.zip)

**Comment by Kurios** [comment]
Or it loads just fine in the current dev version. Thats what I get for pulling it off git to fix it myself. (Horray for staring at a wall for 2 minutes, going, I should just fix this myself, and pulling source to go and do it, only to be disappointingly disappointed at the lack of a need of a fix... BUT ONWARDS TO MY OTHER ISSUES SO FAR THAT HAVE YET TO BE ISSUED!!!)

**Comment by arlith** [comment]
Yea, this was fixed for 8c7a038 and should have been in the latest release, but there was an issue with the release and it pulled from the wrong repo so was a bit behind.  There should be a new release soon with this issue in it (it happens with gyros and cockpits, the more common reports were for cockpits).

**Comment by Kurios** [comment]
Completely out of place question, but:

Some of the GUI dialogs have a comment like:
```
       /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
```

What Form Editor should I be using? Or should I disregard the warnings?

**Comment by arlith** [comment]
I'm actually not certain.  I would imagine Taharqa would know, as he's probably the one who originally worked with that code but since then he has mentioned not wanting to use any form editors.  The only form editor for Java that I am aware of is the one in NetBeans.

**Comment by Dylan-M** [comment]
While there are other form editors for Java, arlith is correct. It's from Netbeans, and can safely be ignored. In fact, we should remove them.
