### ISSUE TITLE
Unable to right click on Meteor-U Fighter

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#1537]
Playing ATB in HQ 47.4 completed a mission where I shot down and salvaged 2 Heavy Strike Fighters. 
One was a Inseki II and the other was a Meteor-U.  When I went into the hangar to assign techs the Inseki had no issue but the game refuses to right click on the Meteor. 

The Log shows the following error.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
   at mekhq.Utilities.getMunitionsFor(Utilities.java:258)
   at mekhq.gui.adapter.UnitTableMouseAdapter.maybeShowPopup(UnitTableMouseAdapter.java:673)
   at mekhq.gui.adapter.UnitTableMouseAdapter.mouseReleased(UnitTableMouseAdapter.java:604)
   at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
   at java.awt.Component.processMouseEvent(Unknown Source)
   at javax.swing.JComponent.processMouseEvent(Unknown Source)
   at java.awt.Component.processEvent(Unknown Source)
   at java.awt.Container.processEvent(Unknown Source)
   at java.awt.Component.dispatchEventImpl(Unknown Source)
   at java.awt.Container.dispatchEventImpl(Unknown Source)
   at java.awt.Component.dispatchEvent(Unknown Source)
   at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
   at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
   at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
   at java.awt.Container.dispatchEventImpl(Unknown Source)
   at java.awt.Window.dispatchEventImpl(Unknown Source)
   at java.awt.Component.dispatchEvent(Unknown Source)
   at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
   at java.awt.EventQueue.access$500(Unknown Source)
   at java.awt.EventQueue$3.run(Unknown Source)
   at java.awt.EventQueue$3.run(Unknown Source)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
   at java.awt.EventQueue$4.run(Unknown Source)
   at java.awt.EventQueue$4.run(Unknown Source)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
   at java.awt.EventQueue.dispatchEvent(Unknown Source)
   at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
   at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
   at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

Saves are attached. 

Any idea why this craft causes an issue?
[Right Click error.zip](https://github.com/MegaMek/mekhq/files/4271218/Right.Click.error.zip)

**Comment by NickAragua** [comment]
Looks like this is fixed in the current state of the master branch.

**Comment by NickAragua** [comment]
Having encountered it in a separate situation, it looks like the issue is that the aircraft in question had bombs. There's some kind of transition issue between MegaMek and MekHQ when a generated aircraft also has bombs.

**Comment by Windchild292** [comment]
The display issue is fixed in #2149, however the underlying issue with bombs has not been fixed.

**Comment by Windchild292** [comment]
#3211 is a breaking symptom of this, which is fixed in #3213. That handling can be removed once this is fixed.
