### ISSUE TITLE
Failure to save game

### ISSUE THREAD

**Issue by KiloWhiskey1** [MegaMek/mekhq#1636]
### Environment
What version of MekHQ does your issue apply to? 47.5
What operating system are you using?  Windows, Mac, or Linux? Windows 10
Java version 1.8.0_231

### Description
Game will not save megamelog is tossing out a null pointer exception.

18:57:41,266 INFO [mekhq.gui.CampaignGUI] {AWT-EventQueue-0} 
Saving campaign...

18:57:45,973 INFO [mekhq.Utilities] {AWT-EventQueue-0} 
File copied.

18:57:46,187 ERROR [mekhq.gui.CampaignGUI] {AWT-EventQueue-0} 

java.lang.NullPointerException
	at mekhq.campaign.ExtraData.isEmpty(ExtraData.java:182)
	at mekhq.campaign.personnel.Person.writeToXml(Person.java:2124)
	at mekhq.campaign.Campaign.writeMapToXml(Campaign.java:4846)
	at mekhq.campaign.Campaign.writeToXml(Campaign.java:4645)
	at mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1418)
	at mekhq.gui.CampaignGUI.menuSaveXmlActionPerformed(CampaignGUI.java:1384)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

18:59:44,629 INFO [mekhq.Utilities] {AWT-EventQueue-0} 
File copied.

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/4441355/megameklog.txt)

**Comment by Windchild292** [comment]
I'd need to see your campaign file to figure this out

**Comment by KiloWhiskey1** [comment]
The cpnx file?

**Comment by Windchild292** [comment]
Correct

**Comment by KiloWhiskey1** [comment]
Getting a "We don't support that file type" when I try to drop it here.

**Comment by Windchild292** [comment]
You will need to zip the file before uploading

**Comment by KiloWhiskey1** [comment]
Rgr Thanks
[RedRum30391202.zip](https://github.com/MegaMek/mekhq/files/4441377/RedRum30391202.zip)

**Comment by KiloWhiskey1** [comment]
If it helps When I first transferred files over to 47.1 "Kill Roy's Little Buddy" was giving it fits trying to load. I eventually just moved my whole mechfiles folder over from 47.4

**Comment by Windchild292** [comment]
I forgot, I'm also going to need any of your custom mechfiles

**Comment by KiloWhiskey1** [comment]
[customs.zip](https://github.com/MegaMek/mekhq/files/4441389/customs.zip)

**Comment by KiloWhiskey1** [comment]
Thanks for your help BTW. You guys are rockstars.

**Comment by Windchild292** [comment]
I'm still missing Mackie MSK-9HKR 'Kill-Roy’s Little Buddy', and can't load because of that.

**Comment by KiloWhiskey1** [comment]
[mechs.zip](https://github.com/MegaMek/mekhq/files/4441403/mechs.zip)
Its the Mech file from 47.4 the mech file from 47.5 wouldn't load it.

**Comment by Windchild292** [comment]
Ah, we will need to add a note for that.

Otherwise, I fixed the issue, which was related to bad data in the .cnpx file. This is the fixed copy, and also includes [RedRum30391202.zip](https://github.com/MegaMek/mekhq/files/4441426/RedRum30391202.zip) the proper fix for the Mackie (but that requires the data files for 47.5)

**Comment by KiloWhiskey1** [comment]
Thanks for your time. You guys are great thanks to your work I get to play Battletech again its been a long time and I am so grateful for it.

**Comment by Windchild292** [comment]
Welcome, hope you have fun and I'll take a look to see if there is anything that can be done to prevent this in the future.

**Comment by Windchild292** [comment]
That PR should prevent this in future @KiloWhiskey1, and have fun playing 😄

**Comment by Windchild292** [comment]
Fixed by #1643.
