### ISSUE TITLE
NPE: campaign fails to advance day properly 47.6

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#1753]
mekHQ 47.6, win 10

when the advance day button is pressed daily log does not reset but posts the new date at end of current log.  actions that are supposed to progress with the day do not, i.e. repairs are not done, scenarios not generated if its a week advance, etc.  log shows a NPE.

[error.zip](https://github.com/MegaMek/mekhq/files/4637437/error.zip)

**Comment by HammerGS** [comment]
NPE from Log

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.Campaign.processNewDayATBScenarios(Campaign.java:3353)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:3547)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3773)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$35(CampaignGUI.java:1136)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
```

**Comment by bczretribution** [comment]
anything i can do to fix my campaign? or do i need to wait for the release?

**Comment by sixlettervariables** [comment]
Try GM setting your current location.

**Comment by bczretribution** [comment]
worked, thank you!
