### ISSUE TITLE
47.7 Tracking  - Time in Rank - results in multiple glitches 

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#1819]
47.7
Linux
Java 11.0.5

Enabling: Track Time in Rank results in multiple glitches:

Marketplace/Hire/Mechwarrior/ Regenerate (GM)      - feature fails to respond
Main Screen/Personnel Tab         - hangs or becomes unresponsive
Main Screen/Personnel Tab       - Personnel Bio blanks 
Main Screen/Personnel Tab/Change Portrait    - Drop-down fails to display all categories

To reproduce this issue:
Open a fresh install of MekHQ 47.7, select Load Last Save
Campaign Options/Personnel/ Enable "Track Time in Rank"

[Campign File.cpnx.zip](https://github.com/MegaMek/mekhq/files/4822699/Campign.File.cpnx.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4822701/mekhqlog.txt)

**Comment by HammerGS** [comment]
Pages of this error repeated

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.personnel.Person.getLastRankChangeDateAsString(Person.java:1184)
	at mekhq.gui.view.PersonViewPanel.fillInfo(PersonViewPanel.java:743)
	at mekhq.gui.view.PersonViewPanel.initComponents(PersonViewPanel.java:106)
	at mekhq.gui.view.PersonViewPanel.<init>(PersonViewPanel.java:89)
	at mekhq.gui.dialog.NewRecruitDialog.refreshView(NewRecruitDialog.java:66)
	at mekhq.gui.dialog.NewRecruitDialog.changeRank(NewRecruitDialog.java:263)
	at mekhq.gui.dialog.NewRecruitDialog.lambda$createSidebar$4(NewRecruitDialog.java:144)
```

**Comment by Windchild292** [comment]
Which means the value was not initialized properly.

**Comment by Windchild292** [comment]
The issue is that time in rank was written as if a copy of time in service, and I blindly copied down the previous method from Time in Service there. If you have both enabled, it will work in the meantime.
