### ISSUE TITLE
0.47.9 - Error loading campaign

### ISSUE THREAD

**Issue by Leraje2** [MegaMek/mekhq#1920]
Hi,

I ran into an a problem while attempting to load save from 0.47.6 into the 0.47.9 version. Log file indicates the following error:

15:26:38,070 ERROR [mekhq.gui.dialog.DataLoadingDialog$Task] {SwingWorker-pool-1-thread-1} 
doInBackground() : null
java.lang.NullPointerException
	at mekhq.campaign.io.CampaignXmlParser.migrateAncestorNodes(CampaignXmlParser.java:1916)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:278)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:201)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:120)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Save, Custom files and logs:
[Support files.zip](https://github.com/MegaMek/mekhq/files/5065294/Support.files.zip)

Please check and let me know what can be done to fix the issue.

Thank you.

**Comment by Windchild292** [comment]
Sorry for the inconvenience, I'll try to get to this tonight with a fix

**Comment by Windchild292** [comment]
[SAVE.zip](https://github.com/MegaMek/mekhq/files/5066292/SAVE.zip)

**Comment by Windchild292** [comment]
That should work

**Comment by Leraje2** [comment]
Thank you.

**Comment by Windchild292** [comment]
Welcome, and sorry for the inconvenience
