### ISSUE TITLE
Healing DS pilots who are impossible to heal in Mek HQ

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#1923]
DS pilots that are used in battle, even if they do not take a pilot hit show Pilot damage in all versions from 47-2 thru 49-9
of MekHQ. I will send a picture as my HQ file is too large with many custom units. But the DS' are all standard.

Here is a picture of the situation.

![DS_Pilot_Damage_Image](https://user-images.githubusercontent.com/25534324/90303760-97ea4f80-de65-11ea-9902-18735cc690ea.jpg)

### Environment
What version of MekHQ does your issue apply to? ALL
What operating system are you using?  Windows 
What java version are you using?  
megamek.common.loaders.EntityLoadingException: Unsupported file suffix
	at megamek.common.MechFileParser.parse(MechFileParser.java:201)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:85)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:77)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:565)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:237)
	at megamek.common.MechSummaryCache.lambda$getInstance$0(MechSummaryCache.java:86)
	at java.lang.Thread.run(Unknown Source)

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
(Delete the above lines)

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt and mekhqlog.txt files
(Delete the above lines)

**Comment by Windchild292** [comment]
I'm going to need the campaign file and customs to investigate this.

**Comment by Windchild292** [comment]
Closing, will reopen if information is provided.
