### ISSUE TITLE
Bug:  No Personnel Market updates - log errors

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1952]
ATB Campaign is no longer generating new recruits for market.  I noted in logs that I'm getting this error:

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.ThreadLocalRandom.nextDouble(Unknown Source)
	at mekhq.campaign.universe.RangedFactionSelector.selectFaction(RangedFactionSelector.java:111)
	at mekhq.campaign.personnel.generator.DefaultPersonnelGenerator.createPerson(DefaultPersonnelGenerator.java:62)
	at mekhq.campaign.personnel.generator.DefaultPersonnelGenerator.generate(DefaultPersonnelGenerator.java:81)
	at mekhq.campaign.Campaign.newPerson(Campaign.java:1329)
	at mekhq.campaign.Campaign.newPerson(Campaign.java:1312)
	at mekhq.campaign.Campaign.newPerson(Campaign.java:1281)
	at mekhq.campaign.Campaign.newPerson(Campaign.java:1269)
	at mekhq.module.atb.PersonnelMarketAtB.generatePersonnelForDay(PersonnelMarketAtB.java:98)
	at mekhq.campaign.market.PersonnelMarket.generatePersonnelForDay(PersonnelMarket.java:109)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3675)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$33(CampaignGUI.java:1064)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

[Kendricke's Templars30211029.zip](https://github.com/MegaMek/mekhq/files/5106529/Kendricke.s.Templars30211029.zip)

**Comment by Windchild292** [comment]
I'm missing all of the customs required in the supplies campaign file and cannot test for this.

**Comment by Kendricke** [comment]
Whoops!

Attached.
[customs.zip](https://github.com/MegaMek/mekhq/files/5120591/customs.zip)

**Comment by Windchild292** [comment]
I'm also going to need your custom awards

**Comment by Kendricke** [comment]
Sure thing:

[awards.zip](https://github.com/MegaMek/mekhq/files/5120711/awards.zip)
