### ISSUE TITLE
Megamek won't launch from MekHQ using Eclipse.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1969]
Have been able to play MekHQ running from Eclipse. This morning went to start a game. MekHQ will launch from Eclipse but when I hit start game Megamek doesn't launch.  

### Environment
What version of MekHQ does your issue apply to? 47.10-SNAPSHOT run from the Repo
What operating system are you using?  Windows

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5125496/mekhqlog.txt)
[The Harriers30460505.zip](https://github.com/MegaMek/mekhq/files/5125500/The.Harriers30460505.zip)

**Comment by HammerGS** [comment]
@algebro seems related to serial killer.

**Comment by Algebro7** [comment]
Can you attach megameklog.txt if there is one?

**Comment by HammerGS** [comment]
java.lang.NullPointerException
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:208)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:180)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:203)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:197)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Line 208 references serial killer.

It's not generating a MegaMekLog
