### ISSUE TITLE
Resolving battles manually with a Battle Report file

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#1974]
I wish to be able to Resolve Battles Manually in MekHQ.

I Use Megamek to load my recovered units and add them to the salvage Mul file and save the entire unit list as a Battle Report File. Then in MekHQ I click on Resolve Manually in the Briefing Room Tab. I say yes I controlled the battlefield, then select my Battle Report FIle, and every time I do, even though all the units show as damaged in the Mul file, the resolution window in MekHQ shows all the units as undamaged. What is wrong with this picture?

### Environment
47.9
What version of MekHQ does your issue apply to?
What operating system are you using?  Windows, Mac, or Linux?
Win 10 
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

megamek.common.loaders.EntityLoadingException: Unsupported file suffix
	at megamek.common.MechFileParser.parse(MechFileParser.java:201)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:85)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:77)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:565)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:524)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:237)
	at megamek.common.MechSummaryCache.lambda$getInstance$0(MechSummaryCache.java:86)

(Delete the above lines)

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
(Delete the above lines)

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt and mekhqlog.txt files
(Delete the above lines)

**Comment by NickAragua** [comment]
I think we're going to need a campaign save and the MUL in question.

**Comment by Windchild292** [comment]
Closing, will reopen if information is provided.
