### ISSUE TITLE
NPE in mekhq.gui.handler.TOETransferHandler.canImport

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1981]
The TOE error was me bringing a unit out of refit. It appeared in the TOE and then I couldn't drag it to a force. Also I swear we used to be able to drag and drop to re-order the TOE.

### Environment
What version of MekHQ does your issue apply to? 47.10 SNAPSHOT
What operating system are you using?  Windows, 

NPE
```
java.lang.NullPointerException
	at mekhq.gui.handler.TOETransferHandler.canImport(TOETransferHandler.java:109)
	at java.desktop/javax.swing.TransferHandler$DropHandler.handleDrag(TransferHandler.java:1467)
	at java.desktop/javax.swing.TransferHandler$DropHandler.dragOver(TransferHandler.java:1496)
	at java.desktop/java.awt.dnd.DropTarget.dragOver(DropTarget.java:379)
	at java.desktop/javax.swing.TransferHandler$SwingDropTarget.dragOver(TransferHandler.java:1250)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processMotionMessage(SunDropTargetContextPeer.java:482)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchMotionEvent(SunDropTargetContextPeer.java:835)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:781)
```

[The Harriers30460613.cpnx.gz](https://github.com/MegaMek/mekhq/files/5159687/The.Harriers30460613.cpnx.gz)
[megameklog (1).txt](https://github.com/MegaMek/mekhq/files/5159688/megameklog.1.txt)
[mekhqlog (1).txt](https://github.com/MegaMek/mekhq/files/5159689/mekhqlog.1.txt)

**Comment by Windchild292** [comment]
This would be the file that handles drag and drop

**Comment by Windchild292** [comment]
From a code look, did you drag and drop so it was a child of another unit?

**Comment by HammerGS** [comment]
Not that I was aware of. I was trying to order the lances, kinda picky and like my Mech lances on the top of the list.

**Comment by Windchild292** [comment]
I did fix two NPEs from code side, will test when I am able to.
