### ISSUE TITLE
[dev branch] "Monthly Supply Cost Report" dialog doesn't work

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#2021]
When using CamOps spare parts costs, selecting a unit in the hangar, and clicking the 'monthly supply cost report' in the right click menu, the report doesn't show up, instead opting to log the following exception:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.dialog.UnitCostReportDialog.<init>(UnitCostReportDialog.java:35)
	at mekhq.gui.CampaignGUI.showUnitCostReport(CampaignGUI.java:1736)
	at mekhq.gui.adapter.UnitTableMouseAdapter.actionPerformed(UnitTableMouseAdapter.java:194)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)

**Comment by NickAragua** [comment]
Can't reproduce this with the save I used and the latest dev branch.

**Comment by Windchild292** [comment]
This does not make any sense to me, unless I'm missing something obvious.
This is the line in question:
` txtReport.setText(unit.displayMonthlyCost());`
The method line in question is null protected for the unit (the CampaignGUI method checks before it hits it), and I cannot find a way for it to get here without txtReport initializing.

**Comment by NickAragua** [comment]
Going to close it for now, as I haven't seen it since then.
