### ISSUE TITLE
Campaign File Won't Load (NPE in campaign.finances.Money.plus)

### ISSUE THREAD

**Issue by ImperiumKnight** [MegaMek/mekhq#2166]
### Environment
MekHQ  47.11
Windows
Java Oracle 8 Version 1.8.0_271-b09

### Description
Campaign just quit loading and when attempting to load it just gives me an unable to load message.  Was working fine earlier today and quit after I saved and then went to come back to the campaign file.

### Files
[1st Winters' Legion.zip](https://github.com/MegaMek/mekhq/files/5435761/1st.Winters.Legion.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5435764/mekhqlog.txt)

**Comment by HammerGS** [comment]
We also need the megameklog.txt

**Comment by Windchild292** [comment]
`15:42:51,524 ERROR [mekhq.gui.dialog.DataLoadingDialog$Task] {SwingWorker-pool-1-thread-1} 
doInBackground(), line 230 : null
java.lang.NullPointerException
	at mekhq.campaign.finances.Money.plus(Money.java:108)
	at mekhq.campaign.parts.BattleArmorSuit.getStickerPrice(BattleArmorSuit.java:274)
	at mekhq.campaign.parts.BattleArmorSuit.isSamePartType(BattleArmorSuit.java:326)
	at mekhq.campaign.parts.Part.isSamePartTypeAndStatus(Part.java:551)
	at mekhq.campaign.Campaign.checkForExistingSparePart(Campaign.java:6455)
	at mekhq.campaign.Campaign.addPartWithoutId(Campaign.java:1750)
	at mekhq.campaign.Campaign.importParts(Campaign.java:1727)
	at mekhq.campaign.io.CampaignXmlParser.processPartNodes(CampaignXmlParser.java:1585)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:261)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:210)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:122)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

Loads fine in latest development.

**Comment by ImperiumKnight** [comment]
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5435823/megameklog.txt)

Here is the megameklog file.

**Comment by Windchild292** [comment]
Closed as fixed in latest develop.

**Comment by sixlettervariables** [comment]
Ultimately I think we could make `Money::plus` and `Money::minus` treat `null` as `Money.zero()`.
