### ISSUE TITLE
47.12 Stock save games will not load

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#2213]
47.12
Linux

Fresh install with no modifications or alterations
 
"Load Last Save' From the boot screen or attempting to load the stock save games from the Campaign folder produce campaign loading error popup. Selecting 'Start New Campaign' loads without issue. 

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5508076/mekhqlog.txt)

**Comment by jasntiamak** [comment]
Same issue here.  

[Onderon's Outlaws30671220_save.cpnx.gz](https://github.com/MegaMek/mekhq/files/5508100/Onderon.s.Outlaws30671220_save.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5508101/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5508102/mekhqlog.txt)
21:34:42,271 INFO [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
processPartNodes(), line 1411 : Loading Part Nodes from XML...

21:34:42,290 ERROR [mekhq.campaign.parts.Part] {SwingWorker-pool-1-thread-1} 
generateInstanceFromXML(), line 860 : null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at mekhq.campaign.parts.Part.generateInstanceFromXML(Part.java:784)
	at mekhq.campaign.io.CampaignXmlParser.processPartNodes(CampaignXmlParser.java:1433)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:261)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:211)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:123)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at mekhq.campaign.parts.AmmoStorage.<init>(AmmoStorage.java:61)
	at mekhq.campaign.parts.AmmoStorage.<init>(AmmoStorage.java:55)
	... 16 more

**Comment by sixlettervariables** [comment]
That's on me, a final merge prior to release didn't get run through a Campaign, only the tests. Working on a fix now.

**Comment by sixlettervariables** [comment]
Tests covering this in #2227.
