### ISSUE TITLE
47.13 Certain awards cause personnel information to blank 

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#2220]
47.13
Linux
Java 11.0.8

Clean install with no modifications or customization, there appear to be some awards which cause information (Mechwarrior, Status, Origin, Age, Skill Names, etc.) to disappear from within the personnel display on the upper right side of the screen. 

I noticed this issue when attempting to import my custom award set to 47.12 and, in addition to the blank personnel screen detailed above, some of the ribbons from my custom set also failed to display. (log and custom awards file from that attempt have not been included here)  

The issue can be recreated using various awards from the 'standard' set as demonstrated here using the 'Medal of Honor' award featured in the attached screenshots.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5518231/mekhqlog.txt)

![AwardScreen1](https://user-images.githubusercontent.com/30708294/98692683-3e8aa300-2324-11eb-8eea-28bd86be4c57.png)

![AwardScreen2](https://user-images.githubusercontent.com/30708294/98692679-3df20c80-2324-11eb-9b81-3a8864d09793.png)

**Comment by Windchild292** [comment]
Caused by #2161, namely that Image::getWidth and Image::getHeight are returning -1 for an unknown reason.

```
10:48:55,864 ERROR [mekhq.gui.view.PersonViewPanel] {AWT-EventQueue-0} 
drawRibbons(), line 322 : Width (-1) and height (-1) cannot be <= 0
java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:186)
	at megamek.common.util.ImageUtil.createAcceleratedImage(ImageUtil.java:77)
	at megamek.common.util.ImageUtil$AWTImageLoader.loadImage(ImageUtil.java:218)
	at megamek.common.util.ImageUtil.loadImageFromFile(ImageUtil.java:176)
	at megamek.common.util.fileUtils.ImageFileFactory$1.getItem(ImageFileFactory.java:75)
	at megamek.common.util.fileUtils.AbstractDirectory.getItem(AbstractDirectory.java:154)
	at megamek.common.util.fileUtils.AbstractDirectory.getItem(AbstractDirectory.java:147)
	at megamek.common.util.fileUtils.AbstractDirectory.getItem(AbstractDirectory.java:147)
	at mekhq.gui.view.PersonViewPanel.drawRibbons(PersonViewPanel.java:314)
	at mekhq.gui.view.PersonViewPanel.initComponents(PersonViewPanel.java:162)
	at mekhq.gui.view.PersonViewPanel.<init>(PersonViewPanel.java:92)
	at mekhq.gui.PersonnelTab.refreshPersonnelView(PersonnelTab.java:822)
	at mekhq.gui.PersonnelTab.lambda$initTab$3(PersonnelTab.java:222)
```

**Comment by Windchild292** [comment]
There is a chance this is because the files in question are erroneous, however I believe it to be because they are using currently unsupported png formats. I've got a temporary fix that will hold for now, but will need to be revisited once we upgrade to Java 11. This has been noted in the file in question.

**Comment by BullseyeSmith** [comment]
@Windchild292, if I saved the award images in the wrong format, please let me know how to do it properly and I will convert them all.

**Comment by Windchild292** [comment]
It is pre-existing, this was just found because of a few underlying changes I made to standardize and simplify the backend for icons in general.
