### ISSUE TITLE
Monthly Date Rollover Error - No Unit Market or Contract Info

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#2248]
### Environment
What version of MekHQ does your issue apply to? 0.47.14
What operating system are you using?  Windows
What java version are you using?  Java version 1.8.0_271

### Description
Though working way outside the normal scope of MekHQ, I've snagged a bug where the date sticks at the end of the month (which I know is a repeat), the unit market is blank, and the contract market is blank. Also, there is no roll for procuring parts even though there should be.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5618710/mekhqlog.txt)
[BS_Brigade.cpnx.gz](https://github.com/MegaMek/mekhq/files/5618711/BS_Brigade.cpnx.gz)

[Ticket.zip](https://github.com/MegaMek/mekhq/files/5618713/Ticket.zip)

**Comment by sixlettervariables** [comment]
Two exceptions in the log:
```
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at mekhq.campaign.market.ContractMarket.generateContractOffers(ContractMarket.java:187)
	at mekhq.campaign.market.ContractMarket.generateContractOffers(ContractMarket.java:142)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:3094)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3397)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
...
```
and
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.market.ContractMarket.generateAtBContract(ContractMarket.java:315)
	at mekhq.campaign.market.ContractMarket.generateAtBContract(ContractMarket.java:288)
	at mekhq.campaign.market.ContractMarket.addAtBContract(ContractMarket.java:106)
	at mekhq.gui.dialog.ContractMarketDialog.lambda$initComponents$7(ContractMarketDialog.java:369)
...
	at mekhq.gui.CampaignGUI.showContractMarket(CampaignGUI.java:1266)
	at mekhq.gui.CampaignGUI.lambda$initMenu$5(CampaignGUI.java:715)
...
```

**Comment by sixlettervariables** [comment]
Curious, what year and planet? (Haven't loaded your CPNX yet)

**Comment by johnboyjjb** [comment]
Well, that is a thing. Rebels and Pirates show up up as factions, but in the factions XML there should also be the Western Alliance. I would also potentially the planetary government would work. Or corporations.

I did say it was "way outside the scope" of normal usage. And I only have another ~70 years before the first planet is colonized.

**Comment by sixlettervariables** [comment]
Perhaps an enhancement could be introduced which uses the Planetary Govt if no faction exists.

**Comment by johnboyjjb** [comment]
I was thinking about that. Though I thought the unit market also had a segment populated by the employer which would force the Planetary Government to either have some alignment or default to generic.

I will say, starting my campaign in 2000 has really shown me some interesting things about MekHQ. Still amazed it works as well as it does for something it really isn't designed to support.
