### ISSUE TITLE
Saves made by MekHQ 0.47.14 are not possible to load with the same MekHQ 0.47.14

### ISSUE THREAD

**Issue by ADREK4005** [MegaMek/mekhq#2255]
### Environment
MekHQ 0.47.14
Windows 10
java build 1.8.0_271-b09

### Description
Games saved in MekHQ 0.47.14 (I was reorganizing my regiment last) is not loading with MekHQ 0.47.14. No error messages. It just stops loading while loading campaign part. Nothing else happens. Those saves are also not possible to load ingame (after starting a new game for a example). Just nothing happens as well.

### Files
I don't have in my regiment any units mentioned in Mekhq logfile.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5637767/mekhqlog.txt)
[Wargirls30640303.cpnx.gz](https://github.com/MegaMek/mekhq/files/5637772/Wargirls30640303.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5637797/megameklog.txt)

**Comment by sixlettervariables** [comment]
From mekhqlog.txt:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:308)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by sixlettervariables** [comment]
I'm unable to debug the CPNX without the following units:
```
15:40:40,544 ERROR [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
checkUnits(), line 1257 : Could not load the following units: 
Berserker BRZ-A34J
Riever F-700a5 (Mixed)
Cudgel CDG-1B (Mixed)
Devastator DVS-2 (Mixed)
Sprint Scout Helicopter (ECM)
Corsair COR-5R(W)
Xerxes (W)
Masakari (Warhawk) W
Tyrant (3056)(W)
Harpy (W)4
```

**Comment by ADREK4005** [comment]
Ah, I didn't think refit files were necessary. Here they are:
[Refit files.zip](https://github.com/MegaMek/mekhq/files/5638873/Refit.files.zip)

**Comment by sixlettervariables** [comment]
That save, somehow, has a recursive parts tree!
```
java.lang.StackOverflowError
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:350)
	at java.base/java.util.TreeMap.remove(TreeMap.java:601)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:141)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
	at mekhq.campaign.Warehouse.removePart(Warehouse.java:152)
```

**Comment by sixlettervariables** [comment]
Try this CPNX:
[Wargirls30640303-fixed.cpnx.gz](https://github.com/MegaMek/mekhq/files/5640288/Wargirls30640303-fixed.cpnx.gz)
It may work in 0.47.14.

**Comment by ADREK4005** [comment]
It works. Thank you! Well, my dropships became "moderately damaged" but in reality they are undamaged and don't appear in repair bay. I also managed to repeat the bug which broke my saves. How to explain it: all my units can be sold except for Fenrir [MPL] and Elemental [HMG] MKII (they both are broken in MekHQ 0.47.14 somehow). So I was not able to sell or GM remove Fenrir [MPL] and found a way around: I GM stripped them and sold for 0 c-bills (it worked). But after such procedure all future save files become broken and don't load. I don't know what files you need to deal with this bug so adding Fenrir screenshot and new broken save file and log.
![Fenrir](https://user-images.githubusercontent.com/75442368/101159281-37626680-363e-11eb-8d90-6b7c43bf5139.jpg)
[Wargirls30640306.cpnx.gz](https://github.com/MegaMek/mekhq/files/5642452/Wargirls30640306.cpnx.gz)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5642456/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
That helps! I'll look into that more.

The dropship issue is a known issue with bay doors I believe.

**Comment by sixlettervariables** [comment]
The parts tree for those suits has some odd recursion (noted by double stars):
```
	702608: Fenrir Battle Armor [MPL] Suit
		702608: Fenrir Battle Armor [MPL] Suit
			702608: Fenrir Battle Armor [MPL] Suit**
			702609: Armor (BA Standard (Basic))
		702609: Armor (BA Standard (Basic))
	702609: Armor (BA Standard (Basic))
	702610: Fenrir Battle Armor [MPL] Suit
		702610: Fenrir Battle Armor [MPL] Suit
			702610: Fenrir Battle Armor [MPL] Suit**
			702611: Armor (BA Standard (Basic))
		702611: Armor (BA Standard (Basic))
	702611: Armor (BA Standard (Basic))
	702612: Fenrir Battle Armor [MPL] Suit
		702612: Fenrir Battle Armor [MPL] Suit
			702612: Fenrir Battle Armor [MPL] Suit**
			702613: Armor (BA Standard (Basic))
		702613: Armor (BA Standard (Basic))
	702613: Armor (BA Standard (Basic))
	702614: Fenrir Battle Armor [MPL] Suit
		702614: Fenrir Battle Armor [MPL] Suit
			702614: Fenrir Battle Armor [MPL] Suit**
			702615: Armor (BA Standard (Basic))
		702615: Armor (BA Standard (Basic))
	702615: Armor (BA Standard (Basic))
	702616: Medium Pulse Laser
	702617: Medium Pulse Laser
	702618: Medium Pulse Laser
	702619: Medium Pulse Laser
```

**Comment by sixlettervariables** [comment]
The next release will have a fix for this, but I'm still researching how your campaign came to have these recursive part trees.
