### ISSUE TITLE
Exception opening Personnel Table context menu

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#2295]
Described on Slack.

### Environment
What version of MekHQ does your issue apply to? 0.47.15
What operating system are you using?  Windows
What java version are you using? 11

### Description
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.maybeShowPopup(PersonnelTableMouseAdapter.java:1212)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.mouseReleased(PersonnelTableMouseAdapter.java:1117)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
```

**Comment by sixlettervariables** [comment]
Offending lines:
https://github.com/MegaMek/mekhq/blob/e9ff1140fde5cc9ba6a9b3771c538ae69391708d/MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java#L1208-L1220
