### ISSUE TITLE
47.15 Generic "Armor" listed in Parts in Use Report, despite not being used/available?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2298]
### Environment
47.15
Windows 10
Java 11.0.8

### Description
Unexpected generic "Armor" is showing up in the Parts in Use Report, despite listed 0 as actually in use, and not being an item type I recognize. Cost is listed as -5 C-bills per unit (which doesn't seem right), and attempting to acquire it gives a notification that "You cannot acquire parts of this tech level". 
![image](https://user-images.githubusercontent.com/59574316/102699455-de382c80-4212-11eb-9874-43161fc97016.png)

### Files
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5720136/Coppercoats.cpnx.gz)
No custom units. 

Encountered an error in mekhqlog.txt specifically while using GM mode powers to clear the impossible procurement order from the procurement list (right click order - GM Mode - "Clear from list") - unrelated to the primary issue. 
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5720140/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
Procurement error:
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at mekhq.gui.model.ProcurementTableModel.getAcquisition(ProcurementTableModel.java:148)
	at mekhq.gui.model.ProcurementTableModel.getValueAt(ProcurementTableModel.java:88)
..

```

**Comment by sixlettervariables** [comment]
The generic armor belongs to your "Xenoplanetary Infantry Eagle Corps Eyrie Defense Force". They have an unknown armor type, and it likely shouldn't be included, but I'm not exactly sure how (e.g. filter vs remove the part).

**Comment by gsparks3** [comment]
I see! That explains why it's gone from the list now in that campaign, along with the more recognizable Armor Kits - I sold my infantry units, so of course those parts are no longer present.
