### ISSUE TITLE
NPE in AeroSensor::getBaseTime

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#2306]
I have run into this issue today also.  Everything worked yesterday, now it goes through the load screen, but nothing opens up.  Have tried both 0.46.1 and an old copy of 0.46.0, as well as both the most recent campaign save and an older version.  Also reinstalled Java.  The log and campaign file (saved as a txt rather than CPNX file) are attached.  Running windows 10

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.parts.AeroSensor.getBaseTime(AeroSensor.java:92)
	at mekhq.campaign.parts.Part.getActualTime(Part.java:804)
	at mekhq.campaign.parts.Part.getTimeLeft(Part.java:810)
	at mekhq.campaign.parts.Part.getRepairDesc(Part.java:469)
	at mekhq.gui.model.PartsTableModel.getValueAt(PartsTableModel.java:107)
```

[Rupard's Roughriders 3034-01.txt](https://github.com/MegaMek/mekhq/files/4125623/Rupard.s.Roughriders.3034-01.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4125627/mekhqlog.txt)

Okay, if I go back 5 saves (~6mo game time), I can open that cpnx file.  Attached
[Rupard's Roughriders 3033-07.txt](https://github.com/MegaMek/mekhq/files/4125643/Rupard.s.Roughriders.3033-07.txt)

_Originally posted by @cjfarls in https://github.com/MegaMek/mekhq/issues/1432#issuecomment-579543173_

**Comment by sixlettervariables** [comment]
Fixed in https://github.com/MegaMek/mekhq/pull/1210
