### ISSUE TITLE
GM Restore on BA missing a suit may raise NPE

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#2347]
### Environment
What version of MekHQ does your issue apply to? 0.47.15+
What operating system are you using?  Windows, Mac, and Linux
What java version are you using?  Java 11

### Description
Added Kage (DEST), salvaged a suit (trooper 4), attempted GM Restore. Sometimes you need to do this twice to get the exception to occur, not entirely sure of the exact conditions:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.parts.equipment.MissingBattleArmorEquipmentPart.fix(MissingBattleArmorEquipmentPart.java:162)
	at mekhq.campaign.unit.actions.RestoreUnitAction.execute(RestoreUnitAction.java:55)
	at mekhq.gui.adapter.UnitTableMouseAdapter.actionPerformed(UnitTableMouseAdapter.java:481)
```

**Comment by sixlettervariables** [comment]
Line number for 0.47.15/16 is 155:
https://github.com/MegaMek/mekhq/blob/3c8a806728eacb28993fed297fcf1a71abd636cf/MekHQ/src/mekhq/campaign/parts/equipment/MissingBattleArmorEquipmentPart.java#L150-L164

Logging the parts for the unit after restoring (note the IDs of zero):
```
12:54:46,318 INFO [mekhq.gui.adapter.UnitTableMouseAdapter$1] {AWT-EventQueue-0} 
actionPerformed(), line 1035 : Kage Light Battle Armor (DEST) (e9737aba-9f73-4b7d-b8fd-5b281f6c9767)
	5: Kage Light Battle Armor (DEST) Suit
		1: Armor (BA Stealth (Basic))
		2: BA Manipulators [Armored Gloves]
		3: BA Manipulators [Armored Gloves]
		4: Auto-Rifle (Modern, Generic)
	6: Armor (BA Stealth (Basic))
	11: Kage Light Battle Armor (DEST) Suit
		7: Armor (BA Stealth (Basic))
		8: BA Manipulators [Armored Gloves]
		9: BA Manipulators [Armored Gloves]
		10: Auto-Rifle (Modern, Generic)
	12: Armor (BA Stealth (Basic))
	17: Kage Light Battle Armor (DEST) Suit
		13: Armor (BA Stealth (Basic))
		14: BA Manipulators [Armored Gloves]
		15: BA Manipulators [Armored Gloves]
		16: Auto-Rifle (Modern, Generic)
	18: Armor (BA Stealth (Basic))
	24: Armor (BA Stealth (Basic))
	25: Small Laser
	26: BA Manipulators [Armored Gloves]
	27: BA Manipulators [Armored Gloves]
	28: BA Manipulators [Armored Gloves]
	30: BA Manipulators [Armored Gloves]
	31: BA Manipulators [Armored Gloves]
	32: BA Manipulators [Armored Gloves]
	34: Auto-Rifle (Modern, Generic)
	35: Auto-Rifle (Modern, Generic)
	36: Auto-Rifle (Modern, Generic)
	70: Kage Light Battle Armor (DEST) Suit
	0: BA Manipulators [Armored Gloves]
	0: BA Manipulators [Armored Gloves]
	0: Auto-Rifle (Modern, Generic)
```
