### ISSUE TITLE
Unable to load saved 47.16 campaign

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2396]
After saving a campaign in 47.16, I cannot load it, or most of the auto-saves.  The only thing I can point to, is

- a change to a conventional infantry platoon, which seems to show up in the log.
- an exception being thrown about battle armor

[Brilliant Light III-Gamma30741228.cpnx.gz](https://github.com/MegaMek/mekhq/files/5861613/Brilliant.Light.III-Gamma30741228.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5861614/megameklog.txt)
[BIIIG Customs.zip](https://github.com/MegaMek/mekhq/files/5861615/BIIIG.Customs.zip)
[BIIIG-BA.zip](https://github.com/MegaMek/mekhq/files/5861618/BIIIG-BA.zip)

**Comment by sixlettervariables** [comment]
```
22:15:48,973 ERROR [mekhq.gui.dialog.DataLoadingDialog$Task] {AWT-EventQueue-0} 
done(), line 264 : megamek.common.Infantry cannot be cast to megamek.common.BattleArmor
java.lang.ClassCastException: megamek.common.Infantry cannot be cast to megamek.common.BattleArmor
	at mekhq.campaign.unit.Unit.initializeParts(Unit.java:2330)
	at mekhq.campaign.io.CampaignXmlParser.lambda$parse$2(CampaignXmlParser.java:452)
	at mekhq.campaign.Hangar.lambda$forEachUnit$0(Hangar.java:116)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at mekhq.campaign.Hangar.forEachUnit(Hangar.java:116)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:449)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:195)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:130)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by sixlettervariables** [comment]
Short a few customs:
![image](https://user-images.githubusercontent.com/8238690/107126491-4b188c00-687e-11eb-86b2-5df9a94cb907.png)

**Comment by SuperStucco** [comment]
Should be in the 'Infantry Pack' from this post:
[https://github.com/MegaMek/mekhq/issues/2406#issuecomment-774519505](url)

**Comment by sixlettervariables** [comment]
Somehow your Infantry platoon's auto-rifle became a battle armor equipment part...how odd.

**Comment by SuperStucco** [comment]
Hmmm... wonder if that's related to something else I'm seeing.  The stat display for conventional infantry has two tabs, 'Summary' and 'TRO'.  While 'Summary' shows the correct primary and secondary weapons, the 'TRO' tab always shows them as the same even for the OOTB designs.

![Infantry display bug](https://user-images.githubusercontent.com/70451747/107126968-3c2add00-6870-11eb-9dda-f9b856c899a9.png)

This happens in all three of MegaMek, MekHQ, and MML.

**Comment by Windchild292** [comment]
That's a different bug, and I'll handle that one
