### ISSUE TITLE
NPE: campaign unloadable

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#2408]
just recently updated to 47.16 and java 11 from 47.6/47.11

Left mekHQ running for the last day,  Produced several saves during that time, as I continued play.  all the saves fail to load with an NPE.

[error.zip](https://github.com/MegaMek/mekhq/files/5929903/error.zip)

**Comment by HammerGS** [comment]
Two errors in the logs:

```
readPreferencesNode : No class with name mekhq.gui.dialog.CamoChoiceDialog found
java.lang.ClassNotFoundException: mekhq.gui.dialog.CamoChoiceDialog
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at mekhq.preferences.MekHqPreferences.readPreferencesNode(MekHqPreferences.java:164)
	at mekhq.preferences.MekHqPreferences.loadFromFile(MekHqPreferences.java:68)
	at mekhq.MekHQ.startup(MekHQ.java:254)
	at mekhq.MekHQ.lambda$main$0(MekHQ.java:333)
```
and

```
ava.lang.NullPointerException
	at mekhq.campaign.parts.TransportBayPart.getBay(TransportBayPart.java:67)
	at mekhq.campaign.parts.TransportBayPart.getName(TransportBayPart.java:74)
	at mekhq.campaign.parts.Part.fixReferences(Part.java:1830)
	at mekhq.campaign.io.CampaignXmlParser.postProcessParts(CampaignXmlParser.java:1288)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:367)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:195)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:130)
```

**Comment by Windchild292** [comment]
The first is an error that occurs when one copies forwards the MekHQ preferences file after a dialog has been removed. User-side fix is to not copy over the preferences between versions, as we don't guarantee that they will stay constant between them

**Comment by bczretribution** [comment]
if by mekHQ preferences you mean the options menu where i can select things like autosave frequency etc.  i don't believe i copied that file over (im assuming it was in mmconf, which i copied WITHOUT replacing) and one of the first things i did after launching mmHQ 47.16 was to open that menu and modify the selection to my preferences.  I can delete and replace that file though from the download zip to be sure its the proper version.

**Comment by Windchild292** [comment]
Those are MekHQ Options, not preferences, and automatically carry over between versions.

MekHQ preferences is a file in the mmconf that does not exist on downloads. Deleting it will clear that error (which can cause visual glitches, but it is almost certainly the bay issue for the campaign not being able to load).

What version did you update from?

**Comment by bczretribution** [comment]
error occurred between keyboard and chair.  thank you for saving me from myself :)

i thought 47.11 but it seems it was 47.6
