### ISSUE TITLE
(MekHQ 0.47.17) NullPointerException Error Found During a Mission

### ISSUE THREAD

**Issue by ACluelessFool** [MegaMek/mekhq#2425]
### Environment
```
MekHQ v0.47.17 RC3
Windows 10
Java 11
```

### Description
Was playing in a Probe mission on the Attacker side, deployed two mech lances (I unfortunately forgot to take screenshots when I ran into the issue). On Round 3 after I collapsed a building a turret was on, Princess immediately entered a state of no action when the physical attack phase came up (I had simul. phys attacks on). Parsed both megameklog and mekhqlog and came across a NPE error in the mekhqlog.

### Files
[mekhqlog_ApocAngelsVSLyranCommon_no1.txt](https://github.com/MegaMek/mekhq/files/5992731/mekhqlog_ApocAngelsVSLyranCommon_no1.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5992734/megameklog.txt)
[Bug Report Package.zip](https://github.com/MegaMek/mekhq/files/5992749/Bug.Report.Package.zip)

.zip file has the .cpnx file and the customized mechs at the time.

**Comment by sixlettervariables** [comment]
Error from the log:
```
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.Mounted.getName(Mounted.java:423)
	at megamek.common.Mounted.getExplosionDamage(Mounted.java:1265)
	at megamek.common.LandAirMech.hasInfernoAmmo(LandAirMech.java:1088)
	at megamek.server.Server.resolveHeat(Server.java:19499)
	at megamek.server.Server.prepareForPhase(Server.java:2391)
	at megamek.server.Server.changePhase(Server.java:2227)
	at megamek.server.Server.endCurrentPhase(Server.java:2910)
	at megamek.server.Server.changeToNextTurn(Server.java:3202)
	at megamek.server.Server.endCurrentTurn(Server.java:2212)
	at megamek.server.Server.receiveAttack(Server.java:13428)
	at megamek.server.Server.handle(Server.java:31380)
	at megamek.server.Server$PacketPump.run(Server.java:254)
```
