### ISSUE TITLE
NPE during Personnel export

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#2431]
### Environment
 	MekHQ 0.47.17
	Java vendor openjdk
	Java version 16
	Platform Mac OS X 11.2.1 (aarch64)

### Description
While attempting to export my personnel to a CSV, an error occurred and logged the following error:
```
exportTableToCSV(), line 1459 : Error exporting JTable
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "javax.swing.table.TableModel.getValueAt(int, int)" is null
```
Only 33 of my 63 personnel ended up getting exported to the CSV.

NOTE: There is an exception prior to the NPE where I accidentally attempted to write the file to a directory that I didn't have permission to. After changing the save location to a directory I **did** have permissions to, I received the NPE.

### Files
[custom_mechs.tar.gz](https://github.com/MegaMek/mekhq/files/6016247/custom_mechs.tar.gz)
Campaign: [Knights of the Periphery30100508.cpnx.gz](https://github.com/MegaMek/mekhq/files/6016250/Knights.of.the.Periphery30100508.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6016252/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6016253/mekhqlog.txt)

Partial export: [30100508_ExportedPersonnel.txt](https://github.com/MegaMek/mekhq/files/6016258/30100508_ExportedPersonnel.txt)

**Comment by sixlettervariables** [comment]
Unrelated NPE in log:
```

10:02:02,434 ERROR [megamek.client.bot.BotClient] {Free Worlds League Turn 5 Calc Thread} 
calculateMyTurnWorker(), line 591 : null
java.util.ConcurrentModificationException
	at java.base/java.util.Vector$Itr.checkForComodification(Vector.java:1292)
	at java.base/java.util.Vector$Itr.next(Vector.java:1248)
	at megamek.common.EquipmentType.hasModeType(EquipmentType.java:549)
	at megamek.client.bot.princess.FireControl.entityCanIndirectFireMissile(FireControl.java:2280)
	at megamek.client.bot.princess.Princess.initFiringEntities(Princess.java:982)
	at megamek.client.bot.princess.Princess.getEntityToFire(Princess.java:954)
	at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:628)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:559)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:516)
	at megamek.client.bot.BotClient.access$000(BotClient.java:85)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:109)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by sixlettervariables** [comment]
Proximate cause:
```
exportTableToCSV(), line 1459 : Error exporting JTable
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "javax.swing.table.TableModel.getValueAt(int, int)" is null
	at mekhq.Utilities.exportTableToCSV(Utilities.java:1449)
	at mekhq.gui.CampaignGUI.lambda$exportPersonnel$33(CampaignGUI.java:1805)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at mekhq.gui.CampaignGUI.exportPersonnel(CampaignGUI.java:1798)
	at mekhq.gui.CampaignGUI.miExportPersonnelCSVActionPerformed(CampaignGUI.java:1523)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
...
```

**Comment by Windchild292** [comment]
I can take a look at this in 4 hours.
