### ISSUE TITLE
Salvaging Dropship causes repair bay and campaign issues

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#2435]
### Environment
 	MekHQ 0.47.17
	Compiled on 2021-02-07T21:28:42Z
	Today is 2021-02-20
	Java vendor N/A
	Java version 16
	Platform Mac OS X 11.2.1 (aarch64)

### Description
I added a Dropship Assault scenario and, on the salvage screen in MekHQ, I edited the damage on the dropship so it was Crippled instead of Salvage, and claimed it.

At that point, things got odd in my campaign:
<img width="1671" alt="Screen Shot 2021-02-20 at 8 33 07 PM" src="https://user-images.githubusercontent.com/5141448/108612934-da638a80-73ba-11eb-8315-33085c7f09f5.png">
1. The Repair Bay for the dropship got screwy with a ghost tech instead of the real tech.
2. The Ghost Tech is the only tech that can affect repairs on the dropship, even if there are other valid techs available.
3. The bay doors that are listed as system damage were able to be repaired... but on subsequent loads, re-appeared as damage.

Additionally, I added the dropship to my TO&E and then accepted a contract, but when I went to the contract, it started throwing errors trying to determine if a unit was a combat unit or not. However, I was not able to reproduce the errors on re-loading the campaign.

In the original occurance, I ended up GM adding another dropship and then removing the 'broken' dropship. When that didn't resolve the issues, I removed the dropship from its force, then removed the forces. Then finally restarted MekHQ.

### Files
Campaign save: [Knights of the Periphery30110325.cpnx.gz](https://github.com/MegaMek/mekhq/files/6016967/Knights.of.the.Periphery30110325.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6016977/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6016978/mekhqlog.txt)
[custom_mechs.tar.gz](https://github.com/MegaMek/mekhq/files/6016980/custom_mechs.tar.gz)
[mekhqlog_with_errors.txt](https://github.com/MegaMek/mekhq/files/6016981/mekhqlog_with_errors.txt)

**Comment by sixlettervariables** [comment]
Regarding that ghost tech: units with an engineering role create a "composite" tech. That may be what's going on, I'll see what I can figure out.

Exception from logs:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "mekhq.campaign.force.Force.isCombatForce()" because the return value of "mekhq.campaign.Campaign.getForce(int)" is null
	at mekhq.campaign.force.Lance.isEligible(Lance.java:230)
	at mekhq.campaign.mission.atb.AtBScenarioFactory.createScenariosForNewWeek(AtBScenarioFactory.java:210)
	at mekhq.campaign.Campaign.processNewDayATBScenarios(Campaign.java:3016)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:3181)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3404)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$32(CampaignGUI.java:1053)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by sixlettervariables** [comment]
I believe the exception is due to the case that the scenario's understanding of your forces became inconsistent with reality. You had a lance that was no longer attached to a valid force.

**Comment by UlyssesSockdrawer** [comment]
@IllianiCBT - do we think this one can be closed as no longer relevant, now that DS aren't eligible for salvage from the ground map? Or should it still be investigated for salvaging from space?

**Comment by IllianiCBT** [comment]
I think this still needs investigating

**Comment by UlyssesSockdrawer** [comment]
Thanks, added to the dropship bugcatcher.
