### ISSUE TITLE
End of year finances not being output

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2456]
### Environment
What version of MekHQ does your issue apply to? 0.48.0
What operating system are you using?  Windows 10
What java version are you using? AdoptOpenJDK 11.0.9.1

### Description
I've started a new campaign in 0.48.0, and for some reason, when I move into the year 3060, it isn't generating a financial report.  It did generate one at the end of 3059 (although it named it 3060 for some reason).  

I had this same issue in my 0.47.17 campaign.  I got a report at the end of 3059, but not at the end of 3060, and then I got another report at the end of 3061.

### Files
[Nightstalkers30601231.cpnx.gz](https://github.com/MegaMek/mekhq/files/6112780/Nightstalkers30601231.cpnx.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/6112783/customs.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6112787/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6112788/megameklog.txt)
The log files were saved after rolling over to Jan 1.

**Comment by BowtieBob** [comment]
As a test, I advanced through another year, and it created the finances report for 3061.  Here are the logs and campaign files for 3061.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6112827/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6112829/megameklog.txt)
[Nightstalkers30611231.cpnx.gz](https://github.com/MegaMek/mekhq/files/6112834/Nightstalkers30611231.cpnx.gz)

**Comment by Windchild292** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.market.UnitMarket.generateUnitOffers(UnitMarket.java:139)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:3109)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3425)
	at mekhq.gui.dialog.AdvanceDaysDialog.actionPerformed(AdvanceDaysDialog.java:161)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	```

**Comment by Windchild292** [comment]
NPE in the Unit Market, I'll fix it when I abstract it out.

**Comment by Windchild292** [comment]
This file has led to another NPE being found... and the financial year display is poorly done so I'll fix that
