### ISSUE TITLE
Award PNG Files Include Unsupported PNG Functionality

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#2508]
Currently our award png files include ones that use unsupported PNG functionality. #2507 reintroduced AwardFileFactory, a bandaid that allows us to ignore the unsupported functionality, but we should really just fix the award files.

This causes load failures (although it does not do so on my personal environment during dev testing, just on releases) throwing the following exception, which is written to System.err on another thread.
```
sun.awt.image.PNGImageDecoder$PNGException: Broken file
	at java.desktop/sun.awt.image.PNGImageDecoder.pngassert(PNGImageDecoder.java:94)
	at java.desktop/sun.awt.image.PNGImageDecoder.handleChunk(PNGImageDecoder.java:107)
	at java.desktop/sun.awt.image.PNGImageDecoder.getData(PNGImageDecoder.java:727)
	at java.desktop/sun.awt.image.PNGImageDecoder.produceImage(PNGImageDecoder.java:253)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
	at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)
```

**Comment by IllianiCBT** [comment]
I didn't see this behavior during the implementation of autoAwards, where I had to interact with award images a lot. I'm going to go ahead and close this, though we can re-open it should the error resurface.
