### ISSUE TITLE
Cannot Open Save After Fully Crewing Superheavy Tripod Mechs

### ISSUE THREAD

**Issue by AdamMcAuliffe** [MegaMek/mekhq#2610]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekHQ does your issue apply to?
     0.48.0
What operating system are you using?  Windows, Mac, or Linux?
     Windows
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
     AdoptOpenJDK 11.0.11
(Delete the above lines)

### Description
Describe the issue and provide screenshots ingame if able.
     After assigning full crew to a superheavy 'mech, the campaign will behave normally and track deployments and missions for all crew.  Once the campaign is saved, though, the save will no longer reopen.  Attempting to reload the campaign returns "Campaign Loading Error: the campaign file could not be loaded.  Please check the log file for details."  No error appears in the mekhqlog, but the megameklog has a NullPointerException error at the correct time-stamp for the attempt to load the campaign file.  Screenshot of error included in ZIP file.

Provide the rulebook, page number, and text if you feel like this is a rules issue.
     N/A

And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
     Error initially occurred in longer campaign.  Created new campaign to test if something internal to that campaign, or the superheavy with full crew.  Issue recurred in new campaign with one superheavy and three crew.  While third crew not assigned, campaign saves and loads normally.  Once third crew assigned, campaign would save normally but not load.  Included both saves & matching logs of test campaign in ZIP file.

[Not Loading Superheavy With Full Crew.zip](https://github.com/MegaMek/mekhq/files/6462376/Not.Loading.Superheavy.With.Full.Crew.zip)

(Delete the above lines)

### Files
Provide the .cpnx campaign file that this issue occurs in.
     XX Hastati31450102.cpnx
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
     N/A - occurs on standard Ares chassis.
Provide any other files that you have customized in this campaign like the factions.xml for example.
     N/A
And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
     Included in the attached ZIP file.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt and mekhqlog.txt files
     Included in the attached ZIP file.
(Delete the above lines)

**Comment by Windchild292** [comment]
```
java.lang.NullPointerException
	at mekhq.campaign.personnel.Person.hasSkill(Person.java:2815)
	at mekhq.campaign.unit.Unit.resetPilotAndEntity(Unit.java:3418)
	at mekhq.campaign.io.CampaignXmlParser.lambda$parse$0(CampaignXmlParser.java:401)
	at mekhq.campaign.Hangar.lambda$forEachUnit$0(Hangar.java:116)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at mekhq.campaign.Hangar.forEachUnit(Hangar.java:116)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:395)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:195)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:130)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
