### ISSUE TITLE
Error when modifying Lion dropship

### ISSUE THREAD

**Issue by mouldsgame** [MegaMek/mekhq#2687]
The below screen shot sums up the changes I made, but in brief I have a Lion (2595) dropship in which I'm trying to change the number of bays.   I removed the cargo bay, added 4 more mech bays bringing the total to 12 and added 12 clan Battlearmor bays.   I then used the "Use remaining tonnage..." button to put what was left back into cargo.  When I try to begin the refit I get the error in the screen shot.  

I have also attached my log files and campaign save.  It was a brand new unit so there's not a ton there yet.   
[13th Watch Commandos 30670101.cpnx.gz](https://github.com/MegaMek/mekhq/files/6620661/13th.Watch.Commandos.30670101.cpnx.gz)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6620657/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6620659/megameklog.txt)

![image](https://user-images.githubusercontent.com/49316494/121282344-5240bc80-c8a7-11eb-8148-f6d8e9eef093.png)

**Comment by sixlettervariables** [comment]
Errors from log:
```
22:13:57,886 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for Mech Bay #1 during refit calculations

22:13:57,886 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for Light Vehicle Bay #2 during refit calculations

22:13:57,886 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for 2nd Class Quarters Bay #0 during refit calculations

22:13:57,886 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for 2nd Class Quarters Bay #0 during refit calculations

22:13:57,886 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for 2nd Class Quarters Bay #0 during refit calculations

22:13:57,886 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for Battle Armor Bay #3 during refit calculations

22:13:57,886 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for Cargo Bay #4 during refit calculations

22:14:03,119 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
saveCustomization(), line 1605 : Could not read back refit entity Lion Watch
megamek.common.loaders.EntityLoadingException: Could not load Lion Watch from the mech cache
	at mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1597)
	at mekhq.campaign.parts.Refit.begin(Refit.java:1022)
	at mekhq.gui.CampaignGUI.refitUnit(CampaignGUI.java:1691)
	at mekhq.gui.MekLabTab.lambda$initTab$0(MekLabTab.java:108)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

22:14:03,119 WARN [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
saveCustomization(), line 1609 : Deleting invalid refit file data\mechfiles\customs\13th Watch Commandos \Lion Watch.blk
```

**Comment by sixlettervariables** [comment]
`TransportBayPart` instances do not have a missing part version, we _probably_ should just add them to the list on line 483 but I'm not 100% sure on this just yet:
https://github.com/MegaMek/mekhq/blob/fefbea4a47056ee7493e7f5f951fcf5b79c9c3df/MekHQ/src/mekhq/campaign/parts/Refit.java#L480-L485
