### ISSUE TITLE
49.2 Locks up when cancelling out of the 

### ISSUE THREAD

**Issue by mouldsgame** [MegaMek/mekhq#2717]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
0.49.2
Windows
13.0.2
(Delete the above lines)

### Description
I was attempting to advance days after I accepted a contract.   When I did I recieved the warning that I didn't have enough Astechs.  I cancelled out of the advance days dialogue and once I did anywhere I clicked on the MekHQ screen only beeped and didn't register my click.   If I didn't know better I would think there was a dialogue box open behind the window.  (please let me know if that doesn't make sense)

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6702336/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6702342/mekhqlog.txt)
[Wraith Division30670101.cpnx.gz](https://github.com/MegaMek/mekhq/files/6702344/Wraith.Division30670101.cpnx.gz)

[Wraith Division CUstomers.zip](https://github.com/MegaMek/mekhq/files/6702354/Wraith.Division.CUstomers.zip)

**Comment by HammerGS** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.adapter.UnitTableMouseAdapter.actionPerformed(UnitTableMouseAdapter.java:390)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
```

and 

```
Exception in thread "AWT-EventQueue-0" java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:260)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
```

**Comment by Windchild292** [comment]
Both of the above are not related.

**Comment by sixlettervariables** [comment]
These repro steps work for any nag dialog:
1. Advance multiple days until you get a Nag dialog
2. Close the Nag dialog
3. Close the Advance Multiple Days dialog

**Comment by Windchild292** [comment]
Got a fix for the bug in testing, will fix the main issue after.
