### ISSUE TITLE
[BUG] StratOps fails to generate scenarios - Exception in thread "AWT-EventQueue-0"

### ISSUE THREAD

**Issue by Jamini** [MegaMek/mekhq#2747]
### Environment
MekHQ-0.49.2
Ubuntu 20.04 (KDE Plasma 5.18.5)
Java version 11.0.11
Platform Linux 5.8.0-59-generic (amd64)

### Description
StratOps fails to generate scenarios
Logs attached.

### Files
Save
[Dumbcampaign.gz.cpnx.zip](https://github.com/MegaMek/megamek/files/6826193/Dumbcampaign.gz.cpnx.zip)

Logs here
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/6826191/mekhqlog.txt)

**Comment by NickAragua** [comment]
Check your data\scenariotemplates folder. Does it have files called Allied Facility.xml and Hostile Facility.xml?

**Comment by sixlettervariables** [comment]
Three distinct MekHQ NPEs:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.stratcon.StratconScenarioFactory.getSpecificScenario(StratconScenarioFactory.java:124)
	at mekhq.campaign.stratcon.StratconContractInitializer.initializeObjectiveScenarios(StratconContractInitializer.java:294)
	at mekhq.campaign.stratcon.StratconContractInitializer.initializeCampaignState(StratconContractInitializer.java:101)
	at mekhq.campaign.mission.AtBContract.acceptContract(AtBContract.java:1196)
	at mekhq.gui.dialog.ContractMarketDialog.acceptContract(ContractMarketDialog.java:450)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
...
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at mekhq.gui.CampaignGUI.showContractMarket(CampaignGUI.java:1314)
	at mekhq.gui.CampaignGUI.lambda$initMenu$15(CampaignGUI.java:851)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
...
```
And:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.stratcon.StratconScenarioFactory.getSpecificScenario(StratconScenarioFactory.java:124)
	at mekhq.campaign.stratcon.StratconScenarioFactory.getFacilityScenario(StratconScenarioFactory.java:164)
	at mekhq.campaign.stratcon.StratconRulesManager.setupScenario(StratconRulesManager.java:263)
	at mekhq.campaign.stratcon.StratconRulesManager.deployForceToCoords(StratconRulesManager.java:245)
	at mekhq.gui.stratcon.TrackForceAssignmentUI.actionPerformed(TrackForceAssignmentUI.java:128)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
...
```
And:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.initializeScenarioFromTemplate(AtBDynamicScenarioFactory.java:126)
	at mekhq.campaign.stratcon.StratconRulesManager.generateScenario(StratconRulesManager.java:638)
	at mekhq.campaign.stratcon.StratconRulesManager.generateScenario(StratconRulesManager.java:627)
	at mekhq.campaign.stratcon.StratconRulesManager.setupScenario(StratconRulesManager.java:267)
	at mekhq.campaign.stratcon.StratconRulesManager.deployForceToCoords(StratconRulesManager.java:245)
	at mekhq.gui.stratcon.TrackForceAssignmentUI.actionPerformed(TrackForceAssignmentUI.java:128)
...
```

**Comment by sixlettervariables** [comment]
Offending lines (NPEs 1 and 2):
https://github.com/MegaMek/mekhq/blob/d9d70ed28de6deeea5abfec98e5bff0e9cdf70e2/MekHQ/src/mekhq/campaign/stratcon/StratconScenarioFactory.java#L120-L125

Offending lines (NPE 3):
https://github.com/MegaMek/mekhq/blob/e0fb679ce5945bfce922cdcfe22a240d88495579/MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java#L123-L131

**Comment by NickAragua** [comment]
Right, they're all trying to explicitly get "Hostile Facility.xml". The only way to encounter this exception is if the file is not present or there's some kind of file system weirdness. I don't have a Linux box around for testing so I can't confirm one way or the other, but my guess is that it's a combination of how MekHQ was extracted and case sensitivity. I could probably put some more detailed logging in there ("what specific scenario are we trying to get") but that wouldn't tell me anything about the way it's set up in the local install.

**Comment by NickAragua** [comment]
For those who are experiencing the issue, the workaround is to rename your data/scenariotemplates directory to data/ScenarioTemplates (case sensitive)
