### ISSUE TITLE
[0.47.1 -> 0.48.0 or 0.49.2] Import of MekHQ Campaign file fails

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#2807]
I am currently using a campagin file in version 0.47.1. I would like to upgrade but the campagin file does not load in version 0.48.0 or 0.49.2 of MekHQ. A dialogue appears that the issue is logged. However I cannot easily find out what I could fix. 

### Environment
Import from version 0.47.1 -> 0.48.0 or 0.49.2]
OS: Windows
JRE: 8 (Update 301)
Java version 15

### Files
Logs
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6986634/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6986635/mekhqlog.txt)
Campaign File
[Hunting Hellhounds30541122withoutLTtrailer.zip](https://github.com/MegaMek/mekhq/files/6986636/Hunting.Hellhounds30541122withoutLTtrailer.zip)
Custom Units
[customs.zip](https://github.com/MegaMek/mekhq/files/6986638/customs.zip)

**Comment by Windchild292** [comment]
```
16:36:18,177 ERROR [mekhq.gui.dialog.DataLoadingDialog$Task] {AWT-EventQueue-0} 
done(), line 265 : Cannot invoke "megamek.common.EquipmentType.equals(Object)" because the return value of "mekhq.campaign.parts.equipment.EquipmentPart.getType()" is null
java.lang.NullPointerException: Cannot invoke "megamek.common.EquipmentType.equals(Object)" because the return value of "mekhq.campaign.parts.equipment.EquipmentPart.getType()" is null
	at mekhq.campaign.io.CampaignXmlParser.postProcessParts(CampaignXmlParser.java:1399)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:384)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:196)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:130)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by mwberlindeu** [comment]
Additional information: Java Version is taken from the log
CMD shows different version.

![grafik](https://user-images.githubusercontent.com/28268113/129450396-40d6a157-54f5-441e-824a-1a194d859387.png)

**Comment by Windchild292** [comment]
I've got a probable fix ready to go, but I don't know the region of the code too well and would thus recommend waiting until another dev can take a look at the fix.

As for Java, I'd reinstall following this guide: https://github.com/MegaMek/megamek/wiki/Updating-to-OpenJDK
You've got two versions installed, which can cause issues.
