### ISSUE TITLE
MekHQ will not load

### ISSUE THREAD

**Issue by Haranin** [MegaMek/mekhq#29]
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/168225/mekhqlog.txt)

MekHQ worked this morning, will not load now. I have updated java and up to win10 but still not working...

**Comment by Haranin** [comment]
3.21 development

**Comment by HammerGS** [comment]
Have you tried the campaign in a newer version? 0.3.21 is about 4 months old.

If you attached your cpnx file and any customs it will help trouble shoot the issues.


**NPE from the File**
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.force.Lance.getSize(Lance.java:177)
	at mekhq.campaign.force.Lance.isEligible(Lance.java:268)
	at mekhq.gui.view.LanceAssignmentView$4.include(LanceAssignmentView.java:189)
	at javax.swing.DefaultRowSorter.include(Unknown Source)
	at javax.swing.DefaultRowSorter.initializeFilteredMapping(Unknown Source)
	at javax.swing.DefaultRowSorter.sort(Unknown Source)
	at javax.swing.DefaultRowSorter.allRowsChanged(Unknown Source)
	at javax.swing.JTable.notifySorter(Unknown Source)
	at javax.swing.JTable.sortedTableChanged(Unknown Source)
	at javax.swing.JTable.tableChanged(Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableDataChanged(Unknown Source)
	at mekhq.gui.model.DataTableModel.setData(DataTableModel.java:45)
	at mekhq.gui.view.LanceAssignmentView.refresh(LanceAssignmentView.java:253)
	at mekhq.gui.view.LanceAssignmentView.initComponents(LanceAssignmentView.java:229)
	at mekhq.gui.view.LanceAssignmentView.<init>(LanceAssignmentView.java:93)
	at mekhq.gui.CampaignGUI.initBriefingTab(CampaignGUI.java:1075)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:672)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:553)
	at mekhq.MekHQ.showNewView(MekHQ.java:166)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:278)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
```

**Comment by Dylan-M** [comment]
And I do believe that bug is fixed since then.

**Comment by Haranin** [comment]
I've downloaded 3.25 and that will not start, nor generate a log file

the campaign file will not upload on this site, but as I can't even get to the menu screen (new, load, etc) I do not think it is the campaign file...

**Comment by Haranin** [comment]
[503rd Kampfgruppen30280612.zip](https://github.com/MegaMek/mekhq/files/168293/503rd.Kampfgruppen30280612.zip)

**Comment by Haranin** [comment]
There it is as a zip

**Comment by Haranin** [comment]
Stable 2.0 will load.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/168295/mekhqlog.txt)

very strange

**Comment by pheonixstorm** [comment]
Your zip does not contain the Chameleon (custom unit).

Also, the NPE is present in the recent release as well (0.3.25). Even found the cause of it.

Somehow your ASF is listed as being in force 5 which doesn't exist. When AtB checks the unit sizes it looks for this id and finds nothing. Don't know what you did but your aero lance (force id 5) was removed but for one fighter the scenario id stayed around while the other didn't. The lance section also contained an entry for force id 5. That solves one issue, question now is why won't 0.3.25 load.
[test.zip](https://github.com/MegaMek/mekhq/files/168614/test.zip)

Try loading the above zip and let me know if you still can't get it to work. I had to remove the Chameleon to get it to load. If it works I will provide a better fixed file for you.

**Comment by neoancient** [comment]
Added checks for non-existent force to prevent the specific problem and remove the lance on the next save, but I can't figure out how this happened in the first place. It appears that a unit was removed from the TO&E while deployed, which I don't think is supposed to be possible.

**Comment by Dylan-M** [comment]
More likely the unit itself was deleted while in the TO&E and deployed. That is possible, and will cause this behavior.

**Comment by neoancient** [comment]
It's showing up in the hangar.

**Comment by Dylan-M** [comment]
Oh well, it was worth a guess. You're right though, it should not be possible to do that without hand editing the campaign file.

**Comment by pheonixstorm** [comment]
If its fixed don't forget to close the bug report

**Comment by neoancient** [comment]
I left it open because there appears to be an inderlying issue, which may be related to #72. I need to look deeper.

**Comment by pheonixstorm** [comment]
@neoancient anything new on this?

**Comment by zupkuck** [comment]
Also getting this issue. I unzipped MekHQ and started a new AtB campaign, but am now unable to get MekHQ to start w/ the .exe file.

**Comment by Dylan-M** [comment]
@zupkuck That doesn't mean it is the same issue. Please start a new issue and follow our guidelines of zipping and attaching your cpnx, logs, custom units, and anything else relevant. As it stands, your issue is far too vague to know what it is.

**Comment by neoancient** [comment]
Closing as outdated.
