### ISSUE TITLE
Rifleman RFL-3N in hangar bugs out the refit kit window, doesn't appear at all. Removing the unit causes the Purchase Unit window to break.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#3009]
### Environment
0.49.5
Windows, Mac, or Linux? Windows 10
Java JDK 11.0.11.9-hots

### Description
There is a recently reactivated Rifleman RFL-3N (it had this issue before the mothball but I didn't recognize the second issue which I will explain.) which, when I attempt to use a refit kit on it it gives no refit kit window, it simply doesn't appear. The refit window works for other mechs, and this issue appeared on this rifleman before mothballing. I am able to use refit kits on my other rifleman, and the customize in mechlab seems to work. The SECOND issue related to this and I believe caused by whatever anomaly is going on with the RFL-3N here, is that if I remove it with GM mode, then try to go to Purchase Unit, the interface is useless - it becomes extremely laggy and won't pull up any results. I have tried restoring the unit with GM mode as well, same issue occurs.

To simplify this explanation -> Rifleman RFL-3N in hangar bugs out the refit kit window, doesn't appear at all. Removing the unit causes the Purchase Unit window to break.

### Files
![image](https://user-images.githubusercontent.com/59293682/146659728-000420b9-5a6a-4120-a896-9db3dd286ac1.png)
[Helena's Valkyries30271105.cpnx.gz](https://github.com/MegaMek/mekhq/files/7740182/Helena.s.Valkyries30271105.cpnx.gz)
[Helena's Valkyries.zip](https://github.com/MegaMek/mekhq/files/7740183/Helena.s.Valkyries.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7740184/mekhqlog.txt)

**Comment by Windchild292** [comment]
Needs the MegaMekLog.txt, but probably related to this:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.common.MechFileParser.<init>(MechFileParser.java:110)
	at mekhq.gui.dialog.ChooseRefitDialog.populateRefits(ChooseRefitDialog.java:274)
	at mekhq.gui.dialog.ChooseRefitDialog.<init>(ChooseRefitDialog.java:86)
	at mekhq.gui.adapter.UnitTableMouseAdapter.actionPerformed(UnitTableMouseAdapter.java:336)
```

**Comment by OrbMonky** [comment]
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7740190/megameklog.txt)

**Comment by OrbMonky** [comment]
If I remove this specific rifleman and save and reload the suite, the issue with the Purchase Unit market remains. Logs from this;
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7740196/megameklog.txt)

**Comment by IllianiBird** [comment]
Given the age of this issue I'm going to go ahead and close it
