### ISSUE TITLE
[49.7] Error starting game from MekHQ

### ISSUE THREAD

**Issue by Psykoraptor** [MegaMek/mekhq#3145]
### Environment
49.7
Windows
Java 11.0.12

### Description
When starting a scenario (not STRATCON) from MekHQ, and MegaMek loads up to put the units in, a popup happens. Attached screenshot.

### Files
![Unhandled](https://user-images.githubusercontent.com/7112739/155860066-357783b3-1caa-4557-9d25-0b29241ca5c1.png)
[Terran Dragoons30000321.cpnx.gz](https://github.com/MegaMek/mekhq/files/8147568/Terran.Dragoons30000321.cpnx.gz)
[megamek.log](https://github.com/MegaMek/mekhq/files/8147569/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8147570/mekhq.log)

**Comment by repligator** [comment]
Looks like this may actually be a MegaMek issue, see the following from the logs.

```
13:25:49,207 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at megamek.common.util.BoardUtilities.generateElevation(BoardUtilities.java:1140)
	at megamek.common.util.BoardUtilities.generateRandom(BoardUtilities.java:121)
```

**Comment by rjhancock** [comment]
ATB has been deprecated and removed.
