### ISSUE TITLE
[49.7 Dev Release] MekHQ-Generated Princess's Hanging in Firing Phase

### ISSUE THREAD

**Issue by StowGnar** [MegaMek/mekhq#3200]
### Environment
What version of MekHQ does your issue apply to? 49.7 Dev Release
What operating system are you using?  Windows 10
What java version are you using?  Temurin 11.0.13

### Description

Almost exclusively during the Firing Phase in my current scenario, Princess bots generated by MekHQ are hanging when it comes to be their turn to fire. I've attached a zip file containing logs, a savegame of it being the bot's turn to fire, as well as a campaign file (no customs) with steps to reproduce the issue below. Minimal experimentation with the /replacePlayer command causes the bot to behave for another turn or two, before also hanging.

To reproduce:
1. Load campaign file.
2. Begin pending scenario.
3. Start game.
4. Play for 2-5 rounds until one of the Princess bots has their turn to fire but does nothing.

### Files
[Princess Hangs.zip](https://github.com/MegaMek/mekhq/files/8412105/Princess.Hangs.zip)

**Comment by HammerGS** [comment]
From log and moving to MegaMek tracker. 

```
22:23:17,138 ERROR [megamek.common.Report] {Packet Pump}
megamek.common.Report.addNewline(Report.java:550) - Cannot add a new line
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at java.base/java.util.Vector.elementData(Vector.java:762)
	at java.base/java.util.Vector.elementAt(Vector.java:500)
	at megamek.common.Report.addNewline(Report.java:548)
	at megamek.server.Server.handleAttacks(Server.java:35184)
	at megamek.server.Server.handleAttacks(Server.java:35116)
	at megamek.server.Server.endCurrentPhase(Server.java:2786)
	at megamek.server.Server.changeToNextTurn(Server.java:3042)
	at megamek.server.Server.executePhase(Server.java:2475)
	at megamek.server.Server.changePhase(Server.java:2132)
	at megamek.server.Server.endCurrentPhase(Server.java:2696)
	at megamek.server.Server.checkReady(Server.java:1911)
	at megamek.server.Server.handle(Server.java:30993)
	at megamek.server.Server$PacketPump.run(Server.java:151)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
