### ISSUE TITLE
[49.8] NPE When trying to accept contract in 3060

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3215]
EDIT: This is my fault.  I had tried to add a new contract type and failed.  I thought I put the original file back but did not.  Completely my fault and not an issue with the game.  I had changed to the contract manifest to add a new type of contract but didnt revert.  Sorry.  Please delete.

**Comment by Windchild292** [comment]
```
14:20:39,472 ERROR [mekhq.campaign.stratcon.StratconContractDefinition] {AWT-EventQueue-0}
mekhq.campaign.stratcon.StratconContractDefinition.Deserialize(StratconContractDefinition.java:370) - Error deserializing contract definition .\data\stratconcontractdefinitions\Crisis.xml
jakarta.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 39; columnNumber: 3; The element type "objectiveParameters" must be terminated by the matching end-tag "</objectiveParameters>".]
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:310)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:538)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:224)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:196)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:248)
	at mekhq.campaign.stratcon.StratconContractDefinition.Deserialize(StratconContractDefinition.java:366)
	at mekhq.campaign.stratcon.StratconContractDefinition.getContractDefinition(StratconContractDefinition.java:76)
	at mekhq.campaign.mission.AtBContract.acceptContract(AtBContract.java:1152)
	at mekhq.gui.dialog.ContractMarketDialog.acceptContract(ContractMarketDialog.java:439)
```

**Comment by Thom293** [comment]
Oh actually - THIS IS MY FAULT.  I had edited a campaign contract file trying to make a new type of contract, and thought I put the original back - but I did not.  You can delete this.  I apologize.

**Comment by Windchild292** [comment]
This may be caused by user error, but it should be handled better on our end as the unhandled exception handler should never be called.

**Comment by Windchild292** [comment]
I've opened up #3237, which subsumes this.
