### ISSUE TITLE
0.49.8-SNAPSHOT: StratCon Expects Perfect Contract Definitions

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#3237]
StratCon currently breaks hard when you have any issues in your contract definition files, throwing an uncaught exception. This needs to be handled gracefully instead.

This was originally raised in the logs from #3215, with the origin exception being:
```
14:20:39,472 ERROR [mekhq.campaign.stratcon.StratconContractDefinition] {AWT-EventQueue-0}
mekhq.campaign.stratcon.StratconContractDefinition.Deserialize(StratconContractDefinition.java:370) - Error deserializing contract definition .\data\stratconcontractdefinitions\Crisis.xml
jakarta.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 39; columnNumber: 3; The element type "objectiveParameters" must be terminated by the matching end-tag "</objectiveParameters>".]
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:310)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:538)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:224)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:196)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:248)
	at mekhq.campaign.stratcon.StratconContractDefinition.Deserialize(StratconContractDefinition.java:366)
	at mekhq.campaign.stratcon.StratconContractDefinition.getContractDefinition(StratconContractDefinition.java:76)
	at mekhq.campaign.mission.AtBContract.acceptContract(AtBContract.java:1152)
	at mekhq.gui.dialog.ContractMarketDialog.acceptContract(ContractMarketDialog.java:439)
```

**Comment by IllianiCBT** [comment]
The root cause of this issue was fixed in 2024. Closing.
