### ISSUE TITLE
[49.7] Megamek freezes after end turn, MekHQ must be force-closed

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#3241]
I'll say it right away, I'm not sure which tracker this belongs to.

mekhq.MekHQ.initializeLogging(MekHQ.java:290) - Starting MekHQ v0.49.7
	Release Date: 2022-02-18
	Today: 2022-04-24
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_GB
	Total memory available to MekHQ: 2 GB

The issue here is that after playing a full Big Battle scenario, Megamek stops responding after clicking "Done" in the final report, but before that, both Megamek and MekHQ respond properly. After hitting done, the game stops responding (0% CPU usage, with memory staying stable), and MekHQ becomes completely static, with nothing in the window working, not even the window's minimize/close buttons. I can browse the report and click the Megamek window closed, but had to force close the MekHQ one.
Saving the mul when prompted and using that to resolve the battle manually after restarting the game allowed the scenario to be resolved.

Saves and logs
Campaign:
[Lisbon's Ravagers BattleDay.cpnx.gz](https://github.com/MegaMek/mekhq/files/8550229/Lisbon.s.Ravagers.BattleDay.cpnx.gz)
first turn:
[ingame.sav.gz](https://github.com/MegaMek/mekhq/files/8550231/ingame.sav.gz)
Autosaved turn, just before the issues. No enemies left, so just go through the final phases to end the battle:
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/8550234/autosave.sav.gz)
Mul:
[Lisbon's Ravagers Mul.zip](https://github.com/MegaMek/mekhq/files/8550237/Lisbon.s.Ravagers.Mul.zip)
Logs (a few NPEs there):
[legacy.log](https://github.com/MegaMek/mekhq/files/8550239/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8550241/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8550243/mekhq.log)

If needed, I have a few more intermediate megamek saves.

**Comment by Windchild292** [comment]
There's no NPEs in the provided logs, nor anything that would allow one to debug it.

**Comment by JonhyBurner** [comment]
I saw this and mislabelled:

`05:22:30,664 ERROR [megamek.common.pathfinder.AbstractPathFinder] {Princess-precognition (Lyran Commonwealth Regulars Force #2)}
megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:305) - 
java.lang.IllegalArgumentException: Entity invalid. ID 80
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:529)
	at megamek.common.MovePath.addStep(MovePath.java:376)
	at megamek.common.MovePath.addStep(MovePath.java:265)
	at megamek.common.MovePath.addStep(MovePath.java:177)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:287)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:252)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:288)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:315)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:243)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:128)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:358)
	at java.base/java.lang.Thread.run(Thread.java:829)`

Anything extra I can provide to help?

**Comment by IllianiCBT** [comment]
Given the amount of work that's been done with pathfinding over the years I'm confident this can be closed.

If you think this case has been closed in error, please let us know and it can be reopened :)
