### ISSUE TITLE
Cannot use Meklab to customize units from within MekHQ using v43.0

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#326]
EDIT: Sorry this bug is specific to MekHQ v42.0, NOT v41. I misremembered the version numbers when posting.

I have a campaign that I started in MekHQ v42. I tried transferring my savegame over to v43, and it functioned perfectly (so far) except for one issue. When I try to customize a unit by opening it in meklab from the hangar screen, I can change things as I please but when I click on the "Begin Refit" button nothing happens. If I deliberately make the unit underweight and then try the begin refit button, it will pop up a warning message about being underweight but then nothing happens when I click through it. This does NOT effect refit kits, only customization through the meklab UI tab within mekhq.

This does not happen with my original MekHQ 42 install. It only happens in 43, even if I generate a new campaign and use stock rules instead of importing the data over from 42. I looked at the mekHQ log and these are the error messages I get. These are logged each time I click the "begin refit" button.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.MekLabTab.lambda$initTab$0(MekLabTab.java:127)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by ThomasMarik** [comment]
This is a problem in the stable 42.1 build as well.  As far as I can tell it only effects foot and jump infantry.  I can open up and modify Motorized and Mechanized just fine.   Foot and jump infantry are able to be created and modified in MML standalone program but not from within mekHQ

**Comment by pheonixstorm** [comment]
This bug was caused in commit 870075c4f455e1d2cc17389f057fff2888a40675

I have been trying to identify the cause but so far no success. When the code reaches `campaignGUI.refitUnit(refit, true);` you get the above. .

If you use Choose Refit rather than try to customize the code works as intended.
