### ISSUE TITLE
Unable to edit stats for units with "corrupted" data

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#331]
Sometimes my units will come back from combat with "corrupted" stats. For instance one of my VTOLs should have 3 internal structure in all sections, but one of them has 2 structure in the front section and 4 structure in the rear section. Another case of this is an Awesome that was missing all of it's heatsinks, when I looked at it's stats it said 8 heatsinks were damaged, but no repairs could be done and I could edit them back in. If I tried to take the Awesome into a fight it had a heat dissipation rating of only 3.

There's two ways to test if a unit is "corrupted" like this. One way is to use the GM tools to restore the unit, if this does not return it to it's proper stats the unit is borked. Another way is to try to edit the unit damage condition using the GM tools, the button will not work either after a battle, or in the hangar menu. When I looked into the mekhq log this is what happens when I press the edit unit button:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at javax.swing.SpinnerNumberModel.<init>(Unknown Source)
	at javax.swing.SpinnerNumberModel.<init>(Unknown Source)
	at megamek.client.ui.swing.UnitEditorDialog.initArmorPanel(UnitEditorDialog.java:222)
	at megamek.client.ui.swing.UnitEditorDialog.initComponents(UnitEditorDialog.java:122)
	at megamek.client.ui.swing.UnitEditorDialog.<init>(UnitEditorDialog.java:107)
	at mekhq.gui.dialog.ResolveScenarioWizardDialog.editUnit(ResolveScenarioWizardDialog.java:1481)
	at mekhq.gui.dialog.ResolveScenarioWizardDialog.access$1300(ResolveScenarioWizardDialog.java:80)
	at mekhq.gui.dialog.ResolveScenarioWizardDialog$EditUnitListener.actionPerformed(ResolveScenarioWizardDialog.java:1551)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at mekhq.MekHQ.gameVictory(MekHQ.java:427)
	at megamek.common.event.GameVictoryEvent.fireEvent(GameVictoryEvent.java:70)
	at megamek.common.Game.processGameEvent(Game.java:3112)
	at megamek.client.Client.handlePacket(Client.java:1469)
	at megamek.client.Client$1$2.run(Client.java:219)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
```

There is only one solution for this that I've found if refreshing the unit stats does not work. You can only delete or sell the unit and replace it with another of the same type using the unit buy menu.

**Comment by Tamren** [comment]
Sorry to be so sparse on the details but when I went back to retrieve several savegames I had set aside specifically because they contained the borked units. They suddenly just worked fine! The units are the same ones, but the problem has vanished and they perform normally. I don't get it, but it means that I can't show you the bugged Awesome I ran into.

The only example I have left is this save. I have 4 VTOLs in my hangar, the third one is perfectly normal. However numbers 1, 2 and 4 all have damaged internal structure in the nose, the missing IS points have been erroneously assigned to the rotor location instead. If I attempt to edit any of the three bugged VTOLs it results in the error message I posted above being added to the mekhq log, once for each click.

[C68.zip](https://github.com/MegaMek/mekhq/files/792695/C68.zip)

The bugged Awesome had the same symptoms as the VTOLs, buggy in-battle performance and damage that could not be fixed through the repair bay or edited using the GM tools. This has also happened on several other mechs like a Vindicator but like the Awesome the savegame I put aside no longer replicates the problem for the other mech examples.
