### ISSUE TITLE
[0.49.9-Snapshot] Uncaught java.util.FormatFlagsConversionMismatchException 

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3353]
### Environment
V: 0.49.9-Snapshot
O: Linux 5.4.0-109-generic x86_64 GNU/Linux
J: openjdk 11.0.15 2022-04-19

### Description
I just tried the retirement dialog in the latest dev-release and received an Uncaught java.util.FormatFlagsConversionMismatchException.

What it does: it removes the final payout correctly
What it doesn't: remove the personnel 

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/8892914/mekhq.log)

**Comment by Windchild292** [comment]
```
18:27:11,626 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:239) - Uncaught Exception Detected
java.util.FormatFlagsConversionMismatchException: Conversion = h, Flags =  
	at java.base/java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4422)
	at java.base/java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3151)
	at java.base/java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3109)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2870)
	at java.base/java.util.Formatter.parse(Formatter.java:2713)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at mekhq.campaign.personnel.Person.changeStatus(Person.java:941)
	at mekhq.campaign.Campaign.applyRetirement(Campaign.java:687)
	at mekhq.gui.CampaignGUI.showRetirementDefectionDialog(CampaignGUI.java:195)
	at mekhq.gui.CampaignGUI.lambda$initMenu$37(CampaignGUI.java:978)
```

**Comment by Windchild292** [comment]
Subsumed by #3370
