### ISSUE TITLE
[Bug] [49.9 #795] Annual Retirement Dialogue Soft-Lock

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#3370]
### Environment
Version: 49.9 #795 (first encountered in #794)
OS: Mac OS X 12.4 (x86_64)
Jave: Homebrew 11.0.12

### Description
Annual Retirement roll triggered. However, despite retirement funds being paid out, game acts as if insufficient funds were present and prompts the following day for further (identical payment).

### Reproduction
Load provided save, progress days until annual retirement roll is triggered. Pay for retirement. Advance day, encounter issue.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/103902653/174456795-0d81a79a-bb0f-49c5-a541-a039c60d9431.png">

### Files
[Retirement Soft-Lock.cpnx.gz](https://github.com/MegaMek/mekhq/files/8934319/Retirement.Soft-Lock.cpnx.gz)

[mekhq.log](https://github.com/MegaMek/mekhq/files/8934320/mekhq.log)

[Custom Unit(s).zip](https://github.com/MegaMek/mekhq/files/8934323/Custom.Unit.s.zip)

**Comment by IllianiCBT** [comment]
So, further investigation:

- The persons selected for retirement are not removed from the roster, as if retirement payout hadn't been paid.

- Attempting to manually switch the affected personnel to 'retired' throws up an Uncaught Java Exception:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/103902653/174457034-ffd879ee-e6ba-481b-a4f1-b5d2e5e200e4.png">
The above is true, even if the personnel are switched to another status first (MIA, for example).

[mekhq.log](https://github.com/MegaMek/mekhq/files/8934353/mekhq.log)

**Comment by IllianiCBT** [comment]
Issue identical to https://github.com/MegaMek/mekhq/issues/3353#issuecomment-1159555213

Apologies for the double-report. I missed the above when checking the issues list.

**Comment by Windchild292** [comment]
```
18:27:11,626 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:239) - Uncaught Exception Detected
java.util.FormatFlagsConversionMismatchException: Conversion = h, Flags =  
	at java.base/java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4422)
	at java.base/java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3151)
	at java.base/java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3109)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2870)
	at java.base/java.util.Formatter.parse(Formatter.java:2713)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at mekhq.campaign.personnel.Person.changeStatus(Person.java:941)
	at mekhq.campaign.Campaign.applyRetirement(Campaign.java:687)
	at mekhq.gui.CampaignGUI.showRetirementDefectionDialog(CampaignGUI.java:195)
	at mekhq.gui.CampaignGUI.lambda$initMenu$37(CampaignGUI.java:978)
```

**Comment by Windchild292** [comment]
No worries, and it's an exception I've never even heard of before which is always an interesting state of affairs.
