### ISSUE TITLE
[Bug} [49.9 #975] Uncaught Exception When Advancing Day

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#3372]
### Environment
Version: 49.9 #975
Jave: Homebrew 11.0.12
Platform: Mac OS X 12.4 (x86_64)

### Description
Upon clicking 'advance day' MekHQ throws up an Uncaught Exception. The day progresses in the Daily Activity Log, but as an amendment to the prior day:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/103902653/174460093-42846d07-b958-452c-a90c-a99b78c74615.png">

### Reproduction
Using the attached campaign file advance two days.

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/8934506/mekhq.log)
[AdvanceDayException.cpnx.gz](https://github.com/MegaMek/mekhq/files/8934508/AdvanceDayException.cpnx.gz)

**Comment by Windchild292** [comment]
```
18:25:44,846 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:239) - Uncaught Exception Detected
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at mekhq.campaign.finances.Finances.newDay(Finances.java:330)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3507)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$46(CampaignGUI.java:1121)
```

**Comment by IllianiCBT** [comment]
Update: testing further, it appears I can avoid the error by adding sufficient funds to cover the loan payment.

Without sufficient funds the payment isn't made, but the exception occurs:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/103902653/174460317-fdeb81d5-0938-4b3d-b3d0-bb40406e467f.png">

With sufficient funds, the payment is made and no exception occurs:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/103902653/174460335-6f4261c5-95bf-47f6-b1bc-569ff1977d35.png">

**Comment by Windchild292** [comment]
We need the customs to test.

![image](https://user-images.githubusercontent.com/39067288/175203137-27209909-d100-4394-8f6f-e9085b3b8968.png)

**Comment by IllianiCBT** [comment]
Ugh, sorry, school boy error. I’ll get this done when I wake up.

**Comment by IllianiCBT** [comment]
Here you go:
[Custom Units.zip](https://github.com/MegaMek/mekhq/files/8964418/Custom.Units.zip)
