### ISSUE TITLE
[49.8] Unable to save after starting MekHQ by loading from a save running stratcon contract (NPE)

### ISSUE THREAD

**Issue by dragonkid11** [MegaMek/mekhq#3401]
Environment

MekHQ 49.8
Windows 8.1
Java Adoptium 11

Description
The game occurs after starting up MekHQ by loading from a save that's currently running a stratcon mission, I did not start stratcon in the middle of a contract, and before this, I finished 2 full battles, salvaging, saving the game at this point still works.

After closing the game and starting it up, saving doesn't work anymore, and only with this savefile.

Loading earlier instances of the same campaign works.

Below is the mekHQ log and the bugged savefile.

Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/9142907/mekhq.log)
[Dragon Dragoon31480922.cpnx.gz](https://github.com/MegaMek/mekhq/files/9142927/Dragon.Dragoon31480922.cpnx.gz)

**Comment by HammerGS** [comment]
```
mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1404) - 
java.lang.NullPointerException
	at megamek.common.Compute.effectiveDistance(Compute.java:1721)
	at megamek.common.Entity.onSameC3NetworkAs(Entity.java:6201)
	at mekhq.utilities.MHQXMLUtility.writeEntityToXmlString(MHQXMLUtility.java:223)
	at mekhq.utilities.MHQXMLUtility.writeEntityWithCrewToXML(MHQXMLUtility.java:457)
	at mekhq.campaign.mission.BotForce.writeToXML(BotForce.java:330)
	at mekhq.campaign.mission.Scenario.writeToXMLBegin(Scenario.java:782)
	at mekhq.campaign.mission.Scenario.writeToXML(Scenario.java:753)
	at mekhq.campaign.mission.Mission.writeToXMLBegin(Mission.java:220)
	at mekhq.campaign.mission.Contract.writeToXMLBegin(Contract.java:661)
	at mekhq.campaign.mission.AtBContract.writeToXMLBegin(AtBContract.java:770)
	at mekhq.campaign.mission.Mission.writeToXML(Mission.java:202)
	at mekhq.campaign.Campaign.writeToXML(Campaign.java:4132)
	at mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1394)
	at mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1361)
```

**Comment by Windchild292** [comment]
This is either related to a null game or a null return from Game::getBoard. The former has had a major bugfix since 0.49.8 for this exact case, and is the most likely cause of it.

**Comment by dragonkid11** [comment]
Opfor seems to be the problem, as deleting or fighting them then save works perfectly fine.

**Comment by IllianiCBT** [comment]
This should no longer be an issue. Closing as resolved. If you think this case was closed in error, feel free to let us know and we can get it reopened. :)
