### ISSUE TITLE
[0.49.7] Reloading Rocket Pods on Thunderbird ASF never completes and right-clicking throws NPE

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#3409]
### Environment
	MekHQ v0.49.7
	Release Date: 2022-02-18
	Today: 2022-07-24
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.13
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 8 GB

### Description
Possibly related to #3166 but not sure...

I salvaged a Thunderbird ASF with rocket pods in 3041. When it first arrived in my hanger (and repair bay) it stated that the tech hadn't been invented yet. No big deal, I'll repair what I can. When I advanced the day, suddenly all the rocket pods were being reloaded. Again, no big deal, I had salvaged from Rocket Launcher gun emplacements in a previous scenario, maybe the ammo was coming from there. Advanced the day again... still being reloaded. That's odd, so I right click on the unit to try to change repair type: NPE.  Right click on the ammo bin to GM Complete: Doesn't seem to do anything, though the Daily Report says it's fixed.

```
23:27:06,428 WARN  [mekhq.campaign.parts.equipment.AmmoBin] {AWT-EventQueue-0}
mekhq.campaign.parts.equipment.AmmoBin.getMounted(AmmoBin.java:296) - Missing valid equipment for Rocket Launcher Pod Bin to manage ammo on unit Thunderbird TRB-D36 ID:50

23:27:06,428 WARN  [mekhq.campaign.parts.equipment.AmmoBin] {AWT-EventQueue-0}
mekhq.campaign.parts.equipment.AmmoBin.getMounted(AmmoBin.java:296) - Missing valid equipment for Rocket Launcher Pod Bin to manage ammo on unit Thunderbird TRB-D36 ID:50

23:27:06,991 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.NullPointerException
	at mekhq.Utilities.getMunitionsFor(Utilities.java:214)
	at mekhq.gui.adapter.ServicedUnitsTableMouseAdapter.createPopupMenu(ServicedUnitsTableMouseAdapter.java:205)
	at mekhq.gui.adapter.JPopupMenuAdapter.maybeShowPopup(JPopupMenuAdapter.java:82)
	at mekhq.gui.adapter.JPopupMenuAdapter.mouseReleased(JPopupMenuAdapter.java:77)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Files
[BuggedThunderbird30410227.cpnx.gz](https://github.com/MegaMek/mekhq/files/9177790/BuggedThunderbird30410227.cpnx.gz)
megamek.log and mekhq.log: compressed because they are too large otherwise [logs.zip](https://github.com/MegaMek/mekhq/files/9177793/logs.zip)
Custom mech units: [userdata.zip](https://github.com/MegaMek/mekhq/files/9177794/userdata.zip)

**Comment by SuperStucco** [comment]
I find some weirdness with salvaged fighters with external ordnance - I can't do anything with them unless the MekHQ session is closed and restarted.  Until that happens it treats those items as equipment to be handled in the Repair Bay tab; after that they can be unloaded as normal in the Hanger tab.

**Comment by mjbroekman** [comment]
> I find some weirdness with salvaged fighters with external ordnance - I can't do anything with them unless the MekHQ session is closed and restarted. Until that happens it treats those items as equipment to be handled in the Repair Bay tab; after that they can be unloaded as normal in the Hanger tab.

That worked a treat. When I loaded up tonight to continue playing, the rocket pods were no longer in the repair bay list.

**Comment by IllianiBird** [comment]
This is linked to the 'ghost mech' bug fixed last year, closing
