### ISSUE TITLE
[MekLab] Unable to begin refit

### ISSUE THREAD

**Issue by Rael-M** [MegaMek/mekhq#359]
Tried to replace the LRM on a Grasshopper 5H for a medium laser, a heat sink and max armour.  Have all the parts and am unable to refit.  This is with both 4.2 and 4.3.  Tried replacing a medium laser on a Catapult C-1 with a small laser to see if it was just a problem with the 5H but unable to refit that either.

**Comment by HammerGS** [comment]
If this is in MekHQ, its a known bug.

**Comment by neoancient** [comment]
"Unable to refit" does not provide any useful information. What happened when you attempted it? At what point did you fail to get the expected result? What happened instead? Were there any errors in the log file? My best guess is that this is a bug that has already been fixed for the next release but without more information I can't know that.

**Comment by Rael-M** [comment]
@HammerGS Yes it's in MekHQ.  

@neoancient Basically I outfit the mech the way I want it in the MekLab in MekHQ, everything looks good, not overweight or under, all criticals sorted, all parts accounted for.  I hit Begin Refit and well to be blunt, nothing, no error message, no confirmation message just nothing.  Tried repeatedly pressing it, tried different mechs of various tech to see if it was a specific chassis or tech level but same result, no error message or confirmation message.

Refit via kit works no problem but customizing from the lab is just met with no messages of any kind.

As for the log, I believe this section here is the culprit.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.MekLabTab.lambda$initTab$0(MekLabTab.java:127)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by neoancient** [comment]
That's what I suspected. This was first reported in #326 and fixed in 32fa181. We are hoping to have a new development snapshot out this weekend, which will contain this fix.
