### ISSUE TITLE
IllegalArgumentException thrown mid-combat

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#3628]
### Environment
        Starting MegaMek v0.49.12
        Build Date: 2023-03-04T15:27:34.905712500
        Origin Project: MekHQ
        Java Vendor: Homebrew
        Java Version: 11.0.18
        Platform: Mac OS X 13.2.1 (aarch64)
        System Locale: en_US
        Total memory available to MegaMek: 8 GB

### Description
While in combat in MegaMek, MekHQ throws a java.lang.IllegalArgumentException, causing MegaMek to stop. Reloading the previous round's save does not allow me to proceed.

### Files
MegaMek autosave file, Campaign Savegame, custom units, and logs are in issue_report_files.tgz

[issue_report_files.tgz](https://github.com/MegaMek/mekhq/files/11045090/issue_report_files.tgz)

**Comment by kuronekochomusuke** [comment]
may be related to [#4233](https://github.com/MegaMek/megamek/issues/4233)

**Comment by HammerGS** [comment]
From the MekHQ Log and moving to MegaMek Tracker. 

```
18:00:34,102 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at megamek.common.TurnOrdered.generateTurnOrder(TurnOrdered.java:441)
	at megamek.server.GameManager.determineTurnOrderIUI(GameManager.java:2766)
	at megamek.server.GameManager.determineTurnOrder(GameManager.java:2798)
	at megamek.server.GameManager.prepareForPhase(GameManager.java:1750)
	at megamek.server.GameManager.changePhase(GameManager.java:1592)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2172)
	at megamek.server.GameManager.checkReady(GameManager.java:1382)
	at megamek.server.GameManager.handlePacket(GameManager.java:723)
	at megamek.server.Server.handle(Server.java:1257)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
