### ISSUE TITLE
[49.12] News throwing exceptions

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#3635]
Running a campaign with current date of 24-March 3045. Every day is generating exceptions regarding the news. Two different exceptions are below: a date format and a number format

12:44:09,392 ERROR [mekhq.campaign.universe.News] {AWT-EventQueue-0}
mekhq.campaign.universe.News.loadNewsFor(News.java:140) - 
jakarta.xml.bind.UnmarshalException
 - with linked exception:
[java.lang.reflect.InvocationTargetException]
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:693)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext.handleError(UnmarshallingContext.java:720)
	at org.glassfish.jaxb.runtime.v2.runtime.JaxBeanInfo.invokeUnmarshallCallback(JaxBeanInfo.java:536)
	at org.glassfish.jaxb.runtime.v2.runtime.JaxBeanInfo.invokeAfterUnmarshalMethod(JaxBeanInfo.java:529)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.Loader.fireAfterUnmarshal(Loader.java:201)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.StructureLoader.leaveElement(StructureLoader.java:265)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext.endElement(UnmarshallingContext.java:556)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.InterningXmlVisitor.endElement(InterningXmlVisitor.java:56)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:149)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.scan(DOMScanner.java:102)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:330)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:313)
	at mekhq.campaign.universe.News.loadNewsFor(News.java:138)
	at mekhq.campaign.Campaign.reloadNews(Campaign.java:2966)
	at mekhq.gui.CampaignGUI.menuOptionsActionPerformed(CampaignGUI.java:1547)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jaxb.runtime.v2.runtime.JaxBeanInfo.invokeUnmarshallCallback(JaxBeanInfo.java:534)
	... 50 more
Caused by: java.time.format.DateTimeParseException: Text '2309-5-01' could not be parsed at index 5
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at java.base/java.time.LocalDate.parse(LocalDate.java:428)
	at java.base/java.time.LocalDate.parse(LocalDate.java:413)
	at megamek.utilities.xml.MMXMLUtility.parseDate(MMXMLUtility.java:442)
	at mekhq.campaign.universe.NewsItem.afterUnmarshal(NewsItem.java:197)
	... 54 more

12:44:09,396 ERROR [mekhq.campaign.universe.News] {AWT-EventQueue-0}
mekhq.campaign.universe.News.loadNewsFor(News.java:140) - 
jakarta.xml.bind.UnmarshalException
 - with linked exception:
[java.lang.reflect.InvocationTargetException]
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:693)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext.handleError(UnmarshallingContext.java:720)
	at org.glassfish.jaxb.runtime.v2.runtime.JaxBeanInfo.invokeUnmarshallCallback(JaxBeanInfo.java:536)
	at org.glassfish.jaxb.runtime.v2.runtime.JaxBeanInfo.invokeAfterUnmarshalMethod(JaxBeanInfo.java:529)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.Loader.fireAfterUnmarshal(Loader.java:201)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.StructureLoader.leaveElement(StructureLoader.java:265)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext.endElement(UnmarshallingContext.java:556)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.InterningXmlVisitor.endElement(InterningXmlVisitor.java:56)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:149)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.scan(DOMScanner.java:102)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:330)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:313)
	at mekhq.campaign.universe.News.loadNewsFor(News.java:138)
	at mekhq.campaign.Campaign.reloadNews(Campaign.java:2966)
	at mekhq.gui.CampaignGUI.menuOptionsActionPerformed(CampaignGUI.java:1547)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jaxb.runtime.v2.runtime.JaxBeanInfo.invokeUnmarshallCallback(JaxBeanInfo.java:534)
	... 50 more
Caused by: java.lang.NumberFormatException: For input string: "29XX"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at megamek.utilities.xml.MMXMLUtility.parseDate(MMXMLUtility.java:439)
	at mekhq.campaign.universe.NewsItem.afterUnmarshal(NewsItem.java:197)
	... 54 more

**Comment by HammerGS** [comment]
We had a couple of typo's and they should be fixed in the repo. You could grab the new news.xml file to test. 

https://github.com/MegaMek/mekhq/blob/master/MekHQ/data/universe/news.xml

**Comment by kipstafoo** [comment]
Thanks @HammerGS. That seems to have fixed the issue. I'll re-open if I come across it happening again.
