### ISSUE TITLE
0.49.14 Salvaged units don't appear in the hangar until the day is advanced

### ISSUE THREAD

**Issue by AQGadget** [MegaMek/mekhq#3751]
Salvaged units don't appear in the hangar until the day is advanced

### Environment
MHQ 0.49.14
Windows 10
Java Version: 11.0.13

### Description
Salvaged units don't appear in the hangar until the day is advanced or the game is saved and reloaded
They are added to the roster after a mission, but not in the hangar
![added to roster](https://github.com/MegaMek/mekhq/assets/17732457/18f7dc21-2d50-4155-bffc-8256fdf9526c)

![not in roster](https://github.com/MegaMek/mekhq/assets/17732457/b281bed1-778c-489e-9dd3-cf306477ce43)

The game gives a warning that there are unmaintained units, so they are actually there, just not displayed

![but actually there](https://github.com/MegaMek/mekhq/assets/17732457/b9fe2506-6c30-4390-8c4b-1301cfe52f7a)

They will appear after advancing the day, or saving and loading the game
![show up after day advance](https://github.com/MegaMek/mekhq/assets/17732457/3fdbffe9-15fa-4dc0-8e2f-aa9300e8a599)

![or loading a save](https://github.com/MegaMek/mekhq/assets/17732457/17f7aafd-82d1-47a4-8508-53c97dc4764a)

It does not happen when resolving manually with an MUL, only when brought back automatically from megamek

### Files
[The Ghoul Claws30470427a.cpnx.gz](https://github.com/MegaMek/mekhq/files/12479961/The.Ghoul.Claws30470427a.cpnx.gz)

**Comment by AQGadget** [comment]
It continues to do it. Grabbed a log right after a scenario.
[mekhq.log](https://github.com/MegaMek/mekhq/files/12796894/mekhq.log)

16:58:56,519 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.gameVictory(MekHQ.java:490) - 
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at mekhq.campaign.event.ScenarioEvent.<init>(ScenarioEvent.java:36)
	at mekhq.campaign.event.ScenarioChangedEvent.<init>(ScenarioChangedEvent.java:31)
	at mekhq.campaign.event.ScenarioResolvedEvent.<init>(ScenarioResolvedEvent.java:31)
	at mekhq.MekHQ.gameVictory(MekHQ.java:488)
	at megamek.common.event.GameVictoryEvent.fireEvent(GameVictoryEvent.java:65)
	at megamek.common.Game.processGameEvent(Game.java:3011)
	at megamek.client.Client.handlePacket(Client.java:1658)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:174)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by AQGadget** [comment]
Issue resolved by updating to Java 11.0.19 from 11.0.13

**Comment by AQGadget** [comment]
Thought it was resolved, but still getting it with Java 11. 0.19
