### ISSUE TITLE
NullPointerException at firing phase start

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/mekhq#3755]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MekHQ 0.49.14
Windows 10
Java 17.0.8

### Description
NullPointerException when starting firing phase - seems to be artillery related?

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the megamek.log and mekhq.log files for any NPEs or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megamek.log and mekhq.log files
(Delete the above lines)

[megamek.log](https://github.com/MegaMek/mekhq/files/12517800/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/12517801/mekhq.log)

[Czechoslovak Foreign Legion30270919.cpnx.gz](https://github.com/MegaMek/mekhq/files/12517807/Czechoslovak.Foreign.Legion30270919.cpnx.gz)

Savegame: advance turn to firing phase to get NullPointerException. I had a Thumper artillery vehicle off screen, but I fled it to avoid sniper turret counterfire
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/12517810/autosave.sav.gz)

Custom mechs: Dervish and Archer are in this battle
[Czechoslovak Foreign Legion.zip](https://github.com/MegaMek/mekhq/files/12517859/Czechoslovak.Foreign.Legion.zip)

**Comment by HammerGS** [comment]
From the log.

```
21:26:14,638 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "megamek.common.Targetable.getPosition()" because "this.target" is null
	at megamek.common.weapons.ArtilleryWeaponIndirectFireHandler.handle(ArtilleryWeaponIndirectFireHandler.java:106)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34325)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34261)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2471)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2708)
	at megamek.server.GameManager.executePhase(GameManager.java:2155)
	at megamek.server.GameManager.changePhase(GameManager.java:1584)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2378)
	at megamek.server.GameManager.checkReady(GameManager.java:1367)
	at megamek.server.GameManager.handlePacket(GameManager.java:722)
	at megamek.server.Server.handle(Server.java:1265)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
