### ISSUE TITLE
NullPointerException detected in MekHQ/Stratcon battle

### ISSUE THREAD

**Issue by CampaignAnon** [MegaMek/mekhq#3777]
Version: 49.15
On the first round of movement in a brand new MekHQ campaign, Princess OpFor and Ally moves some units, and presumably when control is returned to the player the game hangs with no movement possible for next unit in list of player mechs (Orion -1VA in this save game). Saving the game and disconnecting MegaMek client to relaunch results in an "Uncaught java.lang.NullPointerException" popup. Attached to this post are all logs as directed, the campaign and match save files, as well as all customs available, though only two (Phoenix Hawk PHX-2G and Battlemaster BLR-3N) are present in the battle.
[Exception Log - 11-05.zip](https://github.com/MegaMek/mekhq/files/13259175/Exception.Log.-.11-05.zip)

**Comment by kuronekochomusuke** [comment]
03:18:21,227 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.client.ui.swing.MovementDisplay.updateConvertModeButton(MovementDisplay.java:2700)
	at megamek.client.ui.swing.MovementDisplay.hexMoused(MovementDisplay.java:2139)
	at megamek.client.ui.swing.boardview.BoardView.processBoardViewEvent(BoardView.java:961)
	at megamek.client.ui.swing.boardview.BoardView.mouseAction(BoardView.java:4839)
	at megamek.client.ui.swing.boardview.BoardView.mouseAction(BoardView.java:4871)
	at megamek.client.ui.swing.boardview.BoardView.mouseReleased(BoardView.java:4593)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Sleet01** [comment]
The line in question:

```
if (cmd.length() > 0 && cmd.getLastStep().getType() != MoveStepType.CONVERT_MODE) {
```
Looks like there's no `cmd` set for some reason.
