### ISSUE TITLE
Uncaught java.lang.IllegalArgumentException detected 

### ISSUE THREAD

**Issue by Sebmono** [MegaMek/mekhq#3795]
### Environment
0.49.15
Windows 10
Java Vendor: Eclipse Adoptium
Java Version: 11.0.13

### Description
![image](https://github.com/MegaMek/mekhq/assets/7840034/8ac86c6c-ece7-4e48-8cc1-9d8f8865831b)
I get the above error after clicking the 'Done' button at the end of the Round 15 Firing Phase. 

Exact reproduction steps with the below campaign and MegaMek save file:
1. Load the below campaign save file.
2. Click Load Saved Game from the Briefing Room for the TankBase - Hostile - Prevent Evac scenario.
3. Select OK, load the BA_01.sav file below.
4. Game > Edit Bots > Replace all with Princess > OK
5. Have Booster fire autorifle at pilot north of her.
6. Have Voltage fire autorifle at crew north of him.
7. Have Jester fire all weapons at Cataphract closest to him.
8. Have Calamity fire all weapons at Cataphract closest to her (same one as Jester).
9. Select Done.
10. After Fire Phase resolution log is produced, click done.
11. Error.

### Files
Provide the .cpnx campaign file that this issue occurs in.
[Poznan Heavy Lancers02.cpnx.gz](https://github.com/MegaMek/mekhq/files/13636685/Poznan.Heavy.Lancers02.cpnx.gz)

Also here is the MegaMek in-mission save file it occurs in.
[BA_01.sav.gz](https://github.com/MegaMek/mekhq/files/13636780/BA_01.sav.gz)

Provide any custom units that you are using in this campaign so that it will load on the developers machine.
[Black Knight BL-7-KNT Hussar.zip](https://github.com/MegaMek/mekhq/files/13636708/Black.Knight.BL-7-KNT.Hussar.zip)

Provide any other files that you have customized in this campaign like the factions.xml for example.
I'm using the customized "Heavy" scenarios from Discord here: https://discord.com/channels/458705327911731231/1125131384835555491/1125151393515327498
[scenariotemplates.zip](https://github.com/MegaMek/mekhq/files/13636750/scenariotemplates.zip)

And provide the megamek.log and mekhq.log files for any NPEs or errors that MekHQ might be reporting.
[mekhq.log](https://github.com/MegaMek/mekhq/files/13636773/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/13636774/megamek.log)

**Comment by HammerGS** [comment]
From the MekHQ log
```

java.lang.IllegalArgumentException: Attacker or target not valid
	at megamek.common.actions.ThrashAttackAction.toHit(ThrashAttackAction.java:51)
	at megamek.common.Compute.canPhysicalTarget(Compute.java:5879)
	at megamek.common.Entity.isEligibleForPhysical(Entity.java:9933)
	at megamek.common.Entity.isEligibleFor(Entity.java:9719)
	at megamek.common.Infantry.isEligibleFor(Infantry.java:1068)
	at megamek.server.GameManager.setIneligible(GameManager.java:3609)
	at megamek.server.GameManager.prepareForPhase(GameManager.java:1989)
	at megamek.server.GameManager.changePhase(GameManager.java:1586)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2426)
	at megamek.server.GameManager.checkReady(GameManager.java:1376)
	at megamek.server.GameManager.handlePacket(GameManager.java:722)
	at megamek.server.Server.handle(Server.java:1265)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
