### ISSUE TITLE
Unknown weather

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#381]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Unknown weather condition
	at megamek.common.PlanetaryConditions.getWeatherDisplayableName(PlanetaryConditions.java:160)
	at mekhq.gui.view.AtBScenarioViewPanel.fillStats(AtBScenarioViewPanel.java:439)
	at mekhq.gui.view.AtBScenarioViewPanel.initComponents(AtBScenarioViewPanel.java:188)
	at mekhq.gui.view.AtBScenarioViewPanel.<init>(AtBScenarioViewPanel.java:168)
	at mekhq.gui.BriefingTab.refreshScenarioView(BriefingTab.java:854)

The scenario has a weather type 12, which is valid, yet at the same time PlanetaryConditions in MegaMek.common doesn't have a max size (WE_SIZE) which is valid for all the defined weather conditions.

**Comment by pheonixstorm** [comment]
.... Found the problem. I missed adding in the Blizzard weather condition to the list.

**Comment by pheonixstorm** [comment]
A fix for this is up Megamek/megamek#533

**Comment by pheonixstorm** [comment]
The fix has been merged in MM. This ticket can now be closed.
