### ISSUE TITLE
Warehouse Mass Repair no longer works in 0.43.1

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#382]
I moved my campaign save over to 0.43.1 today. I noticed that the warehouse mass repair feature no longer works. It works in 0.42 and 0.43, but not 0.43.1

Each time I click the "mass repair" button this error appears in the log:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.dialog.MassRepairSalvageDialog.createMassRepairOptionItemBox(MassRepairSalvageDialog.java:760)
	at mekhq.gui.dialog.MassRepairSalvageDialog.createMassRepairOptionControls(MassRepairSalvageDialog.java:683)
	at mekhq.gui.dialog.MassRepairSalvageDialog.createOptionsPanel(MassRepairSalvageDialog.java:653)
	at mekhq.gui.dialog.MassRepairSalvageDialog.initComponents(MassRepairSalvageDialog.java:312)
	at mekhq.gui.dialog.MassRepairSalvageDialog.<init>(MassRepairSalvageDialog.java:129)
	at mekhq.gui.dialog.MassRepairSalvageDialog.<init>(MassRepairSalvageDialog.java:159)
	at mekhq.gui.adapter.PartsTableMouseAdapter.actionPerformed(PartsTableMouseAdapter.java:146)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

```

**Comment by kipstafoo** [comment]
I have a fix for this. I will commit it after May 1, when I return from vacation.
