### ISSUE TITLE
Uncaught java.util.concurrentmodificationexception

### ISSUE THREAD

**Issue by Lightninglash148** [MegaMek/mekhq#3879]
0.49.18 Development
Windows
Java Version 11.0.20

Last night and recently today a popup has appeared on my screen while playing MekHQ in a battle labelled Uncaught java.util.ConcurrentModificationException. It appeared in the previously completed mission and now appears in the newest mission I'm attempting. It doesn't start when the mission starts, usually taking several rounds (In this case it was round 2.)

[Clairs Contenders30500805.cpnx.gz](https://github.com/MegaMek/mekhq/files/14564442/Clairs.Contenders30500805.cpnx.gz)
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/14564452/entitystatus.txt)
[megamek.log](https://github.com/MegaMek/mekhq/files/14564453/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/14564454/megameklab.log)
[Custom Mechs.zip](https://github.com/MegaMek/mekhq/files/14564536/Custom.Mechs.zip)
([mekhq.log](https://github.com/MegaMek/mekhq/files/14564455/mekhq.log))

**Comment by HammerGS** [comment]
Couple of these in the MM log.
```
17:07:29,314 ERROR [megamek.common.net.connections.AbstractConnection] {Connection 0}
megamek.common.net.connections.AbstractConnection.sendNow(AbstractConnection.java:214) - 
java.net.SocketException: Software caused connection abort: socket write error
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
	at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at megamek.common.net.connections.DataStreamConnection.sendNetworkPacket(DataStreamConnection.java:105)
	at megamek.common.net.connections.AbstractConnection.sendNow(AbstractConnection.java:212)
	at megamek.common.net.connections.AbstractConnection.processPacket(AbstractConnection.java:340)
	at megamek.common.net.connections.AbstractConnection.flush(AbstractConnection.java:310)
	at megamek.common.net.connections.DataStreamConnection.flush(DataStreamConnection.java:115)
	at megamek.common.net.connections.AbstractConnection.send(AbstractConnection.java:206)
	at megamek.server.Server.lambda$send$0(Server.java:1149)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at megamek.server.Server.send(Server.java:1149)
	at megamek.server.GameManager.send(GameManager.java:608)
	at megamek.server.GameManager.removeAllEntitiesOwnedBy(GameManager.java:597)
	at megamek.server.GameManager.disconnect(GameManager.java:490)
	at megamek.server.Server.disconnected(Server.java:834)
	at megamek.server.Server$1.disconnected(Server.java:210)
	at megamek.common.net.connections.AbstractConnection.processConnectionEvent(AbstractConnection.java:372)
	at megamek.common.net.connections.AbstractConnection.close(AbstractConnection.java:158)
	at megamek.server.Server.handle(Server.java:1229)
	at megamek.server.Server$1.packetReceived(Server.java:227)
	at megamek.common.net.connections.AbstractConnection.processConnectionEvent(AbstractConnection.java:375)
	at megamek.common.net.connections.AbstractConnection.processPacket(AbstractConnection.java:334)
	at megamek.common.net.connections.AbstractConnection.update(AbstractConnection.java:285)
	at megamek.server.ConnectionHandler.run(ConnectionHandler.java:47)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

and

```
18:21:16,142 ERROR [megamek.common.pathfinder.AbstractPathFinder] {Princess-precognition (Base Civilian Units)}
megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:285) - 
java.lang.IllegalArgumentException: Entity invalid. ID 72
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:561)
	at megamek.common.MovePath.addStep(MovePath.java:371)
	at megamek.common.MovePath.addStep(MovePath.java:263)
	at megamek.common.MovePath.addStep(MovePath.java:175)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:309)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:233)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:270)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:295)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:245)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:364)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by HammerGS** [comment]
From the MekHQ Log
```
13:31:58,383 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1510)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1533)
	at megamek.client.ui.swing.util.MegaMekController.stopAllRepeating(MegaMekController.java:218)
	at megamek.client.ui.swing.ActionPhaseDisplay$1.actionPerformed(ActionPhaseDisplay.java:73)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at megamek.client.ui.swing.widget.MegamekButton.processMouseEvent(MegamekButton.java:242)
```

**Comment by Sleet01** [comment]
From further discussion on Discord, this likely arises when the Round Report pops up while another dialog is open.  We've seen several other issues occur in this situation, due to switching context and losing references; we probably need to make  the Round Report code able to run alongside other UI elements.
