### ISSUE TITLE
[0.49.18] MekHQ contract creation throws NPE when no system is selected

### ISSUE THREAD

**Issue by HSAR** [MegaMek/mekhq#3881]
### Environment
What version of MekHQ does your issue apply to? 0.49.18
What operating system are you using?  Windows 11
What java version are you using? 17.0.10

### Description
Start a new campaign, go to Briefing Room tab -> Add Mission -> New Contract. See that the system dropdown is empty. Press OK button. Uncaught NPE is thrown.

```
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.universe.PlanetarySystem.getId()" because the return value of "mekhq.campaign.universe.Systems.getSystemByName(String, java.time.LocalDate)" is null
	at mekhq.gui.dialog.NewAtBContractDialog.btnOKActionPerformed(NewAtBContractDialog.java:517)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
... 
[lots more, cut for conciseness]
```

This should be a quick fix - a more helpful error message that the system can't be empty would fix this bug.

### Files
[megamek.log](https://github.com/MegaMek/mekhq/files/14573993/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14573994/mekhq.log)
[Orwell Heavy Rifles30620101.cpnx.gz](https://github.com/MegaMek/mekhq/files/14573996/Orwell.Heavy.Rifles30620101.cpnx.gz)

**Comment by BullseyeSmith** [comment]
Hey All! I've decided to make time to test the nightly releases a check out all the cool things @IllianiCBT has been implementing, so this will hopefully be the first of several post from me. 😁
Didn't take long to see that if you select Briefing Room > Add Mission > New Contract, then choose Employer & Enemy, but no contract, and click OK, you get the following pop-up:
![image](https://github.com/user-attachments/assets/90e70c9e-2034-4920-a9a7-468e4ded1926)
Side Note: this pop-up should direct players to github.com/MegaMek/mekhq/issues, not megamek/issues.

Following the new Bug Report template, a tried the same thing in the Milestone 0.4
9.19.1 and got the same result.
Then I searched the list of known issues and found this entry, which sounds like the same problem I'm having.
Windows 11, Java 17.0.13
[0.50.01-SNAPSHOT-logs.zip](https://github.com/user-attachments/files/17693693/0.50.01-SNAPSHOT-logs.zip)

**Comment by HammerGS** [comment]
```
17:18:12,218 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:291) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.universe.PlanetarySystem.getId()" because the return value of "mekhq.campaign.universe.Systems.getSystemByName(String, java.time.LocalDate)" is null
	at mekhq.gui.dialog.NewAtBContractDialog.btnOKActionPerformed(NewAtBContractDialog.java:523)
```

**Comment by BullseyeSmith** [comment]
With 0.49.19.1, I'm using Start a New Campaign > StratCon Alpha > Date 2315-06-02 > Briefing Room > Add Mission > New Contract. Employer: Federation of Skye, Enemy: Free Worlds League, Location Blank, creates the following error log entry:
`18:45:08,937 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:242) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.universe.PlanetarySystem.getId()" because the return value of "mekhq.campaign.universe.Systems.getSystemByName(String, java.time.LocalDate)" is null`

When I close the error pop-up and choose Location: Ford and click OK, then the New Contract is generated.

With 0.50.01, I'm using Start a New Campaign > 2 - Complete Experience (StratCon Beta) > Age of War > Founding of the Hegemony (Date 2315-06-02) > Briefing Room > Add Mission > New Contract. Employer: Federation of Skye, Enemy: Free Worlds League, Location Blank, creates the following error log entry:
`18:53:30,203 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:291) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.universe.PlanetarySystem.getId()" because the return value of "mekhq.campaign.universe.Systems.getSystemByName(String, java.time.LocalDate)" is null`

When I close the error pop-up and choose Location: Ford and click OK, then I get a new error message:
![image](https://github.com/user-attachments/assets/d543edf6-22fd-4a0b-a517-aea87b25c6c5)
With the following log entry:
`18:55:44,787 WARN  [mekhq.campaign.stratcon.StratconContractDefinition] {AWT-EventQueue-0}
mekhq.campaign.stratcon.StratconContractDefinition$ContractDefinitionManifest.Deserialize(StratconContractDefinition.java:418) - Specified file ./data/stratconcontractdefinitions/UserContractDefinitionManifest.xml does not exist

18:55:44,803 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:291) - Uncaught java.lang.ArithmeticException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.ArithmeticException: / by zero`

[0.50.01-SNAPSHOT-logs2.zip](https://github.com/user-attachments/files/17693876/0.50.01-SNAPSHOT-logs2.zip)

**Comment by IllianiCBT** [comment]
This was fixed sometime around 50.01 closing as resolved
