### ISSUE TITLE
49.19-Snapshot Could Not Customize Unit Error

### ISSUE THREAD

**Issue by IllianiBird** [MegaMek/mekhq#3982]
### Environment
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 11.0.22
Platform: Mac OS X 13.6.6 (x86_64)

### Description
<img width="584" alt="image" src="https://github.com/MegaMek/mekhq/assets/103902653/b210d027-e8f9-42be-b3c1-06ac5b1c9933">

Load the file, make any change to the commando in the mhq meklab. When you attempt to begin refit you will be presented with this error. Refreshing the cache does not resolve this issue.

### Files
```
03:21:13,491 ERROR [mekhq.campaign.Campaign] {AWT-EventQueue-0}
mekhq.campaign.Campaign.getTargetFor(Campaign.java:4896) - Attempting to get the target number for a part with zero time left.

03:21:19,375 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0}
mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1578) - Could not read back refit entity Commando COM-2D Mk II
megamek.common.loaders.EntityLoadingException: Could not load Commando COM-2D Mk II from the mech cache
	at mekhq.Utilities.retrieveOriginalUnit(Utilities.java:1282)
	at mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1572)
	at mekhq.campaign.parts.Refit.begin(Refit.java:976)
	at mekhq.gui.CampaignGUI.refitUnit(CampaignGUI.java:1646)
	at mekhq.gui.MekLabTab.lambda$initTab$0(MekLabTab.java:122)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

03:21:19,377 WARN  [mekhq.campaign.parts.Refit] {AWT-EventQueue-0}
mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1582) - Deleting invalid refit file data/mechfiles/customs/My Campaign/Commando COM-2D Mk II.mtf
```

[IllianiCBT_#3982.zip](https://github.com/MegaMek/mekhq/files/14896311/IllianiCBT_.3982.zip)

**Comment by IllianiCBT** [comment]
Customizing the unit in mml and then refitting, within mhq, works without issue. As does refurbishing the unit, from within mhq. So it appears to only be the mhq meklab that's affected by this bug.
