### ISSUE TITLE
Attached campaign no longer loads after 49.19

### ISSUE THREAD

**Issue by Officer1473** [MegaMek/mekhq#4061]
Build Date: 2024-05-08T00:59:23.501593600
	Today: 2024-05-08
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.18
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

Attempting to upgrade from 49.10 with an older save file from possibly 49.07, 49.19 was not able to open the campaign. I discovered that the issues were related to the soldiers. I was able to open the campaign after I deleted the soldiers, but would have an error saying "Uncaught java.util.NoSuchElementException detected." that would occur sporadically when attempting to use the hire the minimum complement for battle armor and infantry. This occurred seemingly randomly. This is reproducible using other campaigns that were exported from this one.

The campaign can be opened by 49.18 and prior without the errors.

[mekhq.log](https://github.com/MegaMek/mekhq/files/15247407/mekhq.log)
[Infantry30590524.cpnx.gz](https://github.com/MegaMek/mekhq/files/15247481/Infantry30590524.cpnx.gz)
[units.zip](https://github.com/MegaMek/mekhq/files/15247419/units.zip)

**Comment by HammerGS** [comment]
Couple of errors in the log.

```
mekhq.campaign.personnel.Person.generateInstanceFromXML(Person.java:1906) - Failed to read person Unnamed Person from file
java.lang.NullPointerException
	at mekhq.campaign.personnel.Person.generateInstanceFromXML(Person.java:1593)
	at mekhq.campaign.io.CampaignXmlParser.processPersonnelNodes(CampaignXmlParser.java:858)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:233)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:346)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:202)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

and

```
mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:374) - 
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:370)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.Vector.lastElement(Vector.java:526)
	at mekhq.campaign.Campaign.clearGameData(Campaign.java:5748)
	at mekhq.campaign.unit.Unit.resetPilotAndEntity(Unit.java:3583)
	at mekhq.campaign.io.CampaignXmlParser.lambda$parse$0(CampaignXmlParser.java:386)
	at mekhq.campaign.Hangar.lambda$forEachUnit$0(Hangar.java:117)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at mekhq.campaign.Hangar.forEachUnit(Hangar.java:117)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:380)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:346)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:202)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Sleet01** [comment]
I can confirm this is new behavior in 0.49.19, as the campaign file loads fine in .11 ~ .18.
Unfortunately it doesn't look like loading in .18 and then re-saving will fix the issue; I'd hoped for a simple work-around like that.

I'll see what changed and how much work it will be to fix this.  If the solution looks A) simple, B) bulletproof, and C) easy to validate with tests, I'll add it to the backport list as well.

**Comment by Sleet01** [comment]
It looks like we should be using the name lookup if the ID lookup fails.

**Comment by HammerGS** [comment]
I can see we have the name change in the xml file.

**Comment by Sleet01** [comment]
Looks like there is another error while clearing entities after loading...
