### ISSUE TITLE
Issues rebuilding Infantry in MekHQ Mek Lab and Java Exception when attempting to add via GM Unit Purchase

### ISSUE THREAD

**Issue by BoloNike** [MegaMek/mekhq#4076]
### Environment
MekHQ v0.49.19
Build Date: 2024-04-19T14:55:55.057542200
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 11.0.22
Platform: Windows 10 10.0 (amd64)
System Locale: en_US
Total memory available to MekHQ: 16 GB

### Description
 - While attempting to adjust CI builds the following error appears
![image](https://github.com/MegaMek/mekhq/assets/169616408/22d8f708-3db4-44bd-8eba-9a7ccb9fb283)
 - Presuming this was a build error issue i recreated the build in MekLab [See Foot Platoon (Camo/IR Sniper/Grenade) -or- Jump Platoon (Marine Sniper/Grenade)] the build validated without issue so did not see a problem there.
 - Upon returning to MekHQ (restarted) it would still not allow me to build to that design but correctly stated that a design with that name exists. However it does not let me rebuild via refit kit to this new "variant"
 - Seeing this i decided to just GM order a new CI unit and transfer soldier to the new unit. These new units however come in "undamaged" with no-one assigned. "Dark Blue highlight"
![image](https://github.com/MegaMek/mekhq/assets/169616408/6d912ea6-56d2-452b-9811-5d29ed018456)
 - It is impossible to add this unit to the ToE and the following error appears when you go to add a soldier to the unit
![image](https://github.com/MegaMek/mekhq/assets/169616408/5166a699-2df3-4b72-9ae2-0bab3b4045c6)
![image](https://github.com/MegaMek/mekhq/assets/169616408/71bf9ea8-ab57-4fcd-8240-4562528e2704)
 - Other actions such as advancing a day also trigger this error. It is possible to add units until the platoon is "full" however there is no indication of further cascade effects that could be happening in the background.

### Files
 - Corrupted file
[Vehicle Campaign Corrupt.cpnx.gz](https://github.com/MegaMek/mekhq/files/15287634/Vehicle.Campaign.Corrupt.cpnx.gz)
 - Backup Save before issue existed
[Vehicle_Backup.cpnx.gz](https://github.com/MegaMek/mekhq/files/15287633/Vehicle_Backup.cpnx.gz)
 - Custom Designs (unsure of specifics as i use the same core files with another campaign. Linking whole custom folder)
[customs.zip](https://github.com/MegaMek/mekhq/files/15287638/customs.zip)
 - All 3 Logs.
[megamek.log](https://github.com/MegaMek/mekhq/files/15287639/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/15287640/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/15287641/mekhq.log)

Only other "custom" items are graphical like camos. can link if necessary

**Comment by BoloNike** [comment]
Part of the issue may be related to where HQ seems to be pulling the information. HQ shows the designs in TW non-box but they were designed under experimental.
![image](https://github.com/MegaMek/mekhq/assets/169616408/4a7ffa52-e532-423b-82f4-b0b915ecc943)
![image](https://github.com/MegaMek/mekhq/assets/169616408/86d2cd97-1fa3-49b5-9884-66b287b37079)

**Comment by HammerGS** [comment]
> Part of the issue may be related to where HQ seems to be pulling the information. HQ shows the designs in TW non-box but they were designed under experimental.
> 
> ![image](https://private-user-images.githubusercontent.com/169616408/329883800-4a7ffa52-e532-423b-82f4-b0b915ecc943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NTcxOTgsIm5iZiI6MTcxNTU1Njg5OCwicGF0aCI6Ii8xNjk2MTY0MDgvMzI5ODgzODAwLTRhN2ZmYTUyLWU1MzItNDIzYi04MmY0LWIwYjkxNWVjYzk0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQyMzM0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjI3MTM0ZGE5ZmM2YmQ2YWUzNzkyNzBmZDQ0ZGE3ZWY1NTQ4ZDJiNGVlMzk3NjM4ZmMzMjBmMjM3ZWU0MmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z3VGUn3bGP5AKXUuZeYhI3_9ZYufv2vZECjdCguox7I) ![image](https://private-user-images.githubusercontent.com/169616408/329883822-86d2cd97-1fa3-49b5-9884-66b287b37079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NTcxOTgsIm5iZiI6MTcxNTU1Njg5OCwicGF0aCI6Ii8xNjk2MTY0MDgvMzI5ODgzODIyLTg2ZDJjZDk3LTFmYTMtNDliNS05ODg0LTY2YjI4N2IzNzA3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQyMzM0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGE4NWQ1NDVmM2Y4ZGZmYzdkOTU1MTBmOTgzMGYxMjVhZTM3YjMzNzExMTllZDI2NTk0MTM0Y2Q5YTM2OGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-rFH1BIzlNLksLSGWPd9AGY-uYWt4LeyW_ZLWSlwtvY)
> 
> I did reset the unit Cache in HQ but this does not seem to have had any effect

Your Campaign looks like its 3026 so they would become Standard by then.

**Comment by HammerGS** [comment]
From the MM log:

```
15:40:28,649 ERROR [megamek.common.util.BuildingBlock] {AWT-EventQueue-0}
megamek.common.util.BuildingBlock.writeBlockFile(BuildingBlock.java:514) - Unable to save block file data\mechfiles\customs\Vehicle\Jump Platoon (Camo/IR Sniper/Grenade).blk
java.io.FileNotFoundException: data\mechfiles\customs\Vehicle\Jump Platoon (Camo\IR Sniper\Grenade).blk (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at megamek.common.util.BuildingBlock.writeBlockFile(BuildingBlock.java:504)
	at megamek.common.loaders.BLKFile.encode(BLKFile.java:1236)
	at mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1562)
	at mekhq.campaign.parts.Refit.begin(Refit.java:976)
	at mekhq.gui.CampaignGUI.refitUnit(CampaignGUI.java:1646)
	at mekhq.gui.MekLabTab.lambda$initTab$0(MekLabTab.java:122)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
```
From the MekHQ Log

```
5:49:56,100 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:242) - Uncaught Exception Detected
java.util.NoSuchElementException
	at java.base/java.util.Vector.lastElement(Unknown Source)
	at mekhq.campaign.Campaign.clearGameData(Campaign.java:5695)
	at mekhq.campaign.unit.Unit.resetPilotAndEntity(Unit.java:3582)
	at mekhq.campaign.unit.Unit.addPilotOrSoldier(Unit.java:4397)
	at mekhq.campaign.unit.Unit.addPilotOrSoldier(Unit.java:4383)
	at mekhq.gui.menus.AssignUnitToPersonMenu.lambda$createPersonAssignmentMenus$34(AssignUnitToPersonMenu.java:646)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

```

**Comment by OrbMonky** [comment]
This may be related - when going in to refit infantry, nothing populates.
![image](https://github.com/user-attachments/assets/0c8717d1-9954-4947-bf00-357a31a7f248)
This creates problems both for refitting to standard variants, and custom variants, as the custom has to be deleted, cleared from cache by refreshing, and then rebuilt from scratch if you wanted to make a few custom infantry.

**Comment by Sephok** [comment]
I had this or a similar problem today in 0.51.00. I customize an infantry unit, I begin the refit process using "Customize in Mek Lab..." and save the variant for later when I click "Begin Refit", then I go to the next infantry unit and the variant doesn't show up in the refit list. I "Customize in Mek Lab..." again, do the same things, "Begin Refit" and want to save the unit with the same name, but then I'm told a unit with that name exists already. I check the Purchase Unit dialog and as mentioned in OPs report, the unit appears.
I tried some more stuff and found that clicking "Save For Later" makes the refit show up in the refit menu. Now I only have the issue that I somehow have the same version showing up there twice. Not quite sure how I did that.
Anyway, both buttons create the .blk file in data/mekfiles/customs/[campaign name here], but apparently only "Save For Later" enters the unit into whatever database is used to select refits.

**Comment by Sephok** [comment]
Furthermore, I have found that I can only reduce the size of squads. I.e., I can take a Foot Platoon (Flamer) with 28 people, remove 1 flamer per squad and reduce the squad size from 7 to 6, and clicking "Begin Refit" will successfully create a 24 soldier single-flamer-per-squad platoon. But when I then do the same with a generic rifle squad to get the required auto rifles and try to increase the flamer squad back to 28, it doesn't take the rifles from the warehouse, it orders new ones (and I don't have instant procurement).
I think the infantry refit system can't properly access the warehouse for parts.

**Comment by Sephok** [comment]
Also, I finally managed to get the first error message from OPs post. That happened when I hit "Begin Refit" and edited the model name rather than the Chassis name. I kept Foot Platoon intact and added "4x1" (four squads, one soldier each, since I wanted those rifles for other refits and I didn't want Foot Platoon to be automatically changed to Foot Squad) at the front of the model name. I'm now pretty sure the model name is the representation of the sprite the unit has (dudes with guns, dudes with flamers, dudes with guns and machine guns etc.) and thus mustn't be changed to values that don't exist in wherever the models are stored.

**Comment by Sephok** [comment]
Phew! I've been able to refit a Foot Platoon (Flamer) into "Foot Platoon GM rifles (InfantryAssaultRifle) #2" (no idea why #2, nothing else exists that would be #1), still with the same 28 soldiers. How?
I used GM Buy in Bulk to get Brand New Auto-Rifles (Modern, Generic). I believe infantry can't access used weapons from the warehouse.

**Comment by Sephok** [comment]
> [...] I'm now pretty sure the model name is the representation of the sprite the unit has (dudes with guns, dudes with flamers, dudes with guns and machine guns etc.) and thus mustn't be changed to values that don't exist in wherever the models are stored.

Well actually, when creating a unit in the proper MegaMekLab, manually choosing the icon from the images folder and saving the unit creates an "icon" tag in the .blk file.
You see, I had the issue of all my refitted units looking like generic infantry, even when in the MekHQ Mek Lab the icon displayed e.g. a Motorized Platoon.
Currently, best thing for infantry seems to be creating the target refit versions in MegaMekLab, GM Adding them to your forces in MekHQ and deleting the previous unit. You just have to keep track of the equipment somehow.
