### ISSUE TITLE
[49.20] Full Screen Mode is not Supported Log Error

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#4342]
### Environment
Version: 49.20 & 50.0
OS: Mac OS X 14.5
Java: Eclipse Adoptium 17.0.11

### Description
Fresh install of the clients, opening an instance of mhq triggers the below error

```
09:39:11,084 ERROR [mekhq.gui.CampaignGUI] {AWT-EventQueue-0}
mekhq.gui.CampaignGUI.enableFullScreenMode(CampaignGUI.java:1238) - Full screen mode is not supported
java.lang.IllegalAccessException: class mekhq.gui.CampaignGUI cannot access class com.apple.eawt.FullScreenUtilities (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @2beee7ff
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at mekhq.gui.CampaignGUI.enableFullScreenMode(CampaignGUI.java:1236)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:279)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:155)
	at mekhq.MekHQ.showNewView(MekHQ.java:251)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:402)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Files
[mekhq.log](https://github.com/user-attachments/files/16111075/mekhq.log)

**Comment by IllianiCBT** [comment]
Closed as resolved
