### ISSUE TITLE
NPE new contract

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#4349]
### Environment
win 11
java 17
49.20

### Description
received error message when trying to accept recon raid contract

### Files
[mekhq.log](https://github.com/user-attachments/files/16114707/mekhq.log)
[Galatia Mecenary Coalition2.cpnx.gz](https://github.com/user-attachments/files/16114709/Galatia.Mecenary.Coalition2.cpnx.gz)

**Comment by repligator** [comment]
The contract in question can be accepted an infinite number of times (with each acceptance triggering an NPE) without being removed from the contract market.

`mekhq.MekHQ.lambda$main$1(MekHQ.java:288) - Uncaught Exception Detected
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:322)
	at megamek.common.MMRandom$CryptoRandom.randomInt(MMRandom.java:157)
	at megamek.common.MMRoll.<init>(MMRoll.java:65)
	at megamek.common.Compute.randomInt(Compute.java:246)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.setTerrain(AtBDynamicScenarioFactory.java:936)`

**Comment by bczretribution** [comment]
Additional info: after sending report, I found and took a new contract.  While on that contract, come this contracts start date, it did appear in the briefing room tab suddenly (was not there prior to), and I found myself on two contracts simultaneously.
