### ISSUE TITLE
v0.50.0-SNAPSHOT NPE while deploying units

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4588]
v0.50.0-SNAPSHOT
Win 10
Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11

### Description
Partway through deploying units at the start of the game, I keep running into a recurring npe that keeps coming back when I hit OK.
Unsure what the specific trigger is as it doesn't start until a number of units into the deployment phase.

### Files
[Trond's Dragoons30250219C.cpnx.gz](https://github.com/user-attachments/files/16554544/Trond.s.Dragoons30250219C.cpnx.gz)
[Bug1.sav.gz](https://github.com/user-attachments/files/16554546/Bug1.sav.gz)
[mekhq.log](https://github.com/user-attachments/files/16554547/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/16554548/megamek.log)

Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the megamek.log and mekhq.log files for any NPEs or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megamek.log and mekhq.log files
(Delete the above lines)

**Comment by IllianiCBT** [comment]
Seeing a lot of variations on this, in the log:

```23:29:09,267 ERROR [megamek.common.util.BuildingBlock] {Mech Cache Loader}
megamek.common.util.BuildingBlock.getDataAsInt(BuildingBlock.java:264) - getDataAsInt("Front_armor_tech") failed.
java.lang.NumberFormatException: For input string: "Inner Sphere"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at megamek.common.util.BuildingBlock.getDataAsInt(BuildingBlock.java:260)
	at megamek.common.loaders.BLKFile.loadSVArmor(BLKFile.java:374)
	at megamek.common.loaders.BLKSupportVTOLFile.getEntity(BLKSupportVTOLFile.java:87)
	at megamek.common.MechFileParser.parse(MechFileParser.java:159)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:48)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:41)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:787)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:772)
	at megamek.common.MechSummaryCache.checkForChanges(MechSummaryCache.java:254)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:243)
	at megamek.common.MechSummaryCache.lambda$getInstance$0(MechSummaryCache.java:84)
	at java.base/java.lang.Thread.run(Unknown Source)```
