### ISSUE TITLE
[0.50.0-SNAPSHOT] Personnel NPE on new day. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4594]
### Environment
17:49:23,359 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-09T01:19:57.861411807
    Today: 2024-08-09
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: d4cbbc48db154c3a9242440beee777dd1f803251
    MML Code Revision: e9c8ae3cdf57f52d8c5a7cae3de0f66d3db8ef1b
    MHQ Code Revision: 5371f2d2445b9ad4d6ee2454b47ceb838c1cc511

### Description
![image](https://github.com/user-attachments/assets/82ccb5df-fa1d-4a0f-a545-8bec07c21b80)

Day advances, character gives birth accompanied by an NPE. 
Looks to be education-related, but unsure.

Log gives the following error: 

```
19:51:44,894 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "String.isBlank()" because the return value of "mekhq.campaign.personnel.Person.getEduAcademyName()" is null
	at mekhq.campaign.personnel.procreation.AbstractProcreation.birth(AbstractProcreation.java:368)
	at mekhq.campaign.personnel.procreation.AbstractProcreation.processNewDay(AbstractProcreation.java:443)
	at mekhq.campaign.Campaign.processNewDayPersonnel(Campaign.java:3482)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3729)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$61(CampaignGUI.java:1096)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Files
[mekhq.log](https://github.com/user-attachments/files/16565160/mekhq.log)
[1st Rimward Hussars.zip](https://github.com/user-attachments/files/16565177/1st.Rimward.Hussars.zip)
[customs.zip](https://github.com/user-attachments/files/16565184/customs.zip)

**Comment by IllianiCBT** [comment]
One of mine. Pushing a fix momentarily.

**Comment by IllianiCBT** [comment]
Closing as resolved
