### ISSUE TITLE
MHQ takes over a minute to generate two scenarios, and then runs out of memory

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4601]
### Environment
Java 17
Linux
Master (latest PR https://github.com/MegaMek/mekhq/commit/5ab5959011ea22901321b5a4a0792da4d43d65ad)

### Description
I was playing MHQ and hit advance day. My CPU fan started to spin up. Normally scenario generation takes maximum of 5 seconds. This time it took over a minute. Two missions were generated. Big Battle: Ally Rescue and Hostile Facility - Heavy. I deleted the ATB scenario (sorry force of habit), but the StartCon one is strange. There are no enemy mechs of vees. Just turrets. I'll try to reload the autosave and see if I can replicate as soon as I post this (wanted to make sure I didn't accidentally overwrite the logs). The out of memory error is in the MM log.

EDIT: When reloading the auto-save I can't replicate the issue (tried 5 times). I hadn't been playing MHQ for very long, although some of that time was waiting for my OIC to graduate, which involved at least a years worth of Advance Multiple Days.

### Files
[mekhq.log](https://github.com/user-attachments/files/16570481/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/16570482/megamek.log)
[Omega Galaxy31521013.cpnx.gz](https://github.com/user-attachments/files/16570483/Omega.Galaxy31521013.cpnx.gz)
[Autosave-1-Omega Galaxy-31521012.cpnx.gz](https://github.com/user-attachments/files/16570484/Autosave-1-Omega.Galaxy-31521012.cpnx.gz)

**Comment by repligator** [comment]
Possibly the same issue as https://github.com/MegaMek/mekhq/issues/4535 .

**Comment by Sleet01** [comment]
Certainly looks like the same issue:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.math.BigInteger.valueOf(BigInteger.java:1227)
	at java.base/java.math.BigInteger.and(BigInteger.java:3498)
	at megamek.common.EquipmentType.hasFlag(EquipmentType.java:513)
	at megamek.common.weapons.Weapon.adaptToGameOptions(Weapon.java:198)
	at megamek.common.Mounted.adaptToGameOptions(Mounted.java:243)
	at megamek.common.Entity.setGameOptions(Entity.java:12246)
	at megamek.common.Entity.restore(Entity.java:938)
	at megamek.common.Infantry.restore(Infantry.java:1698)
	at megamek.common.Entity.setGame(Entity.java:1013)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.createEntityWithCrew(AtBDynamicScenarioFactory.java:1848)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.createEntityWithCrew(AtBDynamicScenarioFactory.java:1823)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.generateTransportedBAUnit(AtBDynamicScenarioFactory.java:1721)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.fillTransport(AtBDynamicScenarioFactory.java:1527)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.fillTransports(AtBDynamicScenarioFactory.java:1463)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:737)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:254)
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.finalizeScenario(AtBDynamicScenarioFactory.java:186)
	at mekhq.campaign.stratcon.StratconRulesManager.generateScenariosForTrack(StratconRulesManager.java:169)
	at mekhq.campaign.stratcon.StratconRulesManager.handleNewDay(StratconRulesManager.java:1697)
	at jdk.internal.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at megamek.common.event.EventListener.trigger(EventListener.java:42)
	at megamek.common.event.EventBus.internalTrigger(EventBus.java:161)
	at megamek.common.event.EventBus.trigger(EventBus.java:150)
	at mekhq.MekHQ.triggerEvent(MekHQ.java:650)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3759)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$61(CampaignGUI.java:1096)
	at mekhq.gui.CampaignGUI$$Lambda$703/0x00007743ac9c1378.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
```
While the error was reported in the MegaMek log (presumably due to firing while in MM code), it actually was generated while creating a transport filled with BAs, in `mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:737)`

**Comment by Sleet01** [comment]
@repligator I will close this as a dupe, but the data will be helpful.
