### ISSUE TITLE
0.50 nightly NPE trying to load campaign file

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4654]
### Environment
v0.50.0-SNAPSHOT (2024-08-15 evening's nightly)
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

### Description
getting an npe when trying to load campaign file in latest nightly

### Files
[Trond's Dragoons30250225A.cpnx.gz](https://github.com/user-attachments/files/16633161/Trond.s.Dragoons30250225A.cpnx.gz)
[Trond's Dragoons30250225.cpnx.gz](https://github.com/user-attachments/files/16633172/Trond.s.Dragoons30250225.cpnx.gz)
(tested with both files, same result)
[customs.zip](https://github.com/user-attachments/files/16633163/customs.zip)
[megamek.log](https://github.com/user-attachments/files/16633166/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16633169/mekhq.log)

**Comment by Tzahr** [comment]
Was able to replicate; the campaign save doesn't load, so at least it's not a faulty install. 
Both logs gives the following error:
 
`08:23:45,980 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because the return value of "java.util.function.Function.apply(Object)" is null
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:221)
	at java.base/java.util.Arrays.sort(Arrays.java:1308)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1804)
	at mekhq.gui.CommandCenterTab.refreshObjectives(CommandCenterTab.java:621)
	at mekhq.gui.CommandCenterTab.initObjectivesPanel(CommandCenterTab.java:369)
	at mekhq.gui.CommandCenterTab.initTab(CommandCenterTab.java:137)
	at mekhq.gui.CampaignGuiTab.<init>(CampaignGuiTab.java:44)
	at mekhq.gui.CommandCenterTab.<init>(CommandCenterTab.java:116)
	at mekhq.gui.enums.MHQTabType.createTab(MHQTabType.java:123)
	at mekhq.gui.CampaignGUI.addStandardTab(CampaignGUI.java:1165)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:217)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:156)
	at mekhq.MekHQ.showNewView(MekHQ.java:268)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:421)
	at java.desktop/javax.swing.SwingWorker$4.run(SwingWorker.java:749)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

---
[mekhq.log](https://github.com/user-attachments/files/16633691/mekhq.log)

**Comment by IllianiCBT** [comment]
So this is being caused because you've somehow gained two hostile facility scenarios whose status is 'current' (i.e. unresolved) but their due date is null. Have you deleted any scenarios recently?

**Comment by IllianiCBT** [comment]
I figured it out. Let's just say you have a couple of surprises still left on your StratCon map :P

**Comment by IllianiCBT** [comment]
Closed as resolved
