### ISSUE TITLE
NPE in RandomNameGenerator.generateGivenNameSurnameSplit()

### ISSUE THREAD

**Issue by Algebro7** [MegaMek/mekhq#4706]
### Environment
Current master
Linux
JDK 17

### Description
I carried forward my 49.20 campaign to 0.50 today and got the following error when advancing the day:

```
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "megamek.common.util.weightedMaps.WeightedIntMap.randomItem()" is null
        at megamek.client.generator.RandomNameGenerator.generateGivenNameSurnameSplit(RandomNameGenerator.java:225)
        at mekhq.campaign.personnel.generator.AbstractPersonnelGenerator.generateName(AbstractPersonnelGenerator.java:127)
        at mekhq.campaign.personnel.generator.DefaultPersonnelGenerator.generate(DefaultPersonnelGenerator.java:103)
        at mekhq.campaign.Campaign.newPerson(Campaign.java:1489)
        at mekhq.campaign.Campaign.newPerson(Campaign.java:1463)
        at mekhq.campaign.Campaign.newPerson(Campaign.java:1428)
        at mekhq.campaign.Campaign.newPerson(Campaign.java:1416)
        at mekhq.campaign.market.PersonnelMarketCampaignOps.generatePersonnelForDay(PersonnelMarketCampaignOps.java:60)
        at mekhq.campaign.market.PersonnelMarket.generatePersonnelForDay(PersonnelMarket.java:121)
        at mekhq.campaign.Campaign.newDay(Campaign.java:3731)
        at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
        at mekhq.gui.CampaignGUI.lambda$initTopButtons$62(CampaignGUI.java:1099)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Files
[Bishop's Marauders30290731.cpnx.gz](https://github.com/user-attachments/files/16741476/Bishop.s.Marauders30290731.cpnx.gz)

**Comment by Algebro7** [comment]
Most likely, yeah--I haven't been able to replicate it either since then. Sorry for the false alarm!
