### ISSUE TITLE
NPE with campaign.universe.RandomFactionGenerator.addBorderEnemy

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#490]
From this post.

http://bg.battletech.com/forums/index.php?topic=58956.0

_Decided to start a new campaign on this build. Set up all my options, and was about to start adding personnel when I noticed I forgot to add portraits. Saved and closed it. Now it will not open. Any help would be appreciated._

```
java.lang.NullPointerException
	at mekhq.campaign.universe.RandomFactionGenerator.addBorderEnemy(RandomFactionGenerator.java:531)
	at mekhq.campaign.universe.RandomFactionGenerator.updateBorders(RandomFactionGenerator.java:502)
	at mekhq.campaign.universe.RandomFactionGenerator.updateTables(RandomFactionGenerator.java:454)
	at mekhq.campaign.Campaign.restore(Campaign.java:3030)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:194)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:116)
```

[mekhqlog-cpnx.zip](https://github.com/MegaMek/mekhq/files/1364695/mekhqlog-cpnx.zip)

**Comment by neoancient** [comment]
This was triggered when trying to find potential enemies for pirate hunting and riot duty contracts for pirate factions. As near as I can tell, the bug has been there since the beginning but was not triggered because pirate-controlled planets were too distant from the campaign location to be considered. This changed with updated data that gives pirates control of Acamar from 3058-3061.

I fixed the code to prevent the NPE. Workaround for now is to set the campaign in a different time or use a planets.xml file from a previous version.
