### ISSUE TITLE
[0.50.01-SNAPSHOT] Mechanics & Aero Teks cause NPE on right-click - (previously: mechanical wunderkind disturbs resting code gods) 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4948]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

In attached save, a newborn called **Klaas Olatunji** was generated with Tech/Mechanic skills.
Right clicking him in the personnel menu causes an NPE. 

Error logs the following error: 
> 04:45:19,286 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
> mekhq.MekHQ.lambda$main$1(MekHQ.java:290) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
> java.lang.NullPointerException: Cannot invoke "megamek.common.options.IOption.getType()" because the return value of "mekhq.campaign.personnel.PersonnelOptions.getOption(String)" is null
> 	at mekhq.gui.adapter.PersonnelTableMouseAdapter.createPopupMenu(PersonnelTableMouseAdapter.java:2197)
> 	at mekhq.gui.adapter.JPopupMenuAdapter.maybeShowPopup(JPopupMenuAdapter.java:74)
> 	at mekhq.gui.adapter.JPopupMenuAdapter.mouseReleased(JPopupMenuAdapter.java:69)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1 - Rev. b5a4f6a63622f97b768c9dcb2124f544cc986ce8

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17183209/mekhq.log)
[1st Rimward Hussars THE MECHANICAL CHILD.zip](https://github.com/user-attachments/files/17183210/1st.Rimward.Hussars.THE.MECHANICAL.CHILD.zip)
[customs.zip](https://github.com/user-attachments/files/17183227/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Tzahr** [comment]
Upon further investigation, it appears this NPE happens for every Mechanic and AeroSpace Tek, while MekTeks and BA Techs are unaffected.

**Comment by Tzahr** [comment]
This will auto-sanitize on saving and reloading, and is therefore an edge transition case that a simple save and reload will fix. No further action required - closing.
