### ISSUE TITLE
Trying to edit a destroyed protomech results in a null pointer error. 

### ISSUE THREAD

**Issue by BrandonSmith16** [MegaMek/mekhq#4985]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Attempting to edit the CT structure or in some cases edit the unit at all if it has a destroyed torso will result in an uncaught exception. 

### Steps to Reproduce

Load a protomech into mekhq. Set the CT health to zero. Confirm. Try to edit the unit's damage again. 

### Operating System *

Windows 10

### Java Version *

17.7

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at megamek.client.ui.swing.UnitEditorDialog$CheckCritPanel.<init>(UnitEditorDialog.java:1571)
	at megamek.client.ui.swing.UnitEditorDialog.setupProtoSystemPanel(UnitEditorDialog.java:767)
	at megamek.client.ui.swing.UnitEditorDialog.initSystemPanel(UnitEditorDialog.java:383)
	at megamek.client.ui.swing.UnitEditorDialog.initComponents(UnitEditorDialog.java:118)
	at megamek.client.ui.swing.UnitEditorDialog.<init>(UnitEditorDialog.java:102)
	at mekhq.gui.adapter.UnitTableMouseAdapter.actionPerformed(UnitTableMouseAdapter.java:467)
```

[mekhq.log](https://github.com/user-attachments/files/17265005/mekhq.log)

**Comment by NickAragua** [comment]
Fixed with MM 6512.
