### ISSUE TITLE
[0.50.01-2024-10-05] Semi-repeatable NPE on deploying forces, scenarioMod null

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5000]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

Deploying forces in this save is intermittantly causes NPEs about scenarioMod

### Steps to Reproduce

1. Load provided save.
2. Deploy lances on ATB panel (I've been putting Beta on 0101 and also trying 0202 and 0103 with the other two).
3. One of them should NPE about 20% of the time. If it doesn't happen, restart MegaMek and try again.

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01-SNAPSHOT 2024-10-05

### Attach Files

```
09:33:09,244 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:306) - Starting MekHQ v0.50.1-SNAPSHOT
    Build Date: 2024-10-06T03:25:24.214306127
    Today: 2024-10-07
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.2-201.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 82fc89ceba5bfdb40670ba90bdc3e3ca1027a07b
    MML Code Revision: 446bd8d9c7e28bfdf49d35f312d838c44e16941a
    MHQ Code Revision: 976204bfa54b995b2d45159b080d13dba8a16ee5
```

```
09:33:32,947 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:290) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.mission.atb.AtBScenarioModifier.getBlockFurtherEvents()" because "scenarioMod" is null
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.setScenarioModifiers(AtBDynamicScenarioFactory.java:1455)
	at mekhq.campaign.stratcon.StratconRulesManager.generateScenario(StratconRulesManager.java:821)
	at mekhq.campaign.stratcon.StratconRulesManager.generateScenario(StratconRulesManager.java:790)
	at mekhq.campaign.stratcon.StratconRulesManager.setupScenario(StratconRulesManager.java:423)
	at mekhq.campaign.stratcon.StratconRulesManager.deployForceToCoords(StratconRulesManager.java:393)
	at mekhq.gui.stratcon.TrackForceAssignmentUI.actionPerformed(TrackForceAssignmentUI.java:119)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

-- see comment for savefile --

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by WeaverThree** [comment]
Ack, I missed a cutsom in the provided zip, here's a fixed one:

[0.50.01-2024-10-05 NPE.zip](https://github.com/user-attachments/files/17283135/0.50.01-2024-10-05.NPE.zip)

**Comment by IllianiCBT** [comment]
I think this has been resolved. Keep an eye out, but I'm fairly confident I resolved this the other day.

Tentatively closing as resolved.
