### ISSUE TITLE
[0.50.01-2024-10-22] Launching MM from MHQ a second time crashes it even if you cancel.

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5128]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

If you try to start MegaMek from MekHQ when MM is already running, and cancel at the player name window, it will crash the first MM instance with this error:

```
09:22:21,457 ERROR [mekhq.MekHQ] {Connection 0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:291) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot invoke "megamek.common.force.Force.getOwnerId()" because the return value of "megamek.common.force.Forces.getForce(int)" is null
	at megamek.server.totalwarfare.TWGameManager.lambda$removeAllEntitiesOwnedBy$6(TWGameManager.java:466)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at megamek.server.totalwarfare.TWGameManager.removeAllEntitiesOwnedBy(TWGameManager.java:467)
	at megamek.server.totalwarfare.TWGameManager.disconnect(TWGameManager.java:380)
	at megamek.server.Server.disconnected(Server.java:867)
	at megamek.server.Server$1.disconnected(Server.java:236)
	at megamek.common.net.connections.AbstractConnection.processConnectionEvent(AbstractConnection.java:388)
	at megamek.common.net.connections.AbstractConnection.close(AbstractConnection.java:163)
	at megamek.common.net.connections.AbstractConnection.update(AbstractConnection.java:306)
	at megamek.server.ConnectionHandler.run(ConnectionHandler.java:47)
	at java.base/java.lang.Thread.run(Thread.java:840)

09:22:21,883 ERROR [mekhq.AtBGameThread] {Predator Dragons}
mekhq.AtBGameThread.configureBot(AtBGameThread.java:496) - Could not configure bot Capellan Confederation Base Defenses

09:22:47,039 ERROR [mekhq.AtBGameThread] {Predator Dragons}
mekhq.AtBGameThread.configureBot(AtBGameThread.java:496) - Could not configure bot Capellan Confederation OpFor

09:23:12,192 ERROR [mekhq.AtBGameThread] {Predator Dragons}
mekhq.AtBGameThread.configureBot(AtBGameThread.java:496) - Could not configure bot Federated Suns Allied Mek Reinforcements

09:23:37,344 ERROR [mekhq.AtBGameThread] {Predator Dragons}
mekhq.AtBGameThread.configureBot(AtBGameThread.java:496) - Could not configure bot Capellan Confederation Recon Meks
```

While this is a case of "Well, don't do that," I've lost progress to it twice when going back to MHQ to review objectives. Probably the buttons for starting the game should be locked while MM is still running?

### Steps to Reproduce

1. Get to a point where you can launch an ATB/stratcon game from the briefing room
2. "Start Game"
3. Minimize MegaMek (this can happen while it's in the lobby or later)
4. "Start Game" again
5. Optional: Go "Oh wait, I already started the game."
6. "Cancel"
7. Observe crash

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01-SNAPSHOT 2024-10-22

### Attach Files

09:21:38,720 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:307) - Starting MekHQ v0.50.1-SNAPSHOT
    Build Date: 2024-10-22T15:21:50.842015614
    Today: 2024-10-24
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.3-200.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 630bba8695c2b1004e65501fe900f4e1b8c9e973
    MML Code Revision: 384380362038ce744734c3a05836fd5d511d1df0
    MHQ Code Revision: 770a321c0b49cc7c6afac4ff3fefd26108b6df40

[0.50.01-2024-10-22 MHQ to MM Twice Crash.zip](https://github.com/user-attachments/files/17510010/0.50.01-2024-10-22.MHQ.to.MM.Twice.Crash.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by firefly2442** [comment]
I'm unable to replicate this issue as of: a215de857981804e44c2969a20c2d31d1d47b1ba.
