### ISSUE TITLE
Attempting to change tech bases for battle armor in the Mek Lab causes a null pointer error 

### ISSUE THREAD

**Issue by BrandonSmith16** [MegaMek/mekhq#5186]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/54cd8345-56ff-4944-9e13-ba77bde77444)
![image](https://github.com/user-attachments/assets/494f1ef5-538b-4a1a-99a2-58ef7dd4357a)
Best i can tell the issue is related to the game attempting to equip weapons into the battle claw slot. This has been an issue since 0.49.7 or 49.14 I forget which. 

### Steps to Reproduce

Load a battle armor unit into the hangar. Load the unit into the lab. Attempt to change the tech base. Sometimes you can fix this by manually removing the weapon that it places in the battle armor claw location. 
It will almost always occur if you swap between clan and IS but might not occur if you swap to mixed IS or Mixed Clan. 
Examples include the sloth(swapping to clan) and the gnome(Swapping to IS). 
This also sometimes occurs when you try to swap between advanced, experimental and standard. 
Examples include the kanazuchi[Standard] (Swapping to advanced or experimental from standard)
 and Nephilim[Plasma] (Swapping from Advanced to standard)
These units are just examples given to make replicating the issue easier, the issue is incredibly widespread.

### Operating System *

Windows 10

### Java Version *

17.7

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HammerGS** [comment]
Can you attach the logs please.

**Comment by BrandonSmith16** [comment]
Where are they located?

**Comment by HammerGS** [comment]
In the Logs folder, we'd need the three of them

**Comment by BrandonSmith16** [comment]
[megamek.log](https://github.com/user-attachments/files/17692296/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/17692297/mekhq.log)
[megameklab.log](https://github.com/user-attachments/files/17692298/megameklab.log)

**Comment by HammerGS** [comment]
```
09:26:37,037 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot read field "internalName" because "manipulator" is null
	at megameklab.ui.battleArmor.BAStructureTab.setManipulator(BAStructureTab.java:290)
	at megameklab.ui.battleArmor.BAStructureTab.actionPerformed(BAStructureTab.java:276)
```

**Comment by BrandonSmith16** [comment]
Does that mean the bug where it tries to put weapons/armor in battle armor claw slots is probably another issue entirely? 
![image](https://github.com/user-attachments/assets/a368978f-60c3-4adb-8213-29a81dafe28d)

**Comment by BrandonSmith16** [comment]
That part is much less of an issue since you can just...remove the weapon/armor it places there. 
![image](https://github.com/user-attachments/assets/3391bdb3-82cc-42ac-aa41-a8703ec8f045)

**Comment by HammerGS** [comment]
If I had to guess, the Manipulators aren't selected on the first tab. But we have significant issues with refits especially in the non-mech units. It's a goal of the 0.50.x to fix and improve these but we are just too early in the process. 

Some players have had success making the unit in standalone MML, then doing it as a refit kit rather than trying to use MML in MekHQ

**Comment by BrandonSmith16** [comment]
> Some players have had success making the unit in standalone MML, then doing it as a refit kit rather than trying to use MML in MekHQ

That has been the workaround since I started playing a few years ago, yes
