### ISSUE TITLE
Campaign save failed due to bad contract ally camouflage

### ISSUE THREAD

**Issue by TenkawaBC** [MegaMek/mekhq#5300]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

Save failed due to failure to find camouflage for the Filtvelt Coalition. This occurred when trying to save the game immediately after progressing to January 1, 3087. 

15:53:34,412 WARN  [mekhq.campaign.mission.AtBContract] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBContract.pickRandomCamouflage(AtBContract.java:277) - No files in directory Filtvelt Coalition - using default camouflage

15:53:34,424 ERROR [mekhq.campaign.mission.AtBContract] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBContract.pickRandomCamouflage(AtBContract.java:262) - Error getting list of camouflages
java.nio.file.NoSuchFileException: data\images\camo\Filtvelt Coalition
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.find(Files.java:4036)
	at mekhq.campaign.mission.AtBContract.pickRandomCamouflage(AtBContract.java:258)
	at mekhq.campaign.mission.AtBContract.initContractDetails(AtBContract.java:230)
	at mekhq.campaign.market.contractMarket.AtbMonthlyContractMarket.generateAtBContract(AtbMonthlyContractMarket.java:310)
	at mekhq.campaign.market.contractMarket.AtbMonthlyContractMarket.generateAtBContract(AtbMonthlyContractMarket.java:209)
	at mekhq.campaign.market.contractMarket.AtbMonthlyContractMarket.generateContractOffers(AtbMonthlyContractMarket.java:169)
	at mekhq.campaign.market.contractMarket.AbstractContractMarket.generateContractOffers(AbstractContractMarket.java:166)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:3754)
	at mekhq.campaign.Campaign.newDay(Campaign.java:4275)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$62(CampaignGUI.java:1103)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Steps to Reproduce

1. Get bot generated contract for the filtvelt coalition in 3087.
2. Try to save the campaign

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/18015519/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Please attach your broken save and customs folder so we can investigate

**Comment by TenkawaBC** [comment]
Advance the date to Jan 1, 3087 and try to save.
[Anti-blake30861228.cpnx.gz](https://github.com/user-attachments/files/18016902/Anti-blake30861228.cpnx.gz)
[Anti-blake.zip](https://github.com/user-attachments/files/18016915/Anti-blake.zip)

**Comment by DM0000** [comment]
Does your Filtvelt Coalition folder in camos have the 2 camo options?

**Comment by DM0000** [comment]
Nevermind looks like typo in contract Filtvelt Coalition   in the camo folder is spelled Filtvelt Coaltion
