### ISSUE TITLE
NPE on loading with getActiveCrew (Old cpnx file)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#544]
Cambo had made the entire Clan Wolf ToE for Circa 3052. Its a massive file and project and think its worth either fixing the file or MekHQ to keep it going.  NPE on loading.  I have fixed all unit name errors, I think their are some mounted errors also in the logs.  I'm assuming that is a simple rename process.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1497155/mekhqlog.txt)
[Clan Wolf TOE Nov 22 2017cpnx.zip](https://github.com/MegaMek/mekhq/files/1497165/Clan.Wolf.TOE.Nov.22.2017cpnx.zip)

```
java.lang.NullPointerException
	at mekhq.campaign.unit.Unit.getActiveCrew(Unit.java:3507)
	at mekhq.campaign.rating.CampaignOpsReputation.calcLargeCraftSupportValue(CampaignOpsReputation.java:738)
	at mekhq.campaign.rating.CampaignOpsReputation.getSupportValue(CampaignOpsReputation.java:752)
	at mekhq.campaign.rating.CampaignOpsReputation.calculateUnitRatingScore(CampaignOpsReputation.java:381)
	at mekhq.campaign.rating.CampaignOpsReputation.getModifier(CampaignOpsReputation.java:778)
	at mekhq.campaign.Campaign.checkBloodnameAdd(Campaign.java:5621)
	at mekhq.campaign.Campaign.checkBloodnameAdd(Campaign.java:5555)
	at mekhq.campaign.Campaign.newPerson(Campaign.java:5434)
	at mekhq.campaign.Campaign.newPerson(Campaign.java:5284)
	at mekhq.campaign.market.PersonnelMarket.generatePersonnelForDay(PersonnelMarket.java:264)
	at mekhq.campaign.market.PersonnelMarket.<init>(PersonnelMarket.java:81)
	at mekhq.campaign.Campaign.createCampaignFromXMLFileInputStream(Campaign.java:3870)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:193)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by NickAragua** [comment]
It's funny, I loaded it up in my dev branch and got the crash mentioned. Then I loaded it up again, and didn't get the crash. Then I saved it again. Now it loads up every time without the exception. 

It does show some missing SRM ammo for every elemental point and all the large craft are listed as "crippled", but that's probably because of some ammo changes and crew accounting changes respectively.

[Clan Wolf TOE30520602.zip](https://github.com/MegaMek/mekhq/files/1498025/Clan.Wolf.TOE30520602.zip)

**Comment by neoancient** [comment]
This is old enough (0.2.0) that it apparently predates the personnel market. Since none is found in the campaign file it generates one, then in the process of checking for Bloodname checks the unit rating, which in turn checks whether large craft have crews. Since this is before the `campaign` field is set on all units, it throws an NPE when trying to retrieve a `Person` by id.

I see no reason for the personnel and other markets to be generated at that point in loading the campaign so I moved that block of code to the end and tested to make sure newer campaigns still load without problem (though any campaign file created after the various markets appeared should never trigger that code anyway).
