### ISSUE TITLE
12/26 Nightly / 0.50.02 SNAPSHOT - IllegalArgumentException detected when unmothballing a unit. Unit ID 131, RFL-3N

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5548]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/5ab2d99a-8217-4dbb-a781-c5c22cafb7ca)
This happened after loading MekHQ, going to repair bay, auto repairing, then seeing I had tech time to unmothball more stuff. I unmothballed a rifleman (ID:179) then attempted to unmothball rifleman (ID:131). I was not able to reproduce on a relaunch/reload.

the save appended with mothball is the post-error save.
[logs.zip](https://github.com/user-attachments/files/18265113/logs.zip)

### Steps to Reproduce

1. Load normal save not appended by mothball
2. run repair bay auto repair
3. unmothball rifleman ID:179
4. unmothball rifleman ID:131

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/26 Nightly / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Looking at the logic I suspect you tried unmothballing the second Rifleman before the first had finished processing and the table had updated.

**Comment by OrbMonky** [comment]
It would have had to be a significant hang, I'm on a 5950 w/64 gb ram, 16
gb available to mhq. The first unit was unmothballed in the gui before I
unmothballed the second one. Then again I have noticed since moving to the
12/26 nightly I do get several second hangs particularly around repair
bay/hangar.

**Comment by IllianiCBT** [comment]
I'm struggling to replicate this myself. Can you think of anything unusual you might have been doing at the time?

**Comment by IllianiCBT** [comment]
Seeing this in the log when loaded into the latest nightly:

```13:19:47,592 ERROR [mekhq.campaign.parts.Refit] {SwingWorker-pool-2-thread-1}
mekhq.campaign.parts.Refit.generateInstanceFromXML(Refit.java:2340) - 
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at mekhq.campaign.parts.Refit.generateInstanceFromXML(Refit.java:2308)
	at mekhq.campaign.unit.Unit.generateInstanceFromXML(Unit.java:2130)
	at mekhq.campaign.io.CampaignXmlParser.processUnitNodes(CampaignXmlParser.java:1262)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:253)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:407)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:216)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)```

**Comment by IllianiCBT** [comment]
And, of course, it's never appeared again...
