### ISSUE TITLE
Updating to 50.02 returning error on campaign launch

### ISSUE THREAD

**Issue by Felerial** [MegaMek/mekhq#5572]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

Attempted to update from 50.00 to 50.02. Upon loading save file, received Uncaught Exception java.lang.NumberFormatException error.

Per Discord advice, attempted to update from 50.00 to 50.01 first. Update successful with no issues. Update from 50.01 to 50.02 returned the same error as updating from 50.00 to 50.02.

### Steps to Reproduce

1. Fresh install of 50.02
2. Copy over my save file to the main directory. 
3. Copy over data\images and the interior of data\mechfiles as 50.02 has renamed that file to mekfiles. 
4. Load save file, unable to launch at last step.
5. I then tried a new install, and simply copied over everything in data while not overwriting anything, (and manually transferring mechfiles to the new mekfiles) still no luck.

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18282507/logs.zip)
[Valkyrie30420303.cpnx.gz](https://github.com/user-attachments/files/18282509/Valkyrie30420303.cpnx.gz)
[mekfiles.zip](https://github.com/user-attachments/files/18282518/mekfiles.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
So, something is causing your used cargo to fail to parse correctly. This bug looks like it's present in 50.01, too, it just failed elegantly so you didn't notice.

**Comment by Felerial** [comment]
Is this something I can fix myself? Or is it something that needs to be fixed on the coding side and just stick to 50.00 for now?

**Comment by IllianiCBT** [comment]
OK, I've narrowed it down to something in your warehouse, at least

**Comment by IllianiCBT** [comment]
In 50.01, go into your warehouse and track down your 0 rounds of inferno ammo. Remove that, save, and you'll be good to go. :)

**Comment by IllianiCBT** [comment]
While this issue has been resolved for this specific user, this case should not be closed until the root cause has been tracked down.

**Comment by NickAragua** [comment]
I'm looking at it. 

This is a prime situation where the "streaming" approach to writing code is suboptimal - the issue is somewhere on line 93 of cargostatistics.java, which produces a "NaN" ("Not a Number") for the total tonnage value. Now, if it was a regular loop, you could go through and put a conditional breakpoint in there and look for things with a NaN tonnage and discount them. The "stream" approach is great if you can assume all the data contained in there is "good".

**Comment by IllianiCBT** [comment]
Yeah, I have completely gone off streams ever since you pointed out that they weren't even cheaper, memory-wise. Without that, any value went out the window, in my eyes.

**Comment by mwberlindeu** [comment]
I think that I may have the same bug.

20:48:37,252 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:296) - Uncaught java.lang.NumberFormatException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:608)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:497)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:903)
	**at mekhq.campaign.CampaignSummary.getCargoCapacityReport(CampaignSummary.java:291)**
	at mekhq.gui.CommandCenterTab.refreshBasicInfo(CommandCenterTab.java:604)
	at mekhq.gui.CommandCenterTab.refreshAll(CommandCenterTab.java:562)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:258)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:164)
	at mekhq.MekHQ.showNewView(MekHQ.java:268)
	at mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:473)
	at java.desktop/javax.swing.SwingWorker$4.run(SwingWorker.java:749)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[mekhq.log](https://github.com/user-attachments/files/18285288/mekhq.log)

**Comment by mwberlindeu** [comment]
> In 50.01, go into your warehouse and track down your 0 rounds of inferno ammo. Remove that, save, and you'll be good to go. :)

This quick fix also solved the issue for me. 

![grafik](https://github.com/user-attachments/assets/1ec2e5c7-f272-42bb-bb84-86533eca3c0f)

I deleted the "zero" ammunition (standard ammo and auto rifle ammo).
