### ISSUE TITLE
Smallcraft Breaking Campaigns

### ISSUE THREAD

**Issue by jayof9s** [MegaMek/mekhq#637]
Using 0.43.7-RC1

Windows 7 - Java 8 update 161 (build 1.8.0_161-b12)

Adding a smallcraft to a campaign and saving will make the campaign unable to load in the future. An example campaign file is included.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1690506/mekhqlog.txt)
[My Campaign30670102.zip](https://github.com/MegaMek/mekhq/files/1690507/My.Campaign30670102.zip)

Update: Appears to be tied to the Variable Tech Level option if it is Off.

**Comment by HammerGS** [comment]
NPE from Log

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.parts.Part.getTechBase(Part.java:1517)
	at mekhq.campaign.parts.Part.adjustCostsForCampaignOptions(Part.java:338)
	at mekhq.campaign.parts.Part.getActualValue(Part.java:330)
	at mekhq.campaign.unit.Unit.getSellValue(Unit.java:1066)
	at mekhq.campaign.Campaign.getFinancialReport(Campaign.java:7916)
	at mekhq.gui.FinancesTab.initTab(FinancesTab.java:183)
	at mekhq.gui.CampaignGuiTab.<init>(CampaignGuiTab.java:48)
	at mekhq.gui.FinancesTab.<init>(FinancesTab.java:77)
	at mekhq.gui.GuiTabType.createTab(GuiTabType.java:88)
	at mekhq.gui.CampaignGUI.addStandardTab(CampaignGUI.java:414)
	at mekhq.gui.CampaignGUI.initComponents(CampaignGUI.java:338)
	at mekhq.gui.CampaignGUI.<init>(CampaignGUI.java:219)

**Comment by NickAragua** [comment]
I'm fairly confident this was fixed when #638 was fixed. Does it still happen for new small craft?

**Comment by mkerensky** [comment]
I found the Ares Mk III Assault Craft and Aquarius Escort in particular to have some bugs, as the BLK files changed between 0.43.6 and 0.43.7

I removed the old ones from my campaign and added new of the same model under 0.43.8  and was able to clear the issues I noticed.  In my case, the issues were ammo bins that could not be reloaded and SI/Armor falsely showing as damaged because the max values changed.

**Comment by jayof9s** [comment]
Yeah, I think we can close this. After the changes Nick made and replacing
with new versions of the craft, the errors were all cleared up.

People should probably be encouraged to replace small craft, dropships,
etc. as the files are updated to reflect the improvements to their blk
files Hammer has been working on.
