### ISSUE TITLE
Unable to open Campaignoptions

### ISSUE THREAD

**Issue by BRDiger** [MegaMek/mekhq#677]
Hey guys, found another one. Though is suspect that it´s more related to my game and me tinkering than mhq in general.

### Environment
0.43.9 RC3
OS:  Windows 7 + 10
J: V8 U161

### Description
For some builts i experienced problems while trying to open my campaignoptions:
I click it, it and nothing happens.

`Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at javax.swing.SpinnerNumberModel.<init>(Unknown Source)
	at javax.swing.SpinnerNumberModel.<init>(Unknown Source)
	at mekhq.gui.dialog.CampaignOptionsDialog.initComponents(CampaignOptionsDialog.java:1973)
	at mekhq.gui.dialog.CampaignOptionsDialog.<init>(CampaignOptionsDialog.java:463)
	at mekhq.gui.CampaignGUI.menuOptionsActionPerformed(CampaignGUI.java:1674)
	at mekhq.gui.CampaignGUI.access$1000(CampaignGUI.java:163)
	at mekhq.gui.CampaignGUI$12.actionPerformed(CampaignGUI.java:719)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)` 

I suspect something was changed within the options. Can reproduce the problem with my old presets by starting a new game. Using those Presets and trying to change them. I´m very reluctant to lose the campaign i played for years ;)
What was changed and has to be deleted in my campaignfiles /presets?

### Files

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1842484/mekhqlog.txt)

[colt.zip](https://github.com/MegaMek/mekhq/files/1842487/colt.zip)

**Comment by NickAragua** [comment]
As a workaround, you should be able to go into your .cpnx file with a text editor, look for an xml element that looks like this: <equipmentContractPercent>[some number]</equipmentContractPercent>. In your preset, that number is 10.0. Set it to 5.0, and you should be good to go.

**Comment by BRDiger** [comment]
Thanks a lot Nick. That fixed it...<equipmentContractPercent>10.0</equipmentContractPercent>was the culprit. Seems like an old transferbug since you can´t increase the combat percentage (Mercenary Basecontract Payment) above 5.0 any longer.
