### ISSUE TITLE
OutOfMemoryError on Princess bot turn

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#685]
### Environment
MekHQ: 0.43.9
OS: Windows 10
Java: 1.8.0_161-b12

### Description
I am occasionally getting an OutOfMemoryError on Princess's turn, resulting in MegaMek hanging.  I believe this is the 5th time this has happened in 45 battles in my current campaign.

This is the callstack of the error:
```
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at megamek.client.bot.BotClient$1.gameTurnChange(BotClient.java:134)
	at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:51)
	at megamek.common.Game.processGameEvent(Game.java:3132)
	at megamek.common.Game.setTurnIndex(Game.java:743)
	at megamek.client.Client.changeTurnIndex(Client.java:564)
	at megamek.client.Client.handlePacket(Client.java:1306)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:1594)
	at megamek.client.Client$1$2.run(Client.java:220)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
```
When this happens, the buttons in MegaMek stop drawing correctly (they are the same color as the background).  Unfortunately, I did not think to grab a screenshot before restarting the client.  That makes me wonder if this is related to the tooltip error that also shows in the logs (and which has been fixed).

I have to restart MekHQ to get Princess to work correctly again.  After doing so, I load the game and it works fine.

This is the memory usage from megameklog.txt:
```
08:31:35,842 INFO [megamek.server.Server] {Packet Pump} 
Round 0 memory usage: 211,760 kB

08:32:54,785 INFO [megamek.server.Server] {Packet Pump} 
Round 1 memory usage: 336,031 kB

08:35:24,893 INFO [megamek.server.Server] {Packet Pump} 
Round 2 memory usage: 390,298 kB

08:38:54,350 INFO [megamek.server.Server] {Packet Pump} 
Round 3 memory usage: 429,408 kB

08:43:24,805 INFO [megamek.server.Server] {Packet Pump} 
Round 4 memory usage: 302,279 kB

08:45:56,301 INFO [megamek.server.Server] {Packet Pump} 
Round 5 memory usage: 393,436 kB

08:50:15,676 INFO [megamek.server.Server] {Packet Pump} 
Round 6 memory usage: 361,719 kB
```

The memory usage doesn't look insane.  I could attach megameklog.txt as well, but it is quite large and there doesn't seem to be anything else of note.

### Files
[mekhqlog.bak.txt](https://github.com/MegaMek/mekhq/files/1864063/mekhqlog.bak.txt)

There is another log showing this attached to this bug:
https://github.com/MegaMek/mekhq/issues/682

**Comment by NickAragua** [comment]
A couple of questions:

1) What phase is this happening on?
2) Is that phase set to simultaneous?

**Comment by Dylan-M** [comment]
The other question that Nick forgot, is what is your max memory for Java set to (this is different by OS and by how you launch the software)? Keep in mind, that if you're launching from MHQ, some of the max memory is consumed by MHQ. If your max memory is set to 512MB for the combined process and together they exceed that amount, this error will happen. Chances are that you just need to raise the setting.

See: https://github.com/MegaMek/megamek/wiki/Memory-and-our-software

**Comment by BlueThing00** [comment]
@NickAragua:

1) This time it happened on the movement phase.  I don't recall for sure when it happened for the others.
2) I am not using simultaneous for any phases.

My memory is set to the defaults.  I tried to increase the memory, but doing so causes MekHQ to fail to start.  I and a couple of others have requested more details on how to increase the memory usage in the 0.43.9 thread.

I have the same problem now.  I tried changing mekhq.l4j.ini to use -Xmx2048m.  It fails to start and leaves an empty mekhqlog.txt.

I have a similar experience increasing the memory usage in megamek.l4j.ini and trying to run MegaMek.

I have 16 GB of RAM and windows indicates that over 10 GB is still available, so bumping MekHQ or MegaMek to use 2 GB should be no problem.

**Comment by dericpage** [comment]
Are you running a 32 or 64 bit operating system?

**Comment by BlueThing00** [comment]
64 bit.

**Comment by Dylan-M** [comment]
I bet you've installed the 32 bit Java though. Because that's exactly the symptoms you're describing.

**Comment by BlueThing00** [comment]
Could be.

I just installed the 64 bit, and it didn't complain about already being installed.

After installing the 64 bit, I was able to increase the memory sizes without a problem.  I increased MekHQ to 2048 and MegaMek to 1536.

**Comment by Dylan-M** [comment]
Closing as invalid due to incorrect Java.
