### ISSUE TITLE
Campaign file cannot be loaded (ArrayIndexOutOfBounds)

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#76]
I have a feeling this is related to several refits that I had running at the time...

java.lang.ArrayIndexOutOfBoundsException: -1
    at mekhq.campaign.unit.Unit.initializeParts(Unit.java:1771)
    at mekhq.campaign.Campaign.createCampaignFromXMLFileInputStream(Campaign.java:3969)
    at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:184)
    at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:113)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

[#battletech.zip](https://github.com/MegaMek/mekhq/files/264977/battletech.zip)

**Comment by Question2** [comment]
Just had it happen on a new save, this time i didnt have any refits going.

I did some testing and figured out the cause. Refitting an Elemental [MG] point to the [MG 2] variant causes the save file to become unloadable after the refit is finished.

test save is the save before the refit is done, test2 is the save after the refit is done and the save cannot be loaded.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/266432/battletech.zip)

**Comment by Dylan-M** [comment]
Post-Stable because BA aren't fully implemented.

**Comment by neoancient** [comment]
Resolved by d56a13d.
