### ISSUE TITLE
Post game salvage/prisoners didn't show up. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#824]
I thought I'd since this one before but I can't seem to find it.

From our forums - https://www.megamek.org/bb/thread-2544.html

From the current stable.

```
java.lang.NullPointerException
at mekhq.campaign.Campaign.checkBloodnameAdd(Campaign.java:5713)
at mekhq.campaign.Campaign.checkBloodnameAdd(Campaign.java:5597)
at mekhq.campaign.Campaign.newPerson(Campaign.java:5485)
at mekhq.campaign.Campaign.newPerson(Campaign.java:5333)
at mekhq.Utilities.genRandomCrewWithCombinedSkill(Utilities.java:644)
at mekhq.campaign.ResolveScenarioTracker.processPrisonerCapture(ResolveScenarioTracker.java:726)
at mekhq.campaign.ResolveScenarioTracker.checkStatusOfPersonnel(ResolveScenarioTracker.java:672)
at mekhq.campaign.ResolveScenarioTracker.processGame(ResolveScenarioTracker.java:414)
at mekhq.MekHQ.gameVictory(MekHQ.java:511)
at megamek.common.event.GameVictoryEvent.fireEvent(GameVictoryEvent.java:70)
at megamek.common.Game.processGameEvent(Game.java:3132)
at megamek.client.Client.handlePacket(Client.java:1474)
at megamek.client.Client$1$2.run(Client.java:220)
```

Login the attachment. Campaing file https://ufile.io/5e8jr

**Comment by neoancient** [comment]
Related to #600 and #621.
Before those were fixed captured personnel were created based on whether the player's faction was Clan or Spheroid. That fix did not extend to Bloodname generation, so any Clan warriors captured by an Inner Sphere faction attempt to use the IS faction to generate any Bloodnames.
