### ISSUE TITLE
[dev-44.0] NPE when right-clicking on personnel in personnel table

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#837]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.personnel.AwardsFactory.loadAwards(AwardsFactory.java:139)
	at mekhq.campaign.personnel.AwardsFactory.<init>(AwardsFactory.java:57)
	at mekhq.campaign.personnel.AwardsFactory.getInstance(AwardsFactory.java:62)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.maybeShowPopup(PersonnelTableMouseAdapter.java:1777)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.mouseReleased(PersonnelTableMouseAdapter.java:1096)
	[snip]

Reproduced by right-clicking on any person in the personnel tab.

This is probably happening because I don't have the awards folder in the proper location (I just built the jar, but didn't update any of the data). The method specified in the exception needs to be bulletproofed. This is a reminder to myself for tonight, unless @bandildo gets to it first.

**Comment by bandildo** [comment]
Sorry about this. I'll won't be available to fix it in the next 24h.
