### ISSUE TITLE
0.45 Awards - Adding additional sets of awards

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#848]
0.45
Linux
Java 1.8.0_171

Awesome feature, but I'm having trouble adapting it. 

I was able to find and edit the relevant files in order to modify the "Default Set" of awards without any trouble but I then tried to create an additional set of awards (new image files for both ribbons and medals with a separate .xml file under the data/universe folder) in order to display a rank insignia as though it were a medal.

I've only been able to get this new set of awards to display the ribbon graphics - The larger medal images will not display at all. 

Eventually I just added the graphics and the .xml for the new "rank" set of awards to the existing Default Set. 

This did work and ALL added graphics displayed without issue - but with so many additions to the Default Set the awards pop-up list became too long to navigate.

**Comment by bandildo** [comment]
Regarding the pop-up list being too long to navigate, this should be fixed in the next release. It was an oversight from my behalf, sorry about that. A workaround I've recommended to other community members is to divide those awards into different award sets.

To create a new award set, you need to have a NewAward.xml, and three different folders for the graphics, just like the DefaultSet. The three folders need to have those specific names. So, if you have a `My New Set.xml` you should have three folders with the graphics:
`/data/images/awards/My New Set/medals/` 
`/data/images/awards/My New Set/misc/`
`/data/images/awards/My New Set/ribbons/`

Let me know if this helps out the issue. Otherwise, attach your .xml and image files, so I can test it out.

**Comment by servo01** [comment]
That fixed it. 

Apparently it was just the absence of a "misc" folder with the "new set" of awards that was keeping the medal graphic from being displayed. 

Thanks for the response!

**Comment by bandildo** [comment]
Great!

We should leave this ticket open, though, to implement some extra bulletproofing to avoid this issue. Users shouldn't be obliged to create an empty folder.

**Comment by servo01** [comment]
I appear to still be having problems with adding a new set. 

Everything seems to work fine, provided the new set of awards is limited to the first three entries or less (file attached) 

Attempting to add more than three awards to the New Set.xml results in the set disappearing from the pop-up menu entirely. I've tried renaming the image and directory files as well as going over the .xml in case the problem was being caused by a syntax  or formatting issue. So far - limiting the .xml to the first three entries has been the only thing I've done that allows new awards to show up in the menu and the medal image to be displayed. 

I also tried dividing the new awards into multiple sets, but that only seemed to cause everything but the Default Set to disappear from the pop-up. 

Image and .xml files have been attached for further testing.
[New Set.zip](https://github.com/MegaMek/mekhq/files/2263019/New.Set.zip]

**Comment by mchapman1970** [comment]
This is the error I get when I try to put a badge in the misc folder.  it does show on the list of awards to add and it does put the award in the personal log but it wont display the badge.

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 3
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.actionPerformed(PersonnelTableMouseAdapter.java:554)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by bandildo** [comment]
@servo01 it seems your xml is wrongly configured from the 4th entry till the end: the closing </description> are missing the backslah. After adding the backslash and adding the medals to the awards/New Set/medals/ folder, it seems to work fine.

@mchapman1970 could you attach your award files and configuration? I can't replicate it, it seems something different.

**Comment by mchapman1970** [comment]
I figured mine out so no worries

**Comment by servo01** [comment]
Confirmed - Syntax issue with my XML was causing the problem. Everything is now working fine.

**Comment by mchapman1970** [comment]
![image](https://user-images.githubusercontent.com/22855199/44124298-18971d5c-9ff2-11e8-834b-f82a82cc81d3.png)

**Comment by Schugger** [comment]
Hi,
as I didn't know about to create new folders for medals, I saved the original one elsewhere and played around with the original set. 
To avoid scrolling down to much, I put my own created awards on the top of the xml. file.
Unfortunatly, when adding to many new awards the scroll down menu appearing in MHQ gets messy (i.e. not wide enough to display the awards you are going to give). Do you guys know anything about the number of awards in the folder is limited so that the display in MHQ does not mess up?

**Comment by Windchild292** [comment]
As far as I can tell this has been fixed, the folders not being there is now handled properly.
