### ISSUE TITLE
Multi-Day Repairs in Warehouse Not Working (0.45.0)

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#853]
When starting a multi-day repair (i.e. one which does not finish in the same day it was started) in the warehouse, the part in question disappeared forever from the warehouse.

There´s no message in the log, and they don´t re-appear or produce a log entry on later days, including the day the repair should have been finished.

Since the option to pay for repairs was added in this snapshot, and I had it turned on, I tried turning it off - the bug still happens. 

FWIW, single-day repairs work fine, and so do multi-day repairs in the repair bay.

[mekhqlog repair bug.txt](https://github.com/MegaMek/mekhq/files/2263749/mekhqlog.repair.bug.txt)

The first two blocks of error messages appear in the log even if no multi-day repairs are attempted; the first is probably caused by a custom awards file I made.

**Comment by SirChaos1** [comment]
Here you go:
[Chaos Legion30170101.zip](https://github.com/MegaMek/mekhq/files/2270513/Chaos.Legion30170101.zip)

Just checked again, FWIW - this happens in all my saves; I´ve attached one that doesn´t need a heap of customs in order to load. Here´s the log for the attempt with this save: 
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2270524/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
From the log:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.Campaign.fixPart(Campaign.java:2155)
	at mekhq.campaign.Campaign.fixWarehousePart(Campaign.java:2063)
	at mekhq.gui.WarehouseTab.doTask(WarehouseTab.java:731)
	at mekhq.gui.WarehouseTab.lambda$initTab$3(WarehouseTab.java:340)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
```
