### ISSUE TITLE
MekHQ custom in the meklab?

### ISSUE THREAD

**Issue by 69chrisd69123** [MegaMek/mekhq#900]
### Environment
0.44.0 mekhq
Windows, 
Current
Description
I have received this notification 4 times now. In my campaign I am trying to customize a few mechs with advanced tech during 3048. In the earlier versions I have never encountered this and if I use just the separate meklab they are valid designs but not showing up? Is this because of the fact I am using the new ATB rules? 
![image](https://user-images.githubusercontent.com/42626937/44682459-476b5480-a9f8-11e8-9919-8144c50ee50c.png)

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2325436/mekhqlog.txt)

[Hawk's Ronin11-09-3048.zip](https://github.com/MegaMek/mekhq/files/2325440/Hawk.s.Ronin11-09-3048.zip)
[Hawk's Ronin.zip](https://github.com/MegaMek/mekhq/files/2325441/Hawk.s.Ronin.zip)

**Comment by HammerGS** [comment]
Errors in the Log - This guy twice
```
Error parsing null!
megamek.common.loaders.EntityLoadingException: Unable to match Artemis to launcher for Griffin GRF-1N Mk II
	at megamek.common.MechFileParser.postLoadInit(MechFileParser.java:364)
	at megamek.common.MechFileParser.parse(MechFileParser.java:206)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:85)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:77)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:590)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:552)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:552)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:252)
	at megamek.common.MechSummaryCache$1.run(MechSummaryCache.java:101)
```
This guy next
```
    Loading from data\mechfiles\customs\Hawk's Ronin\Griffin GRF-1N Mk II.mtf
***   Unable to load file: megamek.common.loaders.EntityLoadingException: While parsing file Griffin GRF-1N Mk II.mtf, Unable to match Artemis to launcher for Griffin GRF-1N Mk II
	at megamek.common.MechFileParser.<init>(MechFileParser.java:91)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:77)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:590)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:552)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:552)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:252)
	at megamek.common.MechSummaryCache$1.run(MechSummaryCache.java:101)
```

**Comment by 69chrisd69123** [comment]
I had even LRM 5 Artemis IV ammo. Is there a work around for this because I have 2 other mechs using Artemis IV

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by HammerGS** [comment]
Try putting the Artemis IV under the LRM in the design would be my own recommendations

**Comment by 69chrisd69123** [comment]
That's right I didn't do that

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
