### ISSUE TITLE
No Weapons for Custom Units - NPE

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#907]
Opening for someone on Slack.

With MekHQ .44 custom units weapons don't show up in Weapon View panel.

Logs show NPE
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.common.Entity.getTotalMunitionsOfType(Entity.java:3562)
	at megamek.client.ui.swing.unitDisplay.WeaponPanel$WeaponListModel.getElementAt(WeaponPanel.java:277)
	at megamek.client.ui.swing.unitDisplay.WeaponPanel$WeaponListModel.getElementAt(WeaponPanel.java:161)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1360)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
```

[No Weapons for Custom Mens.zip](https://github.com/MegaMek/mekhq/files/2334213/No.Weapons.for.Custom.Mens.zip)

**Comment by HammerGS** [comment]
issue appears resolved.

**Comment by HammerGS** [comment]
False alarm the issue still exists.

**Comment by Craftnburn** [comment]
It appears the issue is definitely related to the 2 custom vehicles.  Running the same scenario with them removed from the lance gives no errors.

**Comment by Craftnburn** [comment]
I've also eliminated the specific scenario as a cause.  I completed the scenario (without the units) and moved to another scenario, but that one hangs as well.  I'm not sure what's the issue with the ammunition that's causing the NPE.  I haven't changed any ammunition types.

**Comment by Craftnburn** [comment]
Well, I deleted the Custom Behemoth and recreated it and I no longer get the error.  Still not sure what I did wrong, but ... ¯\_(ツ)_/¯
